### ISSUE TITLE
Auth processResponse doesn't throw an invalid_reponse OneLogin_Saml2_Error

### ISSUE THREAD

**Issue by dustinlindquist** [onelogin/php-saml#101]
If a response fails to validate, the _errors[] has a 'invalid_response' added to it but no OneLogin_Saml2_Error is raised. For consolidated error handling wouldn't it be best to raise an exception? Similar to the invalid_binding error?

**Comment by pitbulk** [comment]
You can raise this exception in the code that executes the validation.
Notice that the getLastErrorReason method will return the reason for the invalidation.
