### ISSUE TITLE
Encryption is enabled in the metadata even though it's disabled

### ISSUE THREAD

**Issue by Ronnie-J** [onelogin/php-saml#102]
Hello.

I am using version 2.6.1.

I am trying to have an ADFS automatically configure it self by consuming the SP Metadata generated by the `OneLogin_Saml2_Metadata` class. In my configuration I have disabled(false) `nameIdEncrypted` and `wantNameIdEncrypted`. 

But when I generate the Metadata for the SP I get this;

```
<md:KeyDescriptor use="encryption">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>
(certificate)
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
```

So the ADFS reads this as if it should use encryption, not just signing. Reading the code(Settings.php line 671) it looks like this package sets signing and encryption to be enabled if a certificate is present. My current configuration doesn't seem to encrypt when communicating with the ADFS since I disabled encrypting on `nameIdEncrypted` and `wantNameIdEncrypted` so it makes no sense that the generated Metadata would reflect that it does.

I should say that I dont "run" the ADFS that another department, but I was told that encryption now was enabled in the ADFS via the metadata and they dont want that, only signing should be enabled. Does that make any sense?

Your thoughts?

**Comment by pitbulk** [comment]
This is something that we can improve at the toolkit and only offer a 
<md:KeyDescriptor use="encryption"> when the settings requires it.

```
I should say that I dont "run" the ADFS that another department, but I was told that encryption now was enabled in the ADFS via the metadata and they dont want that, only signing should be enabled.
```
At ADFS I think you are able to switch-off the encryption in an independent way of what is published at the SP metadata.

**Comment by Ronnie-J** [comment]
I think they can disable it to but only with manuel configuration. The problem is that they would like to let the SP's be self explanatory by consuming the metadata from the SP. Thats not possible at the moment since the encryption is enabled in the metadata. 

A setting to this library would be fine in our case.

**Comment by pitbulk** [comment]
Merged
