### ISSUE TITLE
URL with multiple parameters as a query string

### ISSUE THREAD

**Issue by unumai** [onelogin/php-saml#104]
Hello there.
 If anyone have seen before this type of error....
 Lets take the 'Demo1' for example, if i try to make the assertionConsumerService or       singleLogoutService a link to an service where i will be needing at least two query strings params it returns that the metadata is wrong 'Invalid SP metadata: unloaded_xml'

Ex:
         'singleLogoutService' => array (
                         'url' => $spBaseUrl.'/demo1/index.php?sls=test&param2=test',

 For now i have tested on SP settings and it gives this error when i try to access the metadata file.
 Thanks.
      Dan.

**Comment by pitbulk** [comment]
Don't add parameters in the settings.

If you want to add extra parameters to the logout request petition notice that the [logout method](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L366) contains a parameters var where you may defined them.

So keep:
```
singleLogoutService' => array (
    'url' => $spBaseUrl.'/demo1/index.php?sls
),
```

and use
```
$parameters = array (
   'param2' =>test'
)
$auth->logout(null, $parameters); 
```
