### ISSUE TITLE
Response -> validateNumAssertions() logic error.

### ISSUE THREAD

**Issue by Dimentar** [onelogin/php-saml#107]
I think the logic of [validateNumAssertions()](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L492) function from Response of SAML2 is wrong because Assertion or EncryptedAssertion can have Advice element, that inside can contain more than 1 another Assertion's or EncryptedAssertion's. The result of function will be false even the Response is valid. 
According the [Documentation](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)

**Comment by pitbulk** [comment]
You are right, but this toolkit only support 1 Assertion.

**Comment by pitbulk** [comment]
Toolkit tries to follow [saml2int profile](http://saml2int.org/profile/current/)

```
Assuming a successful response, the <saml2p:Response> message issued by an Identity Provider MUST contain exactly one assertion (either a <saml2:Assertion> or an <saml2:EncryptedAssertion> element).
```

**Comment by Dimentar** [comment]
Inside [saml2int](http://saml2int.org/profile/current/) there is no any word about **Advice** element.
From [saml2int](http://saml2int.org/profile/current/) also, inside **10 Normative References** I found **[SAML2Core]** which has
> Advice [Optional]
Additional information related to the assertion that assists processing in certain situations but which
MAY be ignored by applications that do not understand the advice or do not wish to make use of it.

> The **Advice** element contains any additional information that the SAML authority wishes to provide.
This information MAY be ignored by applications without affecting either the semantics or the validity of the assertion.
The **Advice** element contains a mixture of zero or more **Assertion**, **EncryptedAssertion**, **AssertionIDRef**, and **AssertionURIRef** elements, and namespace-qualified elements in other non-SAML namespaces.

**Comment by Dimentar** [comment]
Hi @pitbulk.
Could you reopen this issue?

**Comment by gdbnet** [comment]
+1

**Comment by pitbulk** [comment]
Sorry but we don't plan to support Advice element.

**Comment by Dimentar** [comment]
Even if I made a PR [#113](https://github.com/onelogin/php-saml/pull/113) with Advice validation implemented?

**Comment by pitbulk** [comment]
If the Service Provider gonna ignore the content of the Advice element, (99% of use cases) I don't see any point of supporting that element.

Support the scenario of more than 1 Assertion only implies possible security issues.

If you have this requirement for your specific protect, you always can extend the toolkit and adapt it to your needs.
