### ISSUE TITLE
Authentication success even though IdP x509 cert has expired

### ISSUE THREAD

**Issue by riula** [onelogin/php-saml#111]
Hello,

Curious as to why authentication succeeds when the IdP provided certificate has expired. I've gone through the sample code and scoured the library source for any clues as to where it might check the certificates "validTo" attribute, but can't seem to make any progress. 

Thoughts?

**Comment by pitbulk** [comment]
In the toolkit we validate the signature of the SAMLResponse with the public certificate, but we don't analyze the certificate itself. ([xmlseclibs](https://github.com/onelogin/php-saml/blob/master/extlib/xmlseclibs/xmlseclibs.php) does not support that neither).

But if your environment require it, you can extract the public cert from the settings file and validate it.
Review:
https://github.com/simplesamlphp/simplesamlphp/blob/f25c7815af52a751cb815709ff33abee14e130a4/modules/authX509/lib/Auth/Process/ExpiryWarning.php#L69

**Comment by riula** [comment]
Sorry for the delayed response, thank you for clarifying. It seems this is a normal approach for most implementations as I've talked to a few vendors and this was the general response. 

Thanks again!
