### ISSUE TITLE
SLO Redirect?

### ISSUE THREAD

**Issue by adamxp12** [onelogin/php-saml#114]
I am working on developing a module for a CMS called PrcoessWire to add SSO, this library has been a big help in this but I think I may of found a bug (or I am being stupid)

I have got SLO working by looking at the examples but despite defining a redirect url as per the example it will not redirect and always stays on the page saying "Sucessfully logged out" (not my spelling)
I want it to redirect back to the homepage of the website and I am not sure if maybe the code in the example is wrong or something but it is just not having any of it

`$auth = new OneLogin_Saml2_Auth();
 $auth->logout($config->urls->root);`

This is the code I am using (minus the includes and session_start)
It does log out just fine but just refuses to redirect, even if I set the url manually instead of getting from a config variable.

Might just me being stupid as SAML does go a little bit over my head but I see no reason why it should not work?

**Comment by pitbulk** [comment]
When you set a URL on the logout method a [RelayState parameter is sent in the GET petition to the IdP](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L390)

Maybe your IdP removes that RelayState parameternor override it instead on sending it back.
Can you analyze the reply of the IdP?

After process the SLO, closing the local session you can check if there is a RelayState paramter and then redirect to it. See for example this WordPress SAML plugin:
https://github.com/pitbulk/wordpress-onelogin/blob/master/onelogin-saml-sso/php/functions.php#L368

**Comment by adamxp12** [comment]
Well that has helped me get closer to the result
the only issue is now its ignoring the url I pass with $auth->logout($url)
But instead giving me the url of the page where $auth->logout is called
which will take me back to the login page because I would be trying to access a page that's blocked

the $url variable contains the homepage of the website which is where I would ideally like it to be directed to.

**Comment by pitbulk** [comment]
@adamxp12 have you solved that issue?
