### ISSUE TITLE
Two errors when logging out

### ISSUE THREAD

**Issue by mstone42** [onelogin/php-saml#115]
I could not find a onelogin forum, and I'm completely new to the code, so my apologizes up front.  Any guidance, recommendations, alternate sites to post this to, would be greatly appreciated.

We are getting two different logout errors when using the OneLogin SAML2 library.  

- The first error is "invalid_logout_request".

Back-tracking thru the code, the problem appears to be that PHP is decoding the `$_GET['SAMLRequest']` by replacing the '+' with ' ', so the `OneLogin_Saml2_LogoutRequest` constructor is producing garbage, which is not error checked before calling the `OneLogin_Saml2_LogoutRequest::getID`, which in turn is throwing a `PHP FATAL error: Call to a member function getAttribute() on a non-object`.

The solution I implemented was to pass the 'SAMLRequest' from the query string rather than $_GET.  There is the `$retrieveParametersFromServer` parameter being passed into the `OneLogin_Saml2_Auth::processSLO()` method, but it is not used to fetch the '`SAMLRequest`' or '`SAMLResponse`' values before passing them to their respective constructors.

- The second error is "logout_not_success".

This is getting thrown because we are getting back a `STATUS_PARTIAL_LOGOUT` status (don't know why, or what this means exactly), but the OneLogin code does not address this status anywhere (not even the unit tests).  Since the error is already being set before getting back to our code (i.e. I have no idea where else to check for this status except in the onelogin code), my solution here was to include a check for this status at the same time that `STATUS_SUCCESS` is checked for.

Altho, as a rule, we do not change third party library code, here are the code changes I've had to make:

```php
/** in our code, the call to OneLogin_Saml2_Auth::processSLO()
 set $retrieveParametersFromServer to TRUE, instead of the default FALSE */
$samlAuth->processSLO(FALSE, NULL, TRUE);
```
```php
// in OneLogin_Saml2_Auth::processSLO()
if (isset($_GET) && isset($_GET['SAMLResponse']))
{
	$samlResponse = (($retrieveParametersFromServer === TRUE)
		? OneLogin_Saml2_Utils::extractOriginalQueryParam('SAMLResponse')
		: $_GET['SAMLResponse']);
	$logoutResponse = new OneLogin_Saml2_LogoutResponse($this->_settings, $samlResponse);
	$responseIsValid = $logoutResponse->isValid($requestId, $retrieveParametersFromServer);
	$responseStatus = $logoutResponse->getStatus();

	if (!$responseIsValid)
	{
		$this->_errors[] = 'invalid_logout_response';
		$this->_errorReason = $logoutResponse->getError();
	}
	elseif ($responseStatus !== OneLogin_Saml2_Constants::STATUS_SUCCESS
		&& $responseStatus !== OneLogin_Saml2_Constants::STATUS_PARTIAL_LOGOUT)
	{
		$this->_errors[] = 'logout_not_success';
	}
	else // ...
}
elseif (isset($_GET) && isset($_GET['SAMLRequest']))
{
	$samlRequest = (($retrieveParametersFromServer === TRUE)
		? OneLogin_Saml2_Utils::extractOriginalQueryParam('SAMLRequest')
		: $_GET['SAMLRequest']);
	$logoutRequest = new OneLogin_Saml2_LogoutRequest($this->_settings, $samlRequest);
	// ...
```

```php
// in OneLogin_Saml2_LogoutRequest::getId()
// add error checking just in case the decode/inflate from constructor still fails
public static function getID($request)
{
	$dom = $id = FALSE;

	if ($request instanceof DOMDocument)
	{
		$dom = $request;
	}
	elseif (!empty($request))
	{
		$dom = new DOMDocument();
		$dom = OneLogin_Saml2_Utils::loadXML($dom, $request);
	}

	if (($dom instanceof DOMDocument) && $dom->documentElement->hasAttribute('ID'))
	{
		$id = $dom->documentElement->getAttribute('ID');
	}

	return $id;
} 
```

Thanks in advance

**Comment by mstone42** [comment]
I know it's questionable whether this is really a bug, but ... ~any~ help would be a big help.
An alternate place to post this?  A link to a similar problem?
Anyone?
Bueller?

**Comment by pitbulk** [comment]
Can you provide the full trace of the error? I don't understand the decoding error you experienced on $_GET['SAMLRequest'] (by replacing the '+' with ' ')

The $request used at getID method should be valid (is the same assumption that I made for the rest of get/parser methods).

**Comment by mstone42** [comment]
Here is the relevant PHP stack trace for the fatal error in getId (we're currently using version 2.6.0):
```
PHP Fatal error:  Call to a member function getAttribute() on a non-object in lib/ol_saml/php-saml-master/lib/Saml2/LogoutRequest.php on line 139
PHP Stack trace:
...
PHP  13. OneLogin_Saml2_Auth->processSLO() lib/thirdparty_ol_saml.php:258
PHP  14. OneLogin_Saml2_LogoutRequest->__construct() lib/ol_saml/php-saml-master/lib/Saml2/Auth.php:163
PHP  15. OneLogin_Saml2_LogoutRequest::getID() lib/ol_saml/php-saml-master/lib/Saml2/LogoutRequest.php:105
```
The '+' is getting replaced with a ' ' by either the browser or PHP itself, because it assumes that the '+' is a string concatenator, not a character to be interpreted exactly.
Here is actual data.  Note the ' ' in the GET string, but the '+' in the QUERY string.  As I mentioned originally, when we modify the code to pull the SAMLRequest value from the QUERY string, the fatal error no longer occurs.
```
$_GET['SAMLRequest'] = 'nZLbTsJAEIZfhfR e5i2lG6ABEShpqCxBpUbstvdYiPdLd3lUJ/ecjBBL7zwdvL/33yZTFeRYl3iWK7kVj/xzZYr3YpGPWOZpTRgkDLEw8BGHgMbhWkIiHs89G2ADgPXaM15pXIpegaYttGKlNrySChNhG5GttNGNiAHngGwH2IAEwAWRutQrIXCp9U9Y1sJLInKFRak4ArrFCeDaYwbIi4rqWUq10a/e0zj04Lqqv93nSjFK934Gf13rUuFLSvLWWGu8lVNzFQW1pFh7Zqs5S7LydIdv82cfQKLzv6F5ZM59dxpTOtG4nb8qj7JQrKhTwau9tmsEneBv6jpRj7u/DioUde6crwIzxqnaPQfYXqfkAcxnNx8eL0L Qw7k0uccHU8fSQYP/S9IKNtSjyUeT5DXupkiNiEItohhIDjExvaZ8qv4vfwxwf0vwA=';
$_SERVER['QUERY_STRING'] = 'q=/saml_logout&SAMLRequest=nZLbTsJAEIZfhfR+e5i2lG6ABEShpqCxBpUbstvdYiPdLd3lUJ/ecjBBL7zwdvL/33yZTFeRYl3iWK7kVj/xzZYr3YpGPWOZpTRgkDLEw8BGHgMbhWkIiHs89G2ADgPXaM15pXIpegaYttGKlNrySChNhG5GttNGNiAHngGwH2IAEwAWRutQrIXCp9U9Y1sJLInKFRak4ArrFCeDaYwbIi4rqWUq10a/e0zj04Lqqv93nSjFK934Gf13rUuFLSvLWWGu8lVNzFQW1pFh7Zqs5S7LydIdv82cfQKLzv6F5ZM59dxpTOtG4nb8qj7JQrKhTwau9tmsEneBv6jpRj7u/DioUde6crwIzxqnaPQfYXqfkAcxnNx8eL0L+Qw7k0uccHU8fSQYP/S9IKNtSjyUeT5DXupkiNiEItohhIDjExvaZ8qv4vfwxwf0vwA='
```

**Comment by pitbulk** [comment]
Ok, I will investigate since I noticed that other [decoder](https://rnd.feide.no/simplesaml/module.php/saml2debug/debug.php) is able to process the value of the 
$_GET['SAMLRequest'].

**Comment by mstone42** [comment]
The i.p. is Gigya.  I believe the logout request is encoded, but I did not configure the set up (it was just handed to me to debug the fatal error), so I'm not sure what I need to look at to give you a definitive answer on that.

**Comment by mstone42** [comment]
Any headway on the fatal error?

**Comment by pitbulk** [comment]
It seems that is a server/php configuration/environment rather than a php-saml toollkit issue.
As you discovered, the value inside the SAMLRequest GET parameter is not able to be decoded in a good way (tried several decoders). The trick you made with the extractOriginalQueryParam makes sense in this case.
