### ISSUE TITLE
Custom cert folder option

### ISSUE THREAD

**Issue by hslavich** [onelogin/php-saml#121]
Is there any way to set a custom folder path where cert files should be loaded?
Currently I have a plugin and the only way to set cert data is using the `x509cert` parameter.

**Comment by pitbulk** [comment]
Yes, at the toolkit exists the 'path' concept:
Take a look on: [_loadPaths method](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L131)

You can define the [ONELOGIN_CUSTOMPATH](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L142) const for the config and certs.

P.S @hslavich nice to see you keep working on the Symfony2 SAML extension ;)

**Comment by pitbulk** [comment]
@hslavich have you solved the issue?

**Comment by hslavich** [comment]
Yes It's solved. Thank you @pitbulk!
