### ISSUE TITLE
Setting SignatureMethod and DigestMethod  to SHA256

### ISSUE THREAD

**Issue by krishnasathyanarayana** [onelogin/php-saml#122]
I have set 'signatureAlgorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'  for my SP. However, when create meta data XML. I still see the values as rsa-sha1 and not rsa-sha256 and sha256 respectively. My SP certificate has SHA256 as shown in the picture below. And the snippet of XML Meta data is below.   I'm setting the security options in same way as in advanced_settings.php. Anything else specifically needed to make sure of SHA256 instead of SHA1 for  signing SP requests?
```
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <ds:Reference URI="#pfxb50d66b5-24bf-dbcf-b1e0-39ae44b7e0cf"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
```

![sha256-problem](https://cloud.githubusercontent.com/assets/13102187/13949321/5a31796a-f04a-11e5-9586-78a98f956403.png)
.

**Comment by pitbulk** [comment]
There is a bug signing metadata.

The [signMetadata](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L125) method expects a $signAlgorithm parameter, but the toolkit is not providing it when [calling the method](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L731) at the Setting class.

We will fix it, meanwhile, can you try the patch yourself, just replace the Line 731 of lib/Saml2/Settings.php 
```
$metadata = OneLogin_Saml2_Metadata::signMetadata($metadata, $keyMetadata, $certMetadata);
```
by the following code:
```
$signatureAlgorithm = $this->_security['signatureAlgorithm'];
$metadata = OneLogin_Saml2_Metadata::signMetadata($metadata, $keyMetadata, $certMetadata, $signatureAlgorithm);
```

**Comment by krishnasathyanarayana** [comment]
Thanks. I tested it and it works. Please commit the fix to the next release,
krishna
