### ISSUE TITLE
Demo1 Caught in Redirection Loop

### ISSUE THREAD

**Issue by jlcross** [onelogin/php-saml#123]
When attempting to set up and test using the Demo1, the log in dies in a redirection loop.

**settings.php**
`
    $settingsInfo = array (
        'sp' => array (
            'entityId' => $spBaseUrl.'/demo1/metadata.php',
            'assertionConsumerService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?acs',
            ),
            'singleLogoutService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?sls',
            ),
            'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified',
        ),
        'idp' => array (
            'entityId' => $spBaseUrl.'/demo1/metadata.php',
            'singleSignOnService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?sso',
            ),
            'singleLogoutService' => array (
                'url' => $spBaseUrl.'/demo1/index.php?sls',
            ),
            'x509cert' => '',
        ),
    );
`

The session variable $_SESSION['samlUserdata'] is never assigned because the assertionConsumerService is never posted to.

This is an example of the URL that's created: /demo1/index.php?sso&SAMLRequest=tVNNj9owEL3zK1DuwQmkWWpBKgr9QGIhgrSHXqrBniyuEju1HaD%2Fvk7CdmlV5dRalizNzHtv%2FDQzM1AWFV3U9iT3%2BL1GYwdDd65lIQ1tk3Ov1pIqMMJQCSUaahk9LB43dDwKaKWVVUwV3h%2BwfhQYg9oKJTvYejX3dtt3m92H9fZr9ABhkE%2Fi1wBx8Gqah5yHDyyOpjyEKIrHx%2FA4PcaTsIN%2BRm0cz9xztN6gYzOmxrU0FqR18SCM%2FWDij6MsCGnk7uRLB125zwoJtoWfrK0MJeSbkiMtLLBTPWKqJFUB8izw4teuY3A2kTNKrjRREgv1JCSpTpXf%2FJhwLFVIhOR4HbngG2NUJ5TePHrrckI%2B9Vtz7IoM%2FZhlqZ%2FuDllHsni2bKmkqUvUB9RnwfDTfvNfugdmvKRVnjV52rqqk3%2BmVKIFDhYasRm5l3gRrejW%2BbNepaoQ7Ecbb857pUuw%2FTY2EcH9vC2ltTQVMpEL5N4vmkVRqMtSI1ice1bX6A3Jb%2BK3hUDerofz3eLVDpeqrEAL00wNXoHZm00vVt2XLws363vMk951YJQ1dS6cuueiNG9mBpnTzjS45pW2N5P%2BSt51TXraTgbP6ftdT34C&RelayState=%2Fdemo1%2Findex.php

**Comment by pitbulk** [comment]
After send an AuthNRequest the Identity Provider should send a SAMLResponse (HTTP-POST binding) and if something if wrong with the Response, it should ends with "Not authenticated"

**Comment by pitbulk** [comment]
@jlcross in what status is your deployment? have you verified that you had a "Not authenticated" so $_SESSION['samlUserdata'] is not assigned (not a bug).
