### ISSUE TITLE
The library not log on fileSystem

### ISSUE THREAD

**Issue by sharkman79** [onelogin/php-saml#125]
Library work properly but it is not possible add the system for logging for example log4php.
Do you have improvements this featurer or not ?

**Comment by pitbulk** [comment]
At the settings you have the [debug](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L11) parameter
If you enable the debug parameter, errors will be displayed to the users

We don't want to use a specific log engine on this toolkit, instead we let the developer to use whatever log library. At  auth.php you have the [getErrors](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L286) and the [getLastErrorReason](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L296). You can use those methods to extract possible errors and record them in your log system.

**Comment by SvenRtbg** [comment]
That's what the PSR logger interface is for. See https://github.com/php-fig/log
