### ISSUE TITLE
The $stay parameter on the OneLogin_Saml2_Auth::login function.

### ISSUE THREAD

**Issue by AndrewECooper** [onelogin/php-saml#129]
Hi,

In your OneLogin_Saml2_Auth::login() there is a parameter, $stay, that defaults to false. From looking at the code, it seems that the $stay parameter is there in case someone wants to use Ajax (like we do) and do the redirect to the IdP from Javascript.  That functionality seems to be broken though.

```
    public function login($returnTo = null, $parameters = array(), $forceAuthn = false, $isPassive = false, **$stay=false**)
    {
        assert('is_array($parameters)');

        $authnRequest = new OneLogin_Saml2_AuthnRequest($this->_settings, $forceAuthn, $isPassive);

        $this->_lastRequestID = $authnRequest->getId();

        $samlRequest = $authnRequest->getRequest();
        $parameters['SAMLRequest'] = $samlRequest;

        if (!empty($returnTo)) {
            $parameters['RelayState'] = $returnTo;
        } else {
            $parameters['RelayState'] = OneLogin_Saml2_Utils::getSelfRoutedURLNoQuery();
        }

        $security = $this->_settings->getSecurityData();
        if (isset($security['authnRequestsSigned']) && $security['authnRequestsSigned']) {
            $signature = $this->buildRequestSignature($samlRequest, $parameters['RelayState'], $security['signatureAlgorithm']);
            $parameters['SigAlg'] = $security['signatureAlgorithm'];
            $parameters['Signature'] = $signature;
        }
        return $this->redirectTo($this->getSSOurl(), $parameters, **$stay**);
    }
```

The login() function passes the $stay parameter on to OneLogin_Saml2_Auth::redirectTo() which is where the problem starts.  RedirectTo() doesn't have a $stay parameter.  It simply checks some values and then calls OneLogin_Saml2_Utils::redirect() without any $stay option.

```
    public function redirectTo($url = '', $parameters = array()) // No $stay param here.
    {
        assert('is_string($url)');
        assert('is_array($parameters)');

        if (empty($url) && isset($_REQUEST['RelayState'])) {
            $url = $_REQUEST['RelayState'];
        }

        return OneLogin_Saml2_Utils::redirect($url, $parameters);
    }
```

Strangely, the redirect() function declaration also has a $stay parameter. It does some stuff and then at the end either changes the headers (if $stay is false) or returns the redirect URL (if $stay is true).  This is why I think it is there for folks who want to use Ajax.

```
    public static function redirect($url, $parameters = array(), $stay = false)
    {
        assert('is_string($url)');
        assert('is_array($parameters)');

        BLAH
        BLAH
        BLAH

        if ($stay) {
            return $url;
        }

        header('Pragma: no-cache');
        header('Cache-Control: no-cache, must-revalidate');
        header('Location: ' . $url);
        exit();
    }
```

My question is, shouldn't the redirectTo() function's declaration look like:

`public function redirectTo($url = '', $parameters = array(), $stay = false)
`
and then the return line look like this:

`return OneLogin_Saml2_Utils::redirect($url, $parameters, $stay);`

**Comment by pitbulk** [comment]
It was already fixed , review the latest version.

**Comment by AndrewECooper** [comment]
Cool!  Thanks.  I thought I had the latest version but apparently not. Glad to know I wasn't crazy and that it was an issue. :)
