### ISSUE TITLE
Logout question

### ISSUE THREAD

**Issue by urban-1** [onelogin/php-saml#131]
Hi there, I was wondering if there is a reason for using `$_GET` in `Saml2::Auth::processSLO()`. It seems that my IdP sends back data using POST... I have replaced `$_GET` with `$_REQUEST` and everything seems working. Will this cause problems later on?

Cheers,

Andreas

**Comment by pitbulk** [comment]
The php-saml toolkit ony support HTTP-Redirect binding (GET) for LogoutRequest and LogoutResponse.
Check if your IdP supports  HTTP-Redirect binding for Logout, and if support it configure it propertly.

If only supports  HTTP-POST binding you will need to extend the toolkit and implement it yourself.
As you alredy noticed, when you changed the $_GET by $_REQUEST it worked... but if you want to support signatures for example, in HTTP-POST binding the signatures are embebed in the SAML Message and in the   HTTP-Redirect binding, the signature is another GET parameter.

**Comment by urban-1** [comment]
Hi @pitbulk 

That makes perfect sense now! Cause I am getting:

```
logout_not_success: urn:oasis:names:tc:SAML:2.0:status:Requester
```

I will see if the IdP supports HTTP-Redirect.

Thanks for your reply,

Andreas

**Comment by lexakozakov** [comment]
will php-saml support HTTP-POST binding for logout? 

Thanks
