### ISSUE TITLE
Sign LogoutRequest

### ISSUE THREAD

**Issue by micmania1** [onelogin/php-saml#133]
I've been trying to figure out a way to sign a LogoutRequest but it doesn't seem possible out of the box?

The only way I could do it was to alter `OneLogin_Saml2_LogoutRequest`'s constructor to include the following:

```
            // Sign the request
            $security = $this->_settings->getSecurityData();
            $logoutRequest = OneLogin_Saml2_Utils::addSign(
                $logoutRequest,
                $spData['privateKey'],
                $spData['x509cert'],
                $security['signatureAlgorithm']
            );
```

I tried subclassing, but it seems to be overridden somewhere before sending the actual request.

**Comment by pitbulk** [comment]
Only the HTTP-Redirect binding is officially supported by this toolkit for the LogoutRequest.
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L199
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L494

Is ok if you want to add HTTP-POST Signature but as you discovered there is no out of the box solution, you will need to extend the classes.

The addSign method is used to sign md;Metadata elements but should work for a LogoutRequest.
(The $logoutRequest that you provide to the method must be an XML or a Document)
