### ISSUE TITLE
PHP7 compatibility

### ISSUE THREAD

**Issue by olivM** [onelogin/php-saml#139]
seems like PHP7 is more strict on continue usage : 

FatalErrorException in Utils.php line 1006:
'continue' not in the 'loop' or 'switch' context

**Comment by pitbulk** [comment]
What php-saml version are you using?

**Comment by olivM** [comment]
oh sorry, i use 2.6.1 ( require by https://github.com/aacotroneo/laravel-saml2 )
i guess i should ask laravel-saml2 to change the deps in composer

**Comment by pitbulk** [comment]
yeah ;)
