### ISSUE TITLE
Adding <ds:Signature> data to AuthnRequest 

### ISSUE THREAD

**Issue by ddrdusan** [onelogin/php-saml#142]
I've tried a lot of different settings values & combinations, but neither resulted in signature being included in the samlp::AuthnRequest. The IdP I use requires this data. Is it possible? On https://developers.onelogin.com/saml/examples/authnrequest there is an example with embedded signature, but not sure how to reproduce it...

**Comment by pitbulk** [comment]
php-saml supports AuthnRequest on HTTP-Redirect binding (this mean the signature will be sent to the IdP as a GET parameter.

What you are asking for is the HTTP-POST binding where the signature is embedded inside the AuthnRequest XML. But this is not officially supported by this toolkit.

Are you sure that your Identity Provider only provide HTTP-POST  Single Sign On Service?
The HTTP-Redirect is the only required in Lite-IdPs. 
Also the [SAML2int Profile](http://saml2int.org/profile/current/#section81) specifies:
```
The <saml2p:AuthnRequest> message issued by a Service Provider MUST be communicated to the Identity Provider using the HTTP-REDIRECT binding.
```
