### ISSUE TITLE
support for SOAP Binding

### ISSUE THREAD

**Issue by dev-yohan** [onelogin/php-saml#143]
The library supports SOAP Binding?? I'm trying to maken and AuthnRequest with Packed Credentials over SOAP

regards

**Comment by pitbulk** [comment]
SOAP binding Is not covered.

You have to alternatives:
* Use another PHP SAML library like [simplesamlphp](https://github.com/simplesamlphp/saml2) that [supports](https://github.com/simplesamlphp/saml2/blob/d9df067df9fb2f48bbcf0d8e95c9c9a04116a860/src/SAML2/HTTPArtifact.php) it
* Extend that library for your own use, (we don't want to support/maintain SOAP Binding

**Comment by dev-yohan** [comment]
Ok, thanks for the info!

regards

**Comment by pitbulk** [comment]
We try to follow the [SAML2int Profile](http://saml2int.org/profile/current/#section81) and it specifies:
```
The <saml2p:AuthnRequest> message issued by a Service Provider MUST be communicated to
the Identity Provider using the HTTP-REDIRECT binding.
```
