### ISSUE TITLE
Add security config to disable destination check

### ISSUE THREAD

**Issue by dhensby** [onelogin/php-saml#149]
At the moment [the destination check](https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Response.php#L169-L181) for SAML responses is forced on and can't be disabled.

This can prove problematic because the utility function(s) used to determine the current URL can be wrong (for example, if we have a `X-Forwarded-Port` header that we don't want to use as the actual port).

As there's no way to provide current URL resolution hints it'd be helpful to either define the current environments domain/host/port/etc in some hard-coded way or to disable this destination check entirely.

I've mainly experienced this issue around ports being appended to the host unexpectedly and this has caused errors as there's a mis-match detected by the server that doesn't occur in the real/actual URLs.

**Comment by pitbulk** [comment]
I dislike the idea of disabling that check. 

The [getSelfURLhost](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L281) takes care of the $_SERVER["HTTP_X_FORWARDED_PORT"],
if you don't want to use it, you can just remove it from the $_SERVER parameter before the validation process (and maybe later restore it).

**Comment by dhensby** [comment]
I don't feel that messing with the super global state is something that should be recommended as a solution nor is it good practice.

I understand it's part of the standard but it and a whole raft of other checks can be disabled by turning off strict checking and then some other parts can be disabled specifically through the config. Is there a particular reason targeting this on it's own like some other checks is more problematic?

**Comment by pitbulk** [comment]
Other checks are disabled by turning off strict, and  this exists:
- To make the dev/test phase easier
- Due compatibility with the old php-saml version 1.0

but strict = false MUST not be used on a production server, so disable the destination check on the scope of strict = false does not solve your issue.

The toolkit follows the SAML standard and take care of the HTTP_X_FORWARDED_PORT parameter if exists, you are asking for a custom solution that fix your situation, so there are only 2 alternatives:
- Modify the $_SERVER["HTTP_X_FORWARDED_PORT"] before execute the check
- Modify locally the getSelfURLhost to not take care of that parameter.

**Comment by dhensby** [comment]
OK - cool, the strict setting makes sense to me then.

There are other checks that are individually configurable (ie: can be disabled) is that because they fall outside the SAML standard and are optional (such as encryption)?

I don't see that messing with super-globals or forking this repo are sustainable options; would you be unwilling to accept a destination check configuration option or perhaps a customisation to `getSelfURLhost` that would allow the setting of the "real" domain domain?

**Comment by pitbulk** [comment]
Disable the check if not an option.

Adding a settings on the 'security' section its ok, but pass this info to the 
getSelfURLhost method gonna be a complex task since this method is used several times.

**Comment by dhensby** [comment]
> Disable the check is not an option.

OK

> Adding a settings on the 'security' section related to that proxy issue is ok, but pass this info to the 
> getSelfURLhost method gonna be a complex task since this method is used several times and will complex the code to solve this specific scenario.

I wouldn't expect to add the settings to the security config - I was more thinking adding an API similar to:

```php
OneLogin_Saml2_Utils::setRequestProto();
OneLogin_Saml2_Utils::setRequestPort();
```

Which, if set, would be used to build the URL instead of looking at the super globals.

**Comment by pitbulk** [comment]
ok, that makes sense.

**Comment by pitbulk** [comment]
After read that:
https://github.com/simplesamlphp/simplesamlphp/issues/419

Maybe is better to disable the use of proto/port as default and only support them after
```
OneLogin_Saml2_Utils::setRequestProto();
OneLogin_Saml2_Utils::setRequestPort();
```

Are you able to contribute with a PR?

**Comment by dhensby** [comment]
Yes, that was my intention.

I'll look into making a PR, yes
