### ISSUE TITLE
Port checking on current host appears to do nothing

### ISSUE THREAD

**Issue by dhensby** [onelogin/php-saml#150]
See https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Utils.php#L326-L332

At first glance this appears to remove non-numeric port numbers from hosts, however, it doesn't actually do this and there's a test that even asserts that it doesn't remove non-numeric ports.

Is this block of code intended to perform any function, if so what? Should if be removed?

**Comment by pitbulk** [comment]
I wrote that too long ago, but I think I took that part from simpleSAMLphp:
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L57

**Comment by dhensby** [comment]
Considering it doesn't actually appear to do anything - should it be removed? It doesn't do what the SimpleSaml lib does (which is remove numeric port numbers).

**Comment by dhensby** [comment]
OK - I'm incorrect - the `array_pop` removes an item from the array and the subsequent `implode` joins an array with a single element (or if there were multiple port declarations, sticks them back together?!)

**Comment by dhensby** [comment]
Closing as the (perhaps) intended functionality of removing numeric ports appears to work
