### ISSUE TITLE
Destination check contains unnecessary duplicate check

### ISSUE THREAD

**Issue by dhensby** [onelogin/php-saml#151]
see: https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Response.php#L170-L181

If the check for whether the destination starts with current url fails, destination is checked with the `OneLogin_Saml2_Utils::getSelfRoutedURLNoQuery()` - however this is the initial value of  the first check (see https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Response.php#L133)

The repeated check does not appear to be needed.

**Comment by pitbulk** [comment]
The second one should be getSelfURLNoQuery
