### ISSUE TITLE
Custom port along with X-Forwared-Port would cause double port concatination

### ISSUE THREAD

**Issue by dhensby** [onelogin/php-saml#153]
I haven't verified this but it appears that a host that uses a custom port in conjunction with an `X-Forwarded-Port` header would lead to double port concatenation.

A port is appended to the host if set via headers (https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Utils.php#L281-L304) but `getSelfHost` appears to return a host with a port if it exists (https://github.com/onelogin/php-saml/blob/570a5d9cc42a1a205355b9212bd182fbe35404d9/lib/Saml2/Utils.php#L311-L334)

A decision needs to be made about which takes precedence and it should be consistently applied

**Comment by pitbulk** [comment]
getSelfURLhost must add the port, meanwhile getSelfHost is just the host without port.

**Comment by dhensby** [comment]
OK - I've tested this issue, it doesn't do a double concatenation *if* the port is numeric. see failing test on #155
