### ISSUE TITLE
No Support for Symmetric Encryption-Decryption

### ISSUE THREAD

**Issue by prashanthviva** [onelogin/php-saml#164]
Looks like currently the library only supports decrypting assertions encrypted by IDP using the SP public key.

Is there going to be support for decrypting when the encryption is through Symmetric Encryption. i.e. A shared key between IDP and SP ?
That's something similar to :
https://simplesamlphp.org/docs/1.5/simplesamlphp-reference-sp-remote#section_2_1

**Comment by pitbulk** [comment]
We are open to contributions, but this is not something that is currently on the roadmap.
