### ISSUE TITLE
Missing AuthState parameter

### ISSUE THREAD

**Issue by aguvillalba** [onelogin/php-saml#165]
When I try to connect to my IdP using:

```
$samlAuth = new OneLogin_Saml2_Auth();
$samlAuth->login();
```
I receive this exception from my IdP:
Missing AuthState parameter.

The URL generated by php-saml library does not contain this parameter, how can be solved?
Thank you in advance.

**Comment by pitbulk** [comment]
Is simpleSAMLphp your IdP? AuthState is not a parameter that php-saml sends, instead an internal parameter of simpleSAMLphp.

Something is wrong on your configuration. I googled and here people say that is related to
Suhosin PHP protection: https://groups.google.com/forum/#!topic/simplesamlphp/rJxsdrLFTYI
