### ISSUE TITLE
<samlp:Response> Destination Check against config, instead of current URL

### ISSUE THREAD

**Issue by JosephViolago** [onelogin/php-saml#166]
Re: #149, #152 (and probably even more)

So I've noticed that the [destination check](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L185-L199) evaluates the a server's current url and port. I reason to believe that this implementation may prove troublesome to a docker context (specifically, port mapping) and worse-so in a distributed context (ie. mesos; where IPs or and ports are less predictable.)

I'm curious as to why this check favors evaluating the current url over the configured `$settings['sp']['assertionConsumerService']['url']`.

**Comment by pitbulk** [comment]
Extracted from SAML standard:

```
the Destination XML attribute in the root SAML element of the protocol
message MUST contain the URL to which the sender has instructed the user agent to deliver the
message. The recipient MUST then verify that the value matches the location at which the message has been received.
```
