### ISSUE TITLE
ADFS IdP SAMLResponse fails in SP ACS with "Reference validation failed" for any version after v2.8.0

### ISSUE THREAD

**Issue by sitecode** [onelogin/php-saml#168]
Security Settings:
```
'security' => array (
'authnRequestsSigned' => true,
'wantAssertionsSigned' => true,
'signatureAlgorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
'lowercaseUrlencoding' => true,
),   
```
In order to pass validation successfully, the OneLogin_Saml2_Utils::validateSign needs a certain version of the decrypted document and also no xpath like it was in 2.8.0. Kinda like so in this commit: 5434c9d8484af5233a58a93ee758bf4539c6134e

**Comment by pitbulk** [comment]
Hi @sitecode, this issue is duplicated. Is the same issue reported at #167.
