### ISSUE TITLE
Problem with multiple attribute values

### ISSUE THREAD

**Issue by zivoradantonijevic** [onelogin/php-saml#170]
I am using this fantastic library for SSO login, and I am very satisfied.

There is only one problem, if I have setup server to return multiple attributes, I can not fetch them all, just one of them.

For example if in result there are 2 roles, editor and author, with it I only get one of them.

I have changed code a little to acomplish my goal:
 vendor/onelogin/php-saml/lib/Saml2/Response.php:498

            if(!isset($attributes[$attributeName])) {
                $attributes[$attributeName] = $attributeValues;
            }
            else{
                $attributes[$attributeName] = array_merge($attributes[$attributeName], $attributeValues);
            }

Did I miss some configuration setting or this feature is not planned ?

This is output with original code:  http://prnt.sc/cx24ba
and this is expected (what I got with changes): http://prnt.sc/cx23vf

**Comment by pitbulk** [comment]
The php-saml toolkit supports Multiple attribute values.
```
    <saml:AttributeStatement>
      <saml:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">test</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">users</saml:AttributeValue>
        <saml:AttributeValue xsi:type="xs:string">examplerole1</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
```
The method getAttributes on this will return:
```
array (
   'uid' => array("test"),
   'eduPersonAffiliation' => array("users", "examplerole1"),
);
``` 

We [don't allow Attributes with the Name duplicated](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L546), so the following entry is consider invalid:

```
    <saml:AttributeStatement>
      <saml:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">test</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">users</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
        <saml:AttributeValue xsi:type="xs:string">examplerole1</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
```

**Comment by zivoradantonijevic** [comment]
Thank you for your response.

I have changed application settings and now it works like a charm
