### ISSUE TITLE
SAML Response - Reference Validation Failed. 

### ISSUE THREAD

**Issue by nagargaurav** [onelogin/php-saml#171]
Hi,

We are trying to use onelogin php-saml, we used python-saml and it works fine but with the php-saml 2.9.1 we are having the following issue - "**Reference Validation Failed**"

Below are the details -

SAML Assertion:

`<default:assertion xmlns:default="urn:oasis:names:tc:SAML:2.0:assertion" id="_717a7a1f-7897-43d1-885f-07d1aa8e1354" issueinstant="2016-10-24T06:10:40.520Z" version="2.0"><default:issuer>http://cas-staging.lazada.com/adfs/services/trust</default:issuer><default:subject><default:nameid format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">philip.arguelles@aaa-dev.com</default:nameid><default:subjectconfirmation method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><default:subjectconfirmationdata inresponseto="ONELOGIN_cd26b68d3f29bc28b026b7e56a83db9185ec5757" notonorafter="2016-10-24T06:15:40.520Z" recipient="https://boosting.local:8080/acs/"></default:subjectconfirmationdata></default:subjectconfirmation></default:subject><default:conditions notbefore="2016-10-24T06:10:40.517Z" notonorafter="2016-10-24T07:10:40.517Z"><default:audiencerestriction><default:audience>http://boosting.local</default:audience></default:audiencerestriction></default:conditions><default:attributestatement><default:attribute name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"><default:attributevalue>philip.arguelles@aaa-dev.com</default:attributevalue></default:attribute></default:attributestatement><default:authnstatement authninstant="2016-10-24T05:50:09.881Z" sessionindex="_717a7a1f-7897-43d1-885f-07d1aa8e1354"><default:authncontext><default:authncontextclassref>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</default:authncontextclassref></default:authncontext></default:authnstatement></default:assertion>`

SAML Response:

`<samlp:Response ID="_73806dd5-e029-48c4-b2d1-d81baba1c61c" Version="2.0" IssueInstant="2016-10-24T06:10:40.520Z" Destination="https://boosting.local:8080/acs/" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="ONELOGIN_cd26b68d3f29bc28b026b7e56a83db9185ec5757" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"><Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://cas-staging.lazada.com/adfs/services/trust</Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></samlp:Status><EncryptedAssertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion"><xenc:EncryptedData Type="http://www.w3.org/2001/04/xmlenc#Element" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" /><KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#"><e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p"><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /></e:EncryptionMethod><KeyInfo><ds:X509Data xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:X509IssuerSerial><ds:X509IssuerName>E=aleksandr.sandrovskii@lazada.com, CN=boosting.local, OU=DS, O=Lazada, L=Singapore, S=Singapore, C=SG</ds:X509IssuerName><ds:X509SerialNumber>9644404756982182132</ds:X509SerialNumber></ds:X509IssuerSerial></ds:X509Data></KeyInfo><e:CipherData><e:CipherValue>yahFnLY3uZ1/29aP1wD1dkA8+wLqfCKEntotgg80Kz/6tbmi8M/6UBZXmIu6EpD6MkXAGUmmAkghZN9bCdKuS/kh4c6wz2dmwMR2HH1ZPdDXlUGrQgZwZA6p/ThUdMAMo8Ct271o6HosuFAjFmOVmh7qbRDBf3oZ99fgikDYBTix/0omZdJUJGF0ZWbuVb1aQC2B6XCoB61gi+/FkToOBXRpAE+P1NHFSTccThTIEtF2NUy0aJG7tqoxLKfgplHhSZ/1adRTEejUpaaaLvi+p1WABJivSrYil6Tro6Qwl2JvPBNyZkb2669xFhpe1tPqjLsWfnQ3+3avKOJ/l6W8wA==</e:CipherValue></e:CipherData></e:EncryptedKey></KeyInfo><xenc:CipherData><xenc:CipherValue>akdLOP1/tiRyB4wte/CNfO5hjUgVRSi47IP0IsSLgqWnccEqm+CyC5RMTl8jgkqutJqg33H0Sz2sBP8rDeYhK15bjB+M002d4j04ain+xqszaOB52SHl3k2tnFv56qIgu3EVJFIIoG3GEG/ubJYqGDpdvDxtx2dMicrKRx215oEKCz6rEghCbPe6B7N+xHwUds4343oGTi7vcUaJEvFPv6mKgyh/T5+hgeb/RPXvr+FZlRAdaGIFIQdI9ndeCb4uoqt7kz7Wrl41b5cWk8QtXuF8Py3HHgeHd1xGV38+bktmZoblUsI8sC5/5fBtYsokqc2eWuAHY/ehZrG72W4biCl8yPpcpoZJT4ynXO0ffPT4N8PQsekA5Bo7orOWa39/eWnc+O4OLjBECZp/L/kg81OyE7uydswKtx2LiEIxveHJDgPl8Z/fbKJIiS7ZD6SJixbAtwdfcuKfOlBmiOLbfb3heOQk8OxCJ9Y76HUf9EmLrD9JjAt+2KDxjduj/6kljsEN7qAErOk8XIfTUMB4sJU6VO/JKA+NSGu1NcbQGsCGi1rZAea1MSMom+LIGAFxhVzIlMvz4ayHarkY60I9tSX+CGe4UISG8d/83lzCqqBRFUXO6SjcvfEhaQadWiAUIcJsb+HI/h2pr8VNFJUQAroKuvRxTTk5H+IF4tG0+SLRCQgy/PkJA5vLLSgmBvXkKxs3ljeMP+91VXh5Ua/0x4bMWgzZjzvQp+WgU4eSjqQ0aflknH6P83uatShxFvyFEOF0sf10450KSQSA+5Bwo/LHmaqGT12VUhonMhZQkVmNvYeIdYznRrOXXPIZrzfSdp3itr2jdvdvLPO6Sjh2QPrha8eUp4tb5rop8zZ8UdxHt0PrAwZJo57P0CSI2+TtZaZtSEvmmFvGJGZBnn0Uagp8ACfy6fPCtez+ya6KKei/jIWMH/o82U9RbHIosdsxSWzofua4HskZNQPt30akWMvXwZV/qkS8iIY5Rf3/F8DiHWAUjLjwaG/XIYp7wZ1rgvnq846KD2bgNIcKKq7CMLiW+ywhUm+igHo7NO0il8fbQlQejBdCWCH5+3pft17HLUD5eZzQoShqQFsw47ojVyXpU2W4pS6LO2qr5H6Pv+AbU0YJu3nrGcwR6zqx4Ua2g0fl+8t2dFxacjHt5k7Nlk+VO9HEhjJV+PKXpCV04MhRlyu2umIvy9l8XzLYGMbuEtxldPQFUYhSyAL0gjy6OJVu5drMVwB92RlniKj27HqYqzC3TrzW3L8oW1dSLKANQf7XzJUVDseC2RcgVc07ycox2SCf1aptx5ubjtd7tJvS/VdeM4yWM+5qQSy0f/Ef6aig3kxNpDNzPifl46GmhcTZgSjyW9NKcytMm4Of9ERNiJnNqRP/khVFKhkmalVIae5k9OT1rbYfTimx95yDruYL0Ujos5vHUi/s4fbp/Lj6CxrVNgXaBYdTTz4NoZxl2hIyhPACcR0REamYaIx2lcYTObemxWKt0EA42rbm3OiSc9tUoLbpINf6+HgV3F3KUbFvmL4SDc7xNFXkhk4wujsg2bEOh8TyyWJylrj8CAJdrU/MOXIsqc6P7rR6njP73zqY66vRtC6DgvbXuNDV6Vqwm4YZ7q5dFKW4rzc1rmRFTxwse/O9DiCW6JVNhfwHgHMooYkpcPVP7ahVrZXb4cpiKjH5Blcl7UfSLg4zaaYzqFjpZeDA7TkXS4YdiAUILsxguaH6GIBig+vP/2jzdv2ygs4yjqe7DfvoR5zI/PjIXdXX2mh9xLwgCsvnifHHWVlsCgO4zHfvy79teuAdyy2m9/NfaS+e/xUefOc2YW9n4iSafk3U87Cxs61/ABXFBQr72TBDy82vbNVHAvDVgGblcJmYhaJmZGj2l8kX/0yDPFq285D9jBtPUYl47mio/YO78ioCcdcoor8bwDXHOFbzZmxQ9mQr2TiqHtLcO6A8aByO6Elo3c3VqfAR1NNDAGcfbkqxF0luNU2atz7chabKm/NG6UD4ibdRxJUIBpvjzgoIxgYaX4LY3nu4GcEgyzqRnRFRq0tKz8zBPQqVRtgY5PMXSbYUW9fJqHGKMTkl1N+iP/eYXfEH9SIf5PuEI/NrW+bBSa7bP/WrnP231qyGo9R4AXbHWvY7aujVOAPnM5UvoWXRNwRlJkd2/iu5B0r+FkWzdl4BV+IxwSNdt00SOOXv5IybwaaNtxAPjc8Ghx3fXUeFkban8LI/i3ZsTz04+c6+DsBQ+CMYti/RPHNDNgollIHNLcwZpnowmw3dQ/MrS+My6nXwT2wlt8d/xXvWiOK8LS261W9VmHqPxi04PLQobbm3DDccxEPOvM80+RNFcRD2ZH3tcksueI2SwIMed1AJgY2ShNSEEj66msm10c5WK9QqWn9q5nFvpkvNBx0eakqsJ8KWHADd/8Qmaj1SkY7PXH+ieR7K8+mACFly+gCprT4nDtyD8Vg1mw/dUjrBODNC5LzNdq70OSGMobxqCkkxg3yP+wWP5XbOZqLAunqQUKgqMnjdncYqLZDFoVvt+q2L6tN+9k8yG4ZfDslYRDNQjhr186QaKoH0lNkczV73FIKoKMb7leiLjBjTI26MpFgXt6NFiAhOy+/6k/i7HWg+LChqpxBneaoIPUo9uIc5W8Zf8lsJP83vSTCnSDG9wHwVIkNzf9YxnC7UNas6TFs7MZlmRbeM7n4lBTkwsYF4v+zxQLzPc70hFbBiz3LsKK6JHt4Qgg5CRH/dQV+qxyrtK+OPaAQqH01Rsz47CMdTD7ZKsFdKzN9S+jopc7zHTy3Iqjqh480/EtNNWojHJuHk59sb021OZ8Pd+C7Hboy41hk6Oh/V3ul103+4c7LV5FsTZjRe6zXsFh4SHss6iE0L4bOKvX7M3MrWIqZXCzUWuysgCvyeIg1af/Z6YC9OYg7ZUxNtelOBLRMO75w+Df10psq4qLYbUedcDBqg2DChESpsl/39aGChpDZtSuCqod20gZRMaiRPh90nhUCs6LLTldL3dKh8akP6LRSQtKiEOpM5h3S8Q7MkPFZGH7qikKha0WvuL8RScle/gKrdzw5z59IDm63xjtITLQvaSFIBS3EgizfRROHXXo4CIPqa6f1XVcD/+rxUYE6mWfekEjGKS3cG08q0jGXFWIuX5Svs/pgcvojolzo2DjFIcinqDeX3EaDPWaVmnKKuui/xNj9nSxHUgIvfKlXoaYT3H8NzBFhtdONkfLKi+FLzpAFt9G6ig/rpBbsTRoMJoLk6RLN/gUcOYiCfu6CAyvFa0Um+S/TDdl37MF1/QgTgzNI+Lh+g4VuUC37toPgwcCtVzUtP07jUIFDibzZJAgZ0mDQlqQAD4Zz/8wcOanE1POkgQWbj+wnU90OKDWPfCWaWpjT4kflM0W5Ho6haLiSbRJy9NfgXu+qJwN2LtRSn/nbwyYEi2qIIXle9P58tTRB5aeLAekXKHlEZpZiENXYseIBXvQzT7krSYgot+S80zSb63gM0GtC4nKCJHOyxyA8BRDtd16BDwWIZNsxiIsiwqgLUj+E2Z4+SXvtl/oGNx5OFgJdc+odX3DL7GMT9lw9pAdwcokfg84+5UpnIMbBgprDYdrQiAucaAqfgEUHrR3gWlbzq45r5kxS6vfMKFXA+fXIDsfSAG9fjZMYKA0PmL+XWHejCuIP/nSZgermqWYEJOIe5TeL/fez1W52QVTcTxNkLmK6MlRZU8ronVPOa7365vLJsIEuRW6uZkr92lfpUgMuc9ryMjySnlb14B7lRTqaJXvUCnkNgpDoeBCLlBUQxnB4z7Z78pFrqTfuOl9AMlnIl6X0Y+ixlRsafT7ecPeCcM8LGtoZNHz3OAEaHcyE9nqCuSqceqWd7jd/Xj7pGtZEX6w0Iw8Hw0sXDdQ9zu2uYrJ0AYhRO0OYBi1/K7VP6R45cleG28YnaI2HtBlRdom90Lc6/zH6NXk8tCYRvV+FrVC1Z0csfSTb+9poUxwwPB4EhxN4Ti/zKqgVEcPbs1vbbVo1aYyzTPbLqgxP8rUfDpJuSDAll+mZIWSqJikwSL4TO5AicsVzKWRoKeiKPJ8ZoNDx5eh4KZ+/7R1dUbyJLgEkyRuq2uQ7++Btt5+7gnOzwrIz524Z0bS0fX0zE1UyfxlJyW9/83E1rchRASvvUTcBHf7qmxMI6kY86lKE/b3djTEMQe4/9RgiFZCVy0y4p2+RDV2K9YPj0r/LB7Ki8TZr8ST7uUoDX/nQLI3Ckk331Mo0RXFEkolmABzT3FlOsVBrITRLwNSSA+vY7IuzKpa5sQyb6rINFljcXpZXxRADm/HERzA9lqsxlnQQcxB2WLChko+5dc14/DfVjkZwg3ygwFqHVIxoWmvTocdswDV6/Gbwo3Tf4y1B2oohBaufHEnYrpqe2daOpxdmLSWOnpmYsan3TmNiU4LHZNIv17Kug8kSBfwj/HWUTt4mXylJXkWQ1TmcPGwuTGmEM+EWBc5Zy+4jaOcwb1vZVJ9Luawabqp3y5BpGWNr5nVrSvfznHhhRTHQSYFnKZH1dEENpU9mKns3L0avLv9GAlHjq0duDoxsk3uDTN6S5eEueHtZvNIQa8lTv8VDf+Q9feEhDu8FtdHIsAJPHgzjdJ/r8ovYpsVSU98wKuR0=</xenc:CipherValue></xenc:CipherData></xenc:EncryptedData></EncryptedAssertion></samlp:Response>`

Please let me know if you need any other details.

Thanks in advance,
Gaurav Nagar

**Comment by pitbulk** [comment]
Hi @nagargaurav 

I'm investigating that issue, already reported at [167](https://github.com/onelogin/php-saml/issues/167)

**Comment by nagargaurav** [comment]
It worked, when we downgraded to 2.8.0
