### ISSUE TITLE
Creating a Certificate Chain

### ISSUE THREAD

**Issue by marcvthooft** [onelogin/php-saml#179]
Hi I am trying to setup a full certificate chain for our Service Provider.

Our client (IdP) needs the full chain to establish thrust. I see in their metadata multiple certificates, is it possible for me to do the same?

Or is there an other way like only putting the public certificates in the metadata and sending the CA certificates by mail? (to be honest I am new to the subject and don't really know what I'm doing :)

thanx

**Comment by pitbulk** [comment]
Service Provider only publish 1 certificate , not the CA, the CA is used to validate the certificate itself, but
no many implementations do that, only check that the signature match the certificate, no if the certificate is valid itself.

**Comment by marcvthooft** [comment]
Thankyou
