### ISSUE TITLE
Unknown key size for type "http://www.w3.org/2000/09/xmldsig#rsa-sha1".

### ISSUE THREAD

**Issue by Nomafin** [onelogin/php-saml#180]
I'm trying to send a signed AuthnRequest with self-signed certificates, but whatever I try, I always get the abovementioned error. Even though I change signatureAlgorithm to be rsa-sha256, the error says rsa-sha1.

**Comment by pitbulk** [comment]
Can you try to use that online tool and see if you are able to sign the AuthNRequest?
https://www.samltool.com/sign_authn.php

**Comment by pitbulk** [comment]
It seems that the error happens on the [generateSessionKey](https://github.com/onelogin/php-saml/blob/88a489013c3dc0a833d1bdca7ad18e3e6ad6914e/extlib/xmlseclibs/xmlseclibs.php#L204), used on the [generateNameId](https://github.com/onelogin/php-saml/blob/8fb44f7b11a15227d4221347a63cf5de7d2e4620/lib/Saml2/Utils.php#L950) method.

But this method is executed on the LogoutRequest not in the AuthNRequest... so I'm lost.
