### ISSUE TITLE
Invalid array settings: sp_acs_url_invalid

### ISSUE THREAD

**Issue by EmilMoe** [onelogin/php-saml#182]
I am using laravel-saml2 which hasn't been updated, but suddenly, I think after an update on this, I'm getting this error:

~~~~
[OneLogin_Saml2_Error]
  Invalid array settings: sp_acs_url_invalid
~~~~

Can you identify if it can be related according to recent updates?

**Comment by juanpscotto** [comment]
Any way to solved this? I have changed to absolute path but the error persists.

**Comment by pitbulk** [comment]
can you provide more info about the error and the piece of code that fails on lavarel-saml2?
