### ISSUE TITLE
You do not have access to this application

### ISSUE THREAD

**Issue by AMilkov** [onelogin/php-saml#19]
Hi,

If I use the demo as it is without any changes, what I get from OneLogin site as response is:

**You do not have access to this application. 
contact your administrator.**

Is it normal the behavior to be like that?
I was expecting to forward me to some login form, so I can authenticate there.

**Comment by nabdef** [comment]
Hi pitbulk,

i have some problem to test my local asp.net application (SP) and onelogin (IDP)

the uri of my application(SP) is : http://localhost:10983/Default.aspx.
the uri of the onelogin(IDP) is : https://app.onelogin.com/saml/signon/20219

the redirect is done perfectly through mylocal application and i arrive to get the onelogin interface to (the login is filled by default).
when i put my password, i get the error message:
"You do not have access to this application. 
contact your administrator."

can please help me to resolve this problem. there is some thing missing in the IDP configuration?
Thanks a lot!

**Comment by pitbulk** [comment]
Is a configuration problem at the OneLogin connector, not a toolkit issue. Read what I already replied.

At the OneLogin connector see that the user you want to authenticate is listed (means has access to the app)

**Comment by nabdef** [comment]
You are right, at the OneLogin connector i see that the user i want to authenticate isn't listed.
I spend a lot of time  trying to list the user at the OneLogin connector but was unsuccessful.
can you please guide me.

thank you so much.

**Comment by pitbulk** [comment]
@nabdef  Review this documentation:
https://onelogin.zendesk.com/hc/en-us/articles/201553114-Getting-Started-with-OneLogin

**Comment by nabdef** [comment]
@pitbulk  thanks à lot..you made my day!!
