### ISSUE TITLE
Can't "deflate" authnRequest

### ISSUE THREAD

**Issue by madebyrogal** [onelogin/php-saml#190]
v2.10.3
In OneLogin_Saml2_Auth->login() line 390:
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L390
`$samlRequest = $authnRequest->getRequest();`
There is no way to "deflate" authnRequest because $deflate always will be null

**Comment by pitbulk** [comment]
when $deflate is null, then [this line](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/AuthnRequest.php#L147) is executed:
```
$deflate = $this->_settings->shouldCompressRequests();
```
So the $deflate value depends on the [settings](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L10), that you can see that by default are true, even if [they are not defined on settings](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L328).

**Comment by madebyrogal** [comment]
Thanks you have a right ;)
