### ISSUE TITLE
Setting DigestMethod to SHA256

### ISSUE THREAD

**Issue by sproogen** [onelogin/php-saml#191]
Following on from Issue #122 it looks like it is still not possible to set the DigestMethod.

In the signMetadata function in the Metadata class a $digestAlgorithm parameter can be passed in but it is always set to SHA1 and is never overridden.

I think this is something that should be configurable in the settings, but I am not 100% sure if it is needed so I wanted to ask.
And also if the digestAlgorithm is used anywhere else in the code that would also need to be updated. 

If it is needed I am happy to create a pull request for this.

James

**Comment by pitbulk** [comment]
You are right, as digestMethod is always used [xmlsec.TransformSha1](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L869).

We should extend [add_sign](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L800) to support a digest_method. And also extend [sign_metadata](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/metadata.py#L205).

As you can see, this is only used to sign metadata, at the method to [sign the authnrequest](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L412) I don't see that we set a DigestMethod.

**Comment by sproogen** [comment]
Hi @pitbulk 

I was looking at the php-saml library, where the [addSign](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L1199) and [signMetadata](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L181) functions do already have support for the digestAlgoritm.

So we would just need to add a digestAlgorithm to the advanced settings and pass it through to the sign metadata [here](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L838)

**Comment by pitbulk** [comment]
Yes on php-saml I added the digestAlgorithm to [signMetadata](added https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L181) and [addSign](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L1199) but as you saw I didn't add a new setting parameter to the settings file and I'm not using it on the [getSPMetadata](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L838) method, the reason was that I don't wanted to add another parameter and turn the settings even more complex...

**Comment by sproogen** [comment]
But I do not see a need of adding it to the signMetada and addSign if it is not going to be used in the getSPMetadata.

If we want the digestMethod algoritm to be SHA256 and we are using the getSPMetadata function then there is currently no way of doing this unless it is added to the settings.

Unless there is another way?

**Comment by pitbulk** [comment]
yeah, that why I gonna say that its ok to add that method to the settings, if not instead the getSPMetadata you will need to extend the Metadata and that method to support the digestAlgorithm

**Comment by pitbulk** [comment]
Also please add a default value as we do for the [digestAlgorithm value](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L387)

**Comment by sproogen** [comment]
Ahh yes, I knew I had seen that somewhere but couldn't find it when adding the digestAlgorithm.

Thanks

**Comment by pitbulk** [comment]
Currently the [test for the signMetadata](https://github.com/onelogin/php-saml/blob/master/tests/src/OneLogin/Saml2/MetadataTest.php#L118) does not check if the proper signatureAlgorithm and digestAlgorithm where used. If you have spare time to create such test .. :)

**Comment by sproogen** [comment]
I have added the default digestAlgorithm now...

Not right this minute, but I shall try add the test later today :)

**Comment by pitbulk** [comment]
Thanks, appreciate!
