### ISSUE TITLE
Getting "invalid_response" $auth->getErrors()

### ISSUE THREAD

**Issue by selvesan** [onelogin/php-saml#195]
Hi, i am using google g-suite as my idp. i thing all my settings are currect and i am able to send request to the idp and also receive "RelayState" and "SAMLResponse(with base 64 incoded string)" 
**However,**

> $auth->processResponse($requestID);
> $errors = $auth->getErrors();
> if (!empty($errors)) {
>     print_r('<p>' . implode(', ', $errors) . '</p>');
>     exit();
> }

is giving me "invalid_response" error

**Comment by pitbulk** [comment]
Use
```
print $auth->getLastErrorReason();
```
To get the reason of the invalid_response, or enable the 'debug' parameter of the settings.

**Comment by selvesan** [comment]
Signature validation failed. SAML Response rejected

**Comment by pitbulk** [comment]
Record the SAMLResponse with [SAMLTracer](https://addons.mozilla.org/es/firefox/addon/saml-tracer/)
and later verify that the X509Certificate element of the signature matches the ['x509cert'](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L93) value of your settings.

**Comment by selvesan** [comment]
currently i have  '[x509cert](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L93)' this empty. should i provide the idp .pem key there or the .pem file location

**Comment by selvesan** [comment]
thankyou very much this is solved now

**Comment by KaperIT** [comment]
for me add (__Include in SAML assertion__)
![изображение](https://github.com/SAML-Toolkits/php-saml/assets/88566801/45ea35ab-6790-4964-a7b3-3f5302476f45)
