### ISSUE TITLE
support authnrequest signature inside the request

### ISSUE THREAD

**Issue by tflori** [onelogin/php-saml#197]
The SAML-Provider I'm using expects the signature inside the AuthnRequest. I didn't found a way to do this:

```xml
<?xml version="1.0"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="pfxa3cf9f80-eeef-18ac-8373-c4d7fea41b91" Version="2.0" IssueInstant="2014-07-11T17:56:28Z" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" AssertionConsumerServiceURL="https://www.whitehatsec.com/saml">
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">Calypso.admin.example.com</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
            <ds:Reference URI="#pfxa3cf9f80-eeef-18ac-8373-c4d7fea41b91">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                <ds:DigestValue>Lx8/i0s6cMpi8AKCmsOW7k1Mgio=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>nCxO8LN2ofxBMZGoLyhpEQyKSYN6rF/I59eQYfn3uBXEFLsJDrgyyUO9ZX2/IVw9z28IywR2/Yq84Het/gXPDcycn7DfB8YNB4yUKuNkABH/7tTB93lrQwHohqrA/Sj5vtTU4o6PiUpFgelX2qb3rg++sXTORsx0s9BUl+Tcgro=</ds:SignatureValue>
    </ds:Signature>
</samlp:AuthnRequest>
```

**Comment by pitbulk** [comment]
Sending AuthNRequest using HTTP-POST is not officially supported by this toolkit, but you can extend the toolkit and support it in your project.

The code of the supported SP-initiated SSO flow looks like:
```
require_once '/_toolkit_loader.php';
require_once 'settings.php';
$auth = new OneLogin_Saml2_Auth($settingsInfo);
if (isset($redirectTo)) {
    $auth->login($redirectTo);
} else {
    $auth->login();
}
```

The HTTP-POST binding:
```
require_once '/_toolkit_loader.php';
require_once 'settings.php';

$settings = new OneLogin_Saml2_Settings($settingsInfo, true);
$security = $settings->getSecurityData();

$authNRequest = new OneLogin_Saml2_AuthnRequest($settings);
$authNRequestXML = $authNRequest->getXML();

$key = $settings->getSPkey();
$cert = $settings->getSPcert();

$signatureAlgorithm = $security['signatureAlgorithm'];
$digestAlgorithm = XMLSecurityDSig::SHA1;
$signedAuthNRequestXML = OneLogin_Saml2_Utils::addSign($authNRequestXML, $key, $cert, $signatureAlgorithm, $digestAlgorithm);
$encodedAuthNRequest = base64_encode($signedAuthNRequestXML);

$params = array(
    'SAMLRequest' => $encodedAuthNRequest
);

if (isset($redirectTo)) {
    $params['RelayState'] = $redirectTo;
}

$idpData = $settings->getIdPData();
$ssoURL = $idpData['singleSignOnService']['url'];

executePostCurl($ssoURL, $params);


public function executePostCurl($url, $params)
{
    $ch = curl_init();
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
    curl_setopt($ch,CURLOPT_URL, $url);
    curl_setopt($ch,CURLOPT_POST,true);
    curl_setopt($ch,CURLOPT_POSTFIELDS, http_build_query($params));
    $result = curl_exec($ch);
}
```

**Comment by tflori** [comment]
I understand your point. But my provider send me exactly this example. And they expect it as query parameter in a redirect. Also they want `ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"` and I found that it is hard coded in `OneLogin_Saml2_AuthnRequest::__construct()`.

I'm new to SAML but for me it looks like a typical problem of XML standards. An instance (*the official*) says you should do it this way and every developer interprets it somehow different.

**Comment by pitbulk** [comment]
The ProtocolBinding of the AuthNRequest shouldn't be hardcoded, fixed at:
https://github.com/onelogin/php-saml/commit/7f10041c826545d45226154670a9fd38517ce925

**Comment by sureshp007** [comment]
Hi All,
We have used the above HTTP-POST binding code but while running the curl result http code is 0. So we have added the additional params CURLOPT_SSL_VERIFYPEER as 0. It was showing result. So kindly let us know, if we set the CURLOPT_SSL_VERIFYPEER as 0 whether we facing an any securitty issue in future or not.
If the CURLOPT_SSL_VERIFYPEER as 1, we need to add additional params CURLOPT_CAINFO,  here what we need to add the .pem file. Where it will be located for that .pem file. Could you please check and do the needful.Thanks.

**Comment by pitbulk** [comment]
That happens with you are connecting to an IdP that is hosted under HTTPs but uses a wrong cert, a self-signed cert or a cert that can be validated because your system doesn't have its related CA.

I don't think you gonna experience any security issue disabling the CURLOPT_SSL_VERIFYPEER, SAML has its own mechanism to ensure

**Comment by sureshp007** [comment]
Hi Pitbulk,

Thanks for the valuable feedback.
