### ISSUE TITLE
Create OneLogin_Saml2_Auth::getLoginUrl() that gets the url OneLogin_Saml2_Auth::login() redirects to.

### ISSUE THREAD

**Issue by zippy1981** [onelogin/php-saml#198]
I'd like to proxy the service that runs the OneLogin api.

**Comment by pitbulk** [comment]
You can use the [login method](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L381) with stay=true and you will get the URL that you asking for.
