### ISSUE TITLE
unclear implementation details with validUntil configuration

### ISSUE THREAD

**Issue by aeilers** [onelogin/php-saml#200]
I have a client that would like to configure the `validUntil` setting in the `EntityDescriptor` of the generated SP metadata.xml. I have been evaluating the use of your library for the project but found some unclear implementation details regarding the setting of `validUntil` and `cacheDuration`. I have reviewed your implementation and found that the `builder` method in the Metadata class does allow you to pass a `$validUntil` and `$cacheDuration` value and default to `null` if they aren't provided.
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L26

However, in the Settings class, you call the `builder` method and explicitly pass `null` for both values so the defaults are used.
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L781

Further, I have reviewed the SAML 2.0 specification document and it says that the `validUntil` and `cacheDuration` values are optional but they recommend that they are set on the `EntityDescriptor` element as you have done.
https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf (lines 316, 319, and 333)

Could you provide some insight on your decision to only use the constant values of `2 days` and `1 week` for the `validUntil` and `cacheDuration` values respectively?
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L10-L11

Also, would you be open to a pull request integrating these configuration options into your `advanced_settings.php`? I have been working with the code and manually testing the integration and it works well with only minimal changes to your current implementation. Most of the changes are in `php-saml/lib/Saml2/Settings.php` and adhere to your implementation and documentation details.

Please advise.

**Comment by pitbulk** [comment]
Hi @aeilers,

I don't want to add 2 new parameters to the settings (there are already a lot).
As you can see, the Metadata builder accepts validUntil and cacheDuration so you can use directly that builder in your code instead the call to the Settings::getSPMetadata method.

P.S If you really want to use the getSPMetadata method, I accept a PR where that method will accept the  validUntil and cacheDuration (by default set to null) and pass then to the builder. Please provide also unit tests.

**Comment by vioan** [comment]
Is there available any value to set `validUntil` and `cacheDuration` for an unlimited period of time, in advanced_settings.json?

**Comment by pitbulk** [comment]
no, that is controlled directly on the [Metadata builder](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L26)... and you could consider unlimited as a date of year 4000.
