### ISSUE TITLE
ate_default_timezone_get(): It is not safe to rely on the system's timezone settings

### ISSUE THREAD

**Issue by togakangaroo** [onelogin/php-saml#209]
Enabled the default Apache/php on OSX.

Following [these instructions](https://developers.onelogin.com/saml/php) I got everything configured but when I click "Login" I get

`
Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. inphp-saml/lib/Saml2/Utils.php on line 657
`

**Comment by pitbulk** [comment]
Edit your php.ini and set a value for [date.timezone](http://us2.php.net/manual/en/timezones.php)

http://us2.php.net/manual/en/function.date-default-timezone-set.php

**Comment by togakangaroo** [comment]
Right, I understand that @pitbulk my point is, that either the example should be updated to `'UTC'` or that the docs should mention this explicitly. Either would work.

**Comment by pitbulk** [comment]
Hi @togakangaroo 

but this issue happens in any php app that use time methods, not only related with that toolkit, so a php coder should be aware of that fact already.

**Comment by togakangaroo** [comment]
Sure, but I haven't been a php developer in 12 years, you referred me here from the dotnet repo. I'm not saying that yall had some major fuckup or anything, I'm just saying that adding a note as to this in your php documentation might help people who are otherwise confused get it running.

**Comment by pitbulk** [comment]
That is open source, if you think you can improve the documentation, you can contribute with a PR and I will be happy to review and merge it.
