### ISSUE TITLE
Logging out doesn't clear the session

### ISSUE THREAD

**Issue by togakangaroo** [onelogin/php-saml#210]
```
else if (isset($_GET['slo'])) {
    $returnTo = null;
    $paramters = array();
    $nameId = null;
    $sessionIndex = null;
    $nameIdFormat = null;

    if (isset($_SESSION['samlNameId'])) {
        $nameId = $_SESSION['samlNameId'];
    }
    if (isset($_SESSION['samlSessionIndex'])) {
        $sessionIndex = $_SESSION['samlSessionIndex'];
    }
    if (isset($_SESSION['samlNameIdFormat'])) {
        $nameIdFormat = $_SESSION['samlNameIdFormat'];
    }

    $auth->logout($returnTo, $paramters, $nameId, $sessionIndex, false, $nameIdFormat);
```

Note what happens when someone logs out - the session never gets cleared!

So when you head back to `index.php` you get the same page with the same user info - confusing! Worse, there is no link to log in, just one to log out!

**Comment by pitbulk** [comment]
On SAML, at a SP-initiaited Single Logout, the session is not cleared before sending the LogoutRequest, instead, when receiving a LogoutResponse from the IdP.
So the [sls](https://github.com/onelogin/php-saml/blob/master/demo1/index.php#L84) code should[ validate the LogoutResponse](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L219) and [close the session](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L227)
