### ISSUE TITLE
Error: app_not_configured_for_user when user has another session on Google

### ISSUE THREAD

**Issue by ghost** [onelogin/php-saml#213]
I'm using SAML to validate into Google Apps.  Everything works fine if user try to login only to our GSuite, but if their have another session instance (like their personal Gmail account) it reloads to 403 page error.  How can we force to AddSession from the login request?

**Comment by pitbulk** [comment]
The error that you experienced is from Gsuite, not from php-saml.
It should be an issue with Gsuite and how it handle multiple session.
