### ISSUE TITLE
Saml Extensions not supported

### ISSUE THREAD

**Issue by florinm8** [onelogin/php-saml#215]
Hi,

Is there an intent to implement saml extensions support in authnRequest?

Thanks.

**Comment by pitbulk** [comment]
That SAML toolkit does not intent to implement all the SAML spec, instead offer a working environment that will work for the majority of the users, keeping the toolkit easy to use and configure.

If you want to add saml extensions support you are free to extend the current classes and add the pieces of code that you need for your project.
