### ISSUE TITLE
Signature validation failed. SAML Response rejected

### ISSUE THREAD

**Issue by pkendre** [onelogin/php-saml#216]
Hi

I have setup simplesamlphp as an IDP.
I am using php-saml as SP

I have hosted both the application on same EC2 instance.

Once I hot the URL of my laravel page, it redirects me to the SSO login page. I enter the username/pass as student/studentpass and the IDP redirects me back to the laravel website but it takes me to the home page (/ route). I futher debug in "vendor/onelogin/php-saml/lib/Saml2/Auth.php" page and print the response.

here is the response I am getting

"View source of the response output - this is more readable since"

OneLogin_Saml2_Response` Object
(
    [_settings:protected] => OneLogin_Saml2_Settings Object
        (
            [_paths:OneLogin_Saml2_Settings:private] => Array
                (
                    [base] => /var/www/html/monitering_v2/vendor/onelogin/php-saml/
                    [config] => /var/www/html/monitering_v2/vendor/onelogin/php-saml/
                    [cert] => /var/www/html/monitering_v2/vendor/onelogin/php-saml/certs/
                    [lib] => /var/www/html/monitering_v2/vendor/onelogin/php-saml/lib/
                    [extlib] => /var/www/html/monitering_v2/vendor/onelogin/php-saml/extlib/
                )

            [_strict:OneLogin_Saml2_Settings:private] => 1
            [_debug:OneLogin_Saml2_Settings:private] => 
            [_sp:OneLogin_Saml2_Settings:private] => Array
                (
                    [NameIDFormat] => urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
                    [x509cert] => 
                    [privateKey] => 
                    [entityId] => https://sso.pi108.net:9005/saml2/metadata
                    [assertionConsumerService] => Array
                        (
                            [url] => https://sso.pi108.net:9005/saml2/acs
                            [binding] => urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
                        )

                    [singleLogoutService] => Array
                        (
                            [url] => https://sso.pi108.net:9005/saml2/sls
                            [binding] => urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
                        )

                )

            [_idp:OneLogin_Saml2_Settings:private] => Array
                (
                    [entityId] => https://sso.pi108.net/simplesamlphp/www/saml2/idp/metadata.php
                    [singleSignOnService] => Array
                        (
                            [url] => https://sso.pi108.net/simplesamlphp/www/saml2/idp/SSOService.php
                        )

                    [singleLogoutService] => Array
                        (
                            [url] => https://sso.pi108.net/simplesamlphp/www/saml2/idp/SingleLogoutService.php
                        )

                    [x509cert] => -----BEGIN CERTIFICATE-----
MIID/TCCAuWgAwIBAgIJAI4R3WyjjmB1MA0GCSqGSIb3DQEBCwUAMIGUMQswCQYD
VQQGEwJBUjEVMBMGA1UECAwMQnVlbm9zIEFpcmVzMRUwEwYDVQQHDAxCdWVub3Mg
QWlyZXMxDDAKBgNVBAoMA1NJVTERMA8GA1UECwwIU2lzdGVtYXMxFDASBgNVBAMM
C09yZy5TaXUuQ29tMSAwHgYJKoZIhvcNAQkBFhFhZG1pbmlAc2l1LmVkdS5hcjAe
Fw0xNDEyMDExNDM2MjVaFw0yNDExMzAxNDM2MjVaMIGUMQswCQYDVQQGEwJBUjEV
MBMGA1UECAwMQnVlbm9zIEFpcmVzMRUwEwYDVQQHDAxCdWVub3MgQWlyZXMxDDAK
BgNVBAoMA1NJVTERMA8GA1UECwwIU2lzdGVtYXMxFDASBgNVBAMMC09yZy5TaXUu
Q29tMSAwHgYJKoZIhvcNAQkBFhFhZG1pbmlAc2l1LmVkdS5hcjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMbzW/EpEv+qqZzfT1Buwjg9nnNNVrxkCfuR
9fQiQw2tSouS5X37W5h7RmchRt54wsm046PDKtbSz1NpZT2GkmHN37yALW2lY7My
VUC7itv9vDAUsFr0EfKIdCKgxCKjrzkZ5ImbNvjxf7eA77PPGJnQ/UwXY7W+cvLk
irp0K5uWpDk+nac5W0JXOCFR1BpPUJRbz2jFIEHyChRt7nsJZH6ejzNqK9lABEC7
6htNy1Ll/D3tUoPaqo8VlKW3N3MZE0DB9O7g65DmZIIlFqkaMH3ALd8adodJtOvq
fDU/A6SxuwMfwDYPjoucykGDu1etRZ7dF2gd+W+1Pn7yizPT1q8CAwEAAaNQME4w
HQYDVR0OBBYEFPsn8tUHN8XXf23ig5Qro3beP8BuMB8GA1UdIwQYMBaAFPsn8tUH
N8XXf23ig5Qro3beP8BuMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AGu60odWFiK+DkQekozGnlpNBQz5lQ/bwmOWdktnQj6HYXu43e7sh9oZWArLYHEO
yMUekKQAxOK51vbTHzzw66BZU91/nqvaOBfkJyZKGfluHbD0/hfOl/D5kONqI9ky
Tu4wkLQcYGyuIi75CJs15uA03FSuULQdY/Liv+czS/XYDyvtSLnu43VuAQWN321P
QNhuGueIaLJANb2C5qq5ilTBUw6PxY9Z+vtMjAjTJGKEkE/tQs7CvzLPKXX3KTD9
lIILmX5yUC3dLgjVKi1KGDqNApYGOMtjr5eoxPQrqDBmyx3flcy0dQTdLXud3UjW
VW3N0PYgJtw5yBsS74QTGD4=
-----END CERTIFICATE-----

                    [certFingerprint] => 
                )

            [_security:OneLogin_Saml2_Settings:private] => Array
                (
                    [nameIdEncrypted] => 
                    [authnRequestsSigned] => 
                    [logoutRequestSigned] => 
                    [logoutResponseSigned] => 
                    [signMetadata] => 
                    [wantMessagesSigned] => 
                    [wantAssertionsSigned] => 
                    [wantNameIdEncrypted] => 
                    [requestedAuthnContext] => 1
                    [wantAssertionsEncrypted] => 
                    [wantXMLValidation] => 1
                )

            [_contacts:OneLogin_Saml2_Settings:private] => Array
                (
                    [technical] => Array
                        (
                            [givenName] => name
                            [emailAddress] => no@reply.com
                        )

                    [support] => Array
                        (
                            [givenName] => Support
                            [emailAddress] => no@reply.com
                        )

                )

            [_organization:OneLogin_Saml2_Settings:private] => Array
                (
                    [en-US] => Array
                        (
                            [name] => Name
                            [displayname] => Display Name
                            [url] => http://url
                        )

                )

            [_errors:OneLogin_Saml2_Settings:private] => Array
                (
                )

        )

    [response] => <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_216dfbb49f70f0605ae17db231ce17c61aa7be3dcd" Version="2.0" IssueInstant="2017-05-15T10:59:54Z" Destination="https://sso.pi108.net:9005/saml2/acs" InResponseTo="ONELOGIN_5f898daf78bbccb828234e11f3b3938febbcac3a"><saml:Issuer>https://sso.pi108.net/simplesamlphp/www/saml2/idp/metadata.php</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <ds:Reference URI="#_216dfbb49f70f0605ae17db231ce17c61aa7be3dcd"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>/YboUuY+jhnETP9hOUewroSmZ58=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>Z4Z35ta7jS4HrYIXB3j0VgY48nk0AIW+Ycdw6IziZKhEXX3sgzl01b9FnhurbMAOEwir5l5SPzfi0m3UUt1jk4rJNlqL6ypi03u0BfM2HbZwcvCie5S0326swY6K2DHNAK98zdmRvjeWeHnyQ5Sp0iUBhNpj07Woqmqtdw7M2Cn6eScUvfM9xYzDncMQM0EKvg1iOraqABVR3zpBPHbtUk8X4zK1XSlOwAuJY7xDt1YjImWhjXzOYyCAxR/ZqwR21GJ/EcKPVKZ9xzUQpXZmB1OvZvdv5bOTGjjGEMurOtgbkSRbGs7yJ99WZVQB6YXeR7VxlMGCWtEy6dys1dKG2A==</ds:SignatureValue>
<ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIFJjCCBA6gAwIBAgIIFLflkM14PsAwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTYwODAyMDYyNTM4WhcNMTgwODAxMDcxODM4WjA5MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAMMCyoucGkxMDgubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1+yz4bzlc3WGxBbzUUTNdBJtnOxyOURJ015gBnUv9Bbt2NzDk8Q4hA1uxrLYyYbDlCLVDWBtD9Tw7VKNyIvZV3GmW5sqN+bMy4erkvr60stN+ndGvL3BGdMS4yJGaN5hExsT9xP2vrXlFcDwwCSGXEPX1bJ5k1x3kdKgAC/2s1kGhW1HZb8+TJLlAP3/ZH1tt0ujgF3Id8GBGafgcoMatFZY4i0uYRrW1LbSKUvhuh9IS2/vbytSe2VwGUiywpZk7lvuC4inCp1M2H9cegrdGCZ2M37BN0qlJCX9VncQvOOQjBKWPwQ5FiAVBB312MJ0Ky1hTA1N8/jty1Yc+zaR/wIDAQABo4IBtDCCAbAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYDVR0PAQH/BAQDAgWgMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2RpZzJzMS0yNzguY3JsMF0GA1UdIARWMFQwSAYLYIZIAYb9bQEHFwEwOTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5LzAIBgZngQwBAgEwdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQsgM4wIQYDVR0RBBowGIILKi5waTEwOC5uZXSCCXBpMTA4Lm5ldDAdBgNVHQ4EFgQUP3SfElMFgD0ZvaA+rvs81XQDEh4wDQYJKoZIhvcNAQELBQADggEBAF10vBjj4tOetpvMRXyAdX0GBO/8A7bG2H/kwO7E/0UOLfCQfb+0DxTWR8JtVhSf1g401qdDjq7jnhl8nxcF/RbihMBJ0l3ff6fEUqpcGBSoNWZu0mG1ETKOTTTj2yMGHDFSkA9PRCC6UWh3sHVWG3IhVAI4RPBLuH5XXZZ++0qLsv/x8KeHAjiFkWaYTdWifk3cf8dtMGBYo4LvtPWnknIrrh4/o3msNcsqw7WURbJ6cxxnOQ+dItxefQu4uksAc5IFlrmFkMqtAdBEHS8gfDbykdia8Wn8eqluX/4aI9KPLdJP0UuFSEI6Nidf0UYzjHtH2N0fLMSkJ/S1Dvm+0DE=</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_4f0ee53943a4f01bb82728a4e3f934c4c5028e1d6e" Version="2.0" IssueInstant="2017-05-15T10:59:54Z"><saml:Issuer>https://sso.pi108.net/simplesamlphp/www/saml2/idp/metadata.php</saml:Issuer><saml:Subject><saml:NameID SPNameQualifier="https://sso.pi108.net:9005/saml2/metadata" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_74188be2e8d0eb68e5628da90cd3c643ccce0cff50</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml:SubjectConfirmationData NotOnOrAfter="2017-05-15T11:04:54Z" Recipient="https://sso.pi108.net:9005/saml2/acs" InResponseTo="ONELOGIN_5f898daf78bbccb828234e11f3b3938febbcac3a"/></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore="2017-05-15T10:59:24Z" NotOnOrAfter="2017-05-15T11:04:54Z"><saml:AudienceRestriction><saml:Audience>https://sso.pi108.net:9005/saml2/metadata</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant="2017-05-15T10:52:38Z" SessionNotOnOrAfter="2017-05-15T18:52:38Z" SessionIndex="_04f9450d3f2b092c826c906f8e68813914d9771295"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement><saml:AttributeStatement><saml:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xsi:type="xs:string">test</saml:AttributeValue></saml:Attribute><saml:Attribute Name="eduPersonAffiliation" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"><saml:AttributeValue xsi:type="xs:string">member</saml:AttributeValue><saml:AttributeValue xsi:type="xs:string">student</saml:AttributeValue></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>
    [document] => DOMDocument Object
        (
            [doctype] => 
            [implementation] => (object value omitted)
            [documentElement] => (object value omitted)
            [actualEncoding] => 
            [encoding] => 
            [xmlEncoding] => 
            [standalone] => 1
            [xmlStandalone] => 1
            [version] => 1.0
            [xmlVersion] => 1.0
            [strictErrorChecking] => 1
            [documentURI] => /var/www/html/monitering_v2/public/
            [config] => 
            [formatOutput] => 
            [validateOnParse] => 
            [resolveExternals] => 
            [preserveWhiteSpace] => 1
            [recover] => 
            [substituteEntities] => 
            [nodeName] => #document
            [nodeValue] => 
            [nodeType] => 9
            [parentNode] => 
            [childNodes] => (object value omitted)
            [firstChild] => (object value omitted)
            [lastChild] => (object value omitted)
            [previousSibling] => 
            [attributes] => 
            [ownerDocument] => 
            [namespaceURI] => 
            [prefix] => 
            [localName] => 
            [baseURI] => /var/www/html/monitering_v2/public/
            [textContent] => https://sso.pi108.net/simplesamlphp/www/saml2/idp/metadata.php
  
    
  /YboUuY+jhnETP9hOUewroSmZ58=Z4Z35ta7jS4HrYIXB3j0VgY48nk0AIW+Ycdw6IziZKhEXX3sgzl01b9FnhurbMAOEwir5l5SPzfi0m3UUt1jk4rJNlqL6ypi03u0BfM2HbZwcvCie5S0326swY6K2DHNAK98zdmRvjeWeHnyQ5Sp0iUBhNpj07Woqmqtdw7M2Cn6eScUvfM9xYzDncMQM0EKvg1iOraqABVR3zpBPHbtUk8X4zK1XSlOwAuJY7xDt1YjImWhjXzOYyCAxR/ZqwR21GJ/EcKPVKZ9xzUQpXZmB1OvZvdv5bOTGjjGEMurOtgbkSRbGs7yJ99WZVQB6YXeR7VxlMGCWtEy6dys1dKG2A==
MIIFJjCCBA6gAwIBAgIIFLflkM14PsAwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTYwODAyMDYyNTM4WhcNMTgwODAxMDcxODM4WjA5MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAMMCyoucGkxMDgubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1+yz4bzlc3WGxBbzUUTNdBJtnOxyOURJ015gBnUv9Bbt2NzDk8Q4hA1uxrLYyYbDlCLVDWBtD9Tw7VKNyIvZV3GmW5sqN+bMy4erkvr60stN+ndGvL3BGdMS4yJGaN5hExsT9xP2vrXlFcDwwCSGXEPX1bJ5k1x3kdKgAC/2s1kGhW1HZb8+TJLlAP3/ZH1tt0ujgF3Id8GBGafgcoMatFZY4i0uYRrW1LbSKUvhuh9IS2/vbytSe2VwGUiywpZk7lvuC4inCp1M2H9cegrdGCZ2M37BN0qlJCX9VncQvOOQjBKWPwQ5FiAVBB312MJ0Ky1hTA1N8/jty1Yc+zaR/wIDAQABo4IBtDCCAbAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYDVR0PAQH/BAQDAgWgMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2RpZzJzMS0yNzguY3JsMF0GA1UdIARWMFQwSAYLYIZIAYb9bQEHFwEwOTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5LzAIBgZngQwBAgEwdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQsgM4wIQYDVR0RBBowGIILKi5waTEwOC5uZXSCCXBpMTA4Lm5ldDAdBgNVHQ4EFgQUP3SfElMFgD0ZvaA+rvs81XQDEh4wDQYJKoZIhvcNAQELBQADggEBAF10vBjj4tOetpvMRXyAdX0GBO/8A7bG2H/kwO7E/0UOLfCQfb+0DxTWR8JtVhSf1g401qdDjq7jnhl8nxcF/RbihMBJ0l3ff6fEUqpcGBSoNWZu0mG1ETKOTTTj2yMGHDFSkA9PRCC6UWh3sHVWG3IhVAI4RPBLuH5XXZZ++0qLsv/x8KeHAjiFkWaYTdWifk3cf8dtMGBYo4LvtPWnknIrrh4/o3msNcsqw7WURbJ6cxxnOQ+dItxefQu4uksAc5IFlrmFkMqtAdBEHS8gfDbykdia8Wn8eqluX/4aI9KPLdJP0UuFSEI6Nidf0UYzjHtH2N0fLMSkJ/S1Dvm+0DE=https://sso.pi108.net/simplesamlphp/www/saml2/idp/metadata.php_74188be2e8d0eb68e5628da90cd3c643ccce0cff50https://sso.pi108.net:9005/saml2/metadataurn:oasis:names:tc:SAML:2.0:ac:classes:Passwordtestmemberstudent
        )

    [decryptedDocument] => 
    [encrypted] => 
    [_error:OneLogin_Saml2_Response:private] => Signature validation failed. SAML Response rejected
)

I tried to decrypt the response  and can see the response object has all the student required/specified attributes.

However I am not able to get why the SP rejecting the response. 
What is the criteria to accept/reject the response. Is it a pem/cert/key?

Please help me, I am struggling since last 2 days.

Thanks in advance
Paresh Kendre
kendreparesh@gmail.com

**Comment by pitbulk** [comment]
Signature validation failed. SAML Response rejected means that the [x509 cert of the IdP registered config file](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L93) is wrong and differ than the one used by the IdP.

Based on your message, you registered
```
-----BEGIN CERTIFICATE-----
MIID/TCCAuWgAwIBAgIJAI4R3WyjjmB1MA0GCSqGSIb3DQEBCwUAMIGUMQswCQYD
VQQGEwJBUjEVMBMGA1UECAwMQnVlbm9zIEFpcmVzMRUwEwYDVQQHDAxCdWVub3Mg
QWlyZXMxDDAKBgNVBAoMA1NJVTERMA8GA1UECwwIU2lzdGVtYXMxFDASBgNVBAMM
C09yZy5TaXUuQ29tMSAwHgYJKoZIhvcNAQkBFhFhZG1pbmlAc2l1LmVkdS5hcjAe
Fw0xNDEyMDExNDM2MjVaFw0yNDExMzAxNDM2MjVaMIGUMQswCQYDVQQGEwJBUjEV
MBMGA1UECAwMQnVlbm9zIEFpcmVzMRUwEwYDVQQHDAxCdWVub3MgQWlyZXMxDDAK
BgNVBAoMA1NJVTERMA8GA1UECwwIU2lzdGVtYXMxFDASBgNVBAMMC09yZy5TaXUu
Q29tMSAwHgYJKoZIhvcNAQkBFhFhZG1pbmlAc2l1LmVkdS5hcjCCASIwDQYJKoZI
hvcNAQEBBQADggEPADCCAQoCggEBAMbzW/EpEv+qqZzfT1Buwjg9nnNNVrxkCfuR
9fQiQw2tSouS5X37W5h7RmchRt54wsm046PDKtbSz1NpZT2GkmHN37yALW2lY7My
VUC7itv9vDAUsFr0EfKIdCKgxCKjrzkZ5ImbNvjxf7eA77PPGJnQ/UwXY7W+cvLk
irp0K5uWpDk+nac5W0JXOCFR1BpPUJRbz2jFIEHyChRt7nsJZH6ejzNqK9lABEC7
6htNy1Ll/D3tUoPaqo8VlKW3N3MZE0DB9O7g65DmZIIlFqkaMH3ALd8adodJtOvq
fDU/A6SxuwMfwDYPjoucykGDu1etRZ7dF2gd+W+1Pn7yizPT1q8CAwEAAaNQME4w
HQYDVR0OBBYEFPsn8tUHN8XXf23ig5Qro3beP8BuMB8GA1UdIwQYMBaAFPsn8tUH
N8XXf23ig5Qro3beP8BuMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
AGu60odWFiK+DkQekozGnlpNBQz5lQ/bwmOWdktnQj6HYXu43e7sh9oZWArLYHEO
yMUekKQAxOK51vbTHzzw66BZU91/nqvaOBfkJyZKGfluHbD0/hfOl/D5kONqI9ky
Tu4wkLQcYGyuIi75CJs15uA03FSuULQdY/Liv+czS/XYDyvtSLnu43VuAQWN321P
QNhuGueIaLJANb2C5qq5ilTBUw6PxY9Z+vtMjAjTJGKEkE/tQs7CvzLPKXX3KTD9
lIILmX5yUC3dLgjVKi1KGDqNApYGOMtjr5eoxPQrqDBmyx3flcy0dQTdLXud3UjW
VW3N0PYgJtw5yBsS74QTGD4=
-----END CERTIFICATE-----
```

and the one on the SAMLResponse:

```
<ds:X509Certificate>MIIFJjCCBA6gAwIBAgIIFLflkM14PsAwDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTYwODAyMDYyNTM4WhcNMTgwODAxMDcxODM4WjA5MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0ZWQxFDASBgNVBAMMCyoucGkxMDgubmV0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1+yz4bzlc3WGxBbzUUTNdBJtnOxyOURJ015gBnUv9Bbt2NzDk8Q4hA1uxrLYyYbDlCLVDWBtD9Tw7VKNyIvZV3GmW5sqN+bMy4erkvr60stN+ndGvL3BGdMS4yJGaN5hExsT9xP2vrXlFcDwwCSGXEPX1bJ5k1x3kdKgAC/2s1kGhW1HZb8+TJLlAP3/ZH1tt0ujgF3Id8GBGafgcoMatFZY4i0uYRrW1LbSKUvhuh9IS2/vbytSe2VwGUiywpZk7lvuC4inCp1M2H9cegrdGCZ2M37BN0qlJCX9VncQvOOQjBKWPwQ5FiAVBB312MJ0Ky1hTA1N8/jty1Yc+zaR/wIDAQABo4IBtDCCAbAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDgYDVR0PAQH/BAQDAgWgMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2RpZzJzMS0yNzguY3JsMF0GA1UdIARWMFQwSAYLYIZIAYb9bQEHFwEwOTA3BggrBgEFBQcCARYraHR0cDovL2NlcnRpZmljYXRlcy5nb2RhZGR5LmNvbS9yZXBvc2l0b3J5LzAIBgZngQwBAgEwdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5nb2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47MNIMwojPX+2yz8LQsgM4wIQYDVR0RBBowGIILKi5waTEwOC5uZXSCCXBpMTA4Lm5ldDAdBgNVHQ4EFgQUP3SfElMFgD0ZvaA+rvs81XQDEh4wDQYJKoZIhvcNAQELBQADggEBAF10vBjj4tOetpvMRXyAdX0GBO/8A7bG2H/kwO7E/0UOLfCQfb+0DxTWR8JtVhSf1g401qdDjq7jnhl8nxcF/RbihMBJ0l3ff6fEUqpcGBSoNWZu0mG1ETKOTTTj2yMGHDFSkA9PRCC6UWh3sHVWG3IhVAI4RPBLuH5XXZZ++0qLsv/x8KeHAjiFkWaYTdWifk3cf8dtMGBYo4LvtPWnknIrrh4/o3msNcsqw7WURbJ6cxxnOQ+dItxefQu4uksAc5IFlrmFkMqtAdBEHS8gfDbykdia8Wn8eqluX/4aI9KPLdJP0UuFSEI6Nidf0UYzjHtH2N0fLMSkJ/S1Dvm+0DE=</ds:X509Certificate>
```

**Comment by pkendre** [comment]
Thanks a lot for your quick reply.

I have copied the crt file content and pasted as value to he key named "x509cert" in saml2_settings.php and it worked :)

You saved my life. Thanks a lot :)

**Comment by chrisford-vcreative** [comment]
I am having a very similar problem except I've verified that the X509 certs match on the SP and IdP. Also, both the XML to Schema and AuthN Requests return valid on samltool.com, but the SAML Response won't validate and returns "Signature validation failed." I'm not sure how to continue troubleshooting this issue. However, I feel like it's some configuration on the IdP side.

**Comment by 1073876389** [comment]
![image](https://user-images.githubusercontent.com/33409711/76620507-43663f80-6568-11ea-8569-7fee4400f95b.png)
I have the same problem

**Comment by chenrui333** [comment]
facing the same issue.

**Comment by chenrui333** [comment]
I ended up making an issue in the java-saml repo, https://github.com/onelogin/java-saml/issues/275

**Comment by ducttapecoder-vt** [comment]
For anyone else troubleshooting that ends up here: My error turned out to be providing a SHA1 thumbprint/hash for the cert to an app that wanted the SHA256 thumbprint/hash.

**Comment by Et7f3** [comment]
We added:
```
    echo "error: ".openssl_error_string();
```
because we use openssl verification instead of hardcoding sha1.
https://github.com/SAML-Toolkits/php-saml/blob/f97d1e840bc6d4cd2f85262db3003aa79610d073/extlib/xmlseclibs/xmlseclibs.php#L409-L417

This showed us https://stackoverflow.com/q/74574684/7227940

Hope this help someone.

We migrated from openssl 1.x to openssl3 and setting were hardened to remove old SHA1.
`update-crypto-policies --set DEFAULT:SHA1` might come handy (or use `LEGACY` if your app is too weak/old).

**Comment by NivethaAravind** [comment]
I am using SHA_256 as signature algorithm.But still i am getting below error
2025-03-24 12:26:11,987 8310 ERROR test-odoo-db saml2.sigver: returncode=1
error=func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=368:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify
FAIL
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
Error: failed to verify file "/tmp/tmp4b7m4b5c.xml"

output=
2025-03-24 12:26:11,987 8310 ERROR test-odoo-db saml2.sigver: check_sig: ['/usr/bin/xmlsec1', '--verify', '--enabled-reference-uris', 'empty,same-doc', '--enabled-key-data', 'raw-x509-cert', '--pubkey-cert-pem', '/tmp/tmpb8jm18j_.pem', '--id-attr:ID', 'urn:oasis:names:tc:SAML:2.0:protocol:Response', '--node-id', 'irTQq16LMwe6Hslx7AJY8HtPuHb', '--output', '/tmp/tmpbbblp901.xml', '/tmp/tmp4b7m4b5c.xml']
2025-03-24 12:26:11,987 8310 ERROR test-odoo-db saml2.entity: Signature Error: Failed to verify signature
2025-03-24 12:26:11,988 8310 ERROR test-odoo-db saml2.client_base: XML parse error: Failed to verify signature

Thanks in advance
