### ISSUE TITLE
requestedAuthnContext default value

### ISSUE THREAD

**Issue by BrandonNoad** [onelogin/php-saml#217]
According to the changelog, in v2.8.0 you "Set none requestedAuthnContext as default behaviour".

The commit that fixed #62, however, seemed to only update one of the example files (https://github.com/onelogin/php-saml/commit/01829e6ec722fe8695855e8ed8291d0f066bab0b).

In onelogin/php-saml/lib/Saml2/Settings.php, where the default settings seem to be set, we have the following code:

```
if (!isset($this->_security['requestedAuthnContext'])) {
    $this->_security['requestedAuthnContext'] = true;
}
```

So the default seems to actually be `true`, and you end up with `urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport`.

Also, the description of the `requestedAuthnContext` in the readme:

```
// Authentication context.
// Set to false or don't present this parameter and no AuthContext will be sent in the AuthNRequest,
// Set true and you will get an AuthContext 'exact' 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
// Set an array with the possible auth context values: array ('urn:oasis:names:tc:SAML:2.0:ac:classes:Password', 'urn:oasis:names:tc:SAML:2.0:ac:classes:X509'),
```

seems to contradict the description in advanced_settings_example.php:

```
// Authentication context.
// Set to false and no AuthContext will be sent in the AuthNRequest,
// Set true or don't present this parameter and you will get an AuthContext 'exact' 'urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport'
// Set an array with the possible auth context values: array ('urn:oasis:names:tc:SAML:2.0:ac:classes:Password', 'urn:oasis:names:tc:SAML:2.0:ac:classes:X509'),
```

**Comment by pitbulk** [comment]
On #62 I changed the default value that the toolkit had at  advanced_settings_example.php.
You are right, the changelog is wrong, it should say:
"Set requestedAuthnContext to false (none requestedAuthnContext sent on AuthNReqest) at advanced_settings.php".

The description on the readme and advanced_settings_example.php describes the current behavior.

A change on the default behavior of that parameter can create incompatibility issues. That why I only change the value of the setting template.

**Comment by BrandonNoad** [comment]
Thanks. That clears things up a bit.

I still think the main readme is wrong since it says: 

"don't present this parameter and no AuthContext will be sent in the AuthNRequest"

**Comment by pitbulk** [comment]
Can you send a PR to fix that?

**Comment by BrandonNoad** [comment]
Yes. I can do that.
