### ISSUE TITLE
Does php-saml supports two decryption certificates simultaneously?

### ISSUE THREAD

**Issue by adrian7** [onelogin/php-saml#221]
We're in the process of renewing our SP certs and we were advised to support both decryption certificates during the transition period. 

Is there a way to achieve this with onelogin toolkit?

**Comment by pitbulk** [comment]
The '[x509certNew](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L76)' setting parameter let you to add the future SP public cert, and it will be published on the SP metadata.

but take in mind that the data encrypted by the SP only will be encrypted with the '[x509cert](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L66)' SP public cert.
