### ISSUE TITLE
Support duplicated Attribute Names?

### ISSUE THREAD

**Issue by clintwilson** [onelogin/php-saml#223]
I saw the response given on #170, but I was wondering if the position indicated on https://github.com/onelogin/php-saml/issues/170#issuecomment-255359227 would be reconsidered. We have a customer use case wherein the IDP sends a specific Attribute Name multiple times rather than combining all Attribute Values under a single Attribute Name.
It seems like it would be relatively straightforward to have lib/phpsaml/lib/Saml2/Response.php collect all Attribute Values from all duplicate Attribute Names and combine them into a single array, similarly to if the IDP were to combine them. Maybe something like this:
\
         foreach ($entries as $entry) {
             $attributeName = $entry->attributes->getNamedItem('Name')->nodeValue;
 
\-            if (in_array($attributeName, array_keys($attributes))) {
\-                throw new OneLogin_Saml2_ValidationError(
\-                    "Found an Attribute element with duplicated Name",
\-                    OneLogin_Saml2_ValidationError::DUPLICATED_ATTRIBUTE_NAME_FOUND
\-                );
\-            }
+//            if (in_array($attributeName, array_keys($attributes))) {
+//                throw new OneLogin_Saml2_ValidationError(
+//                    "Found an Attribute element with duplicated Name",
+//                    OneLogin_Saml2_ValidationError::DUPLICATED_ATTRIBUTE_NAME_FOUND
+//                );
+//            }
\
             $attributeValues = array();
             foreach ($entry->childNodes as $childNode) {
@@ -727,6 +727,10 @@ class OneLogin_Saml2_Response
                 }
             }
 
\+            if (array_key_exists($attributeName, $attributes)) {
\+                $attributeValues = array_merge($attributes[$attributeName], $attributeValues);
\+            }
\+
             $attributes[$attributeName] = $attributeValues;
         }
         return $attributes;

**Comment by pitbulk** [comment]
We intentionally prevent the use of  DUPLICATED_ATTRIBUTES and we don't plan to change that behavior.
If that IdP is not able to send the attributes on a different way, you always can extend the SAMLResponse class and customize it with your needs.
