### ISSUE TITLE
Reference Validation Failed after updating to 2.10.7 from 2.5.0

### ISSUE THREAD

**Issue by jrossiter** [onelogin/php-saml#225]
One particular IdP is receiving this error after the update.

Validating against https://www.samltool.com/validate_response.php also brings up the same error.

`Signature validation failed. Reference validation failed`

It appears that digest values being generated differ in `xmlseclibs.php validateDigest()`.

I've gone through some of the closed issues and have tested that:
- 2.10.0+ returns the same error
- 2.8.0 works

Please let me know what additional details you'll need to help find out why this is occurring only after updating to 2.10.7.

**Comment by pitbulk** [comment]
Can you provide the settings you are using? (hide the private info) and an example of the SAMLResponse that is invalidated?

**Comment by jrossiter** [comment]
```xml
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Consent="urn:oasis:names:tc:SAML:2.0:consent:current-implicit" Destination="https://.../url" ID="_285642c6c38592cc77f31611aa11dc86" InResponseTo="ONELOGIN_f69f1f8cc81a24ca152543e7437e709a05feccca" IssueInstant="2017-06-10T01:30:39Z" Version="2.0"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://.../auth/saml-endpoint.cgi</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="#_285642c6c38592cc77f31611aa11dc86">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
<ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="ds saml samlp xenc"/>
</ds:Transform>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>tpt5aQZ5KCm4esR16vCTMM5xU2Y=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>...</ds:SignatureValue>
<ds:KeyInfo><ds:X509Data><ds:X509Certificate>...</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:EncryptedAssertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"><xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Type="http://www.w3.org/2001/04/xmlenc#Element">
<xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
<xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"/>
</xenc:EncryptionMethod>
<xenc:CipherData>
<xenc:CipherValue>...</xenc:CipherValue>
</xenc:CipherData>
</xenc:EncryptedKey></ds:KeyInfo>
<xenc:CipherData>
<xenc:CipherValue>...</xenc:CipherValue>
</xenc:CipherData></xenc:EncryptedData></saml:EncryptedAssertion></samlp:Response>```

Settings:
- strict: true
- security:
 - nameIdEncrypted: true
 - authnRequestsSigned: true
 - logoutRequestSigned: true
 - logoutResponseSigned: true
 - signMetadata: true
 - wantMessagesSigned: true
 - wantAssertionsSigned: true
 - wantNameIdEncrypted: false
 - requestedAuthnContext: false

Let me know if I've removed too much or have missed anything.

**Comment by pitbulk** [comment]
On the XML I don't see a reason to cause the "Signature validation failed"

Can you play with settings on IdP / SP side to determine if the error is related with a specific settings?

- Signed SAMLResponse and signed assertion with assertion encrypted
- Signed SAMLResponse and signed assertion with no encryption
- Signed SAMLResponse with assertion encrypted (but no signed)
- Unsigned SAMLResponse with with assertion signed and encrypted

**Comment by jrossiter** [comment]
Unfortunately I don't have access to the IdP.

Validating against https://www.samltool.com/validate_response.php returns "Signature validation failed". This form doesn't consider any of those settings and still returns the error.

I can email you the response data if that would help.

**Comment by pitbulk** [comment]
That site uses php-saml so is normal that if php-saml fails to validate your samlresponse, samltool also fails.

**Comment by jrossiter** [comment]
I agree, so playing around with the specific settings shouldn't make a difference in this case.

**Comment by pitbulk** [comment]
Are you using ADFS as IdP?

Have you enabled the advanced setting [lowercaseUrlencoding](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L101) or tried with [$retrieveParametersFromServer](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L221) as true?

**Comment by jrossiter** [comment]
IIRC they may have been using ADFS. 
I'll give these settings a try and see how it goes.
