### ISSUE TITLE
Clarification on SP cert settings

### ISSUE THREAD

**Issue by JasonMortonNZ** [onelogin/php-saml#231]
Just after some clarification on the `sp.cert` settings.

I'm pulling in this library using composer so storing my SP certs in the vendor folder is not ideal. The comments provided above these settings in the `settings_example.php` file mentions that we can provide cert values if necessary. What are these two setting values required to be:

1. A file path to each cert relative to the `settings.php` file
2. The certificate values inlined (maybe base64encoded)
3. Something else...

Any clarification on this would be helpful.

**Note:** Settings and file being referred to can be found [here](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L64)

**Comment by pitbulk** [comment]
If you define a [ONELOGIN_CUSTOMPATH](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L164) const, you will be able to place config and certs in a custom path.  We use that "trick" for the [testing environment](https://github.com/onelogin/php-saml/blob/master/tests/bootstrap.php#L21).

For some scenarios, make sense to store data on database and not in filesystem, for example, that [wordpress SAML plugin](https://github.com/onelogin/wordpress-saml) stores SAML setting data on a database, so the settings.php file looks like [that](https://github.com/onelogin/wordpress-saml/blob/master/onelogin-saml-sso/php/settings.php).  You can use the same approach to generate your settings.php... 

At the end, settings.php is just a file that contains an array with SAML data.. so you don't need that file at all, and just generate the saml setting array.
