### ISSUE TITLE
Invalid issuer in the Assertion/Response, invalid_response

### ISSUE THREAD

**Issue by nWidart** [onelogin/php-saml#232]
Hello,

After getting a successful login on the IdP, I'm getting the following error while processing the saml response.

```
Invalid issuer in the Assertion/Response, invalid_response
```

What could be the cause of this issue ? Would it be something on my end, or the provider's end ?

Thanks,

**Comment by pitbulk** [comment]
That errors happens [when the Issuer value of the SAMLResponse (Message/Assertion) does not match IdP Entity ID](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L266).

Review on [php-saml settings the 'entityId'](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L82) value and take a look at the IdP metadata.

**Comment by nWidart** [comment]
Thanks for your help, that as indeed it.

**Comment by mattdrayer** [comment]
Just a note that I ran into this issue as well (using the python version of this package) and the problem ended up having to do with case sensitivity.  The issuer value sent by the IdP was lowercase and the EntityID value on the SP side contained some uppercase characters.  These were modified to lowercase and then the workflow executed correctly.
