### ISSUE TITLE
Debug mode doesn't log enough information

### ISSUE THREAD

**Issue by EspadaV8** [onelogin/php-saml#235]
We're trying to debug an issue where the XML isn't parsing but there's no way to get a log of the XML that was received. Reading through the code it seems that logging in general is very limited. It would be great if this could be greatly improved, ideally with multiple levels of logging supported, integrated with [Monolog](https://github.com/Seldaek/monolog).

**Comment by pitbulk** [comment]
That suggestion seems a good improvement for the 3.0.0 branch.

Meanwhile, you can use [getLastRequestXML](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L669) and [getLastResponseXML](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L682) methods.
