### ISSUE TITLE
SHA-1 is not considered to be secure anymore, never use it as default hash

### ISSUE THREAD

**Issue by klausi** [onelogin/php-saml#237]
See https://shattered.io/

I don't know the SAML protocol very well, can we just replace the default with a better option such as SHA-256? Do all SAML servers support that?

**Comment by pitbulk** [comment]
You only need to set the desired [signatureAlgorithm](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L90) and [digestAlgorithm](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L97).

**Comment by klausi** [comment]
Sure, but this issue is about using correct default values. This library uses SHA-1 as default, which is a bad security choice. Can we reopen this to fix the defaults?

**Comment by pitbulk** [comment]
but change that "default" behavior can break current environments.

I think makes sense to do that on the future 3.0.0 branch only.
