### ISSUE TITLE
Utils::getSelfPort() does not detect correct port 

### ISSUE THREAD

**Issue by garethellis36** [onelogin/php-saml#238]
Our development environment is running in a vagrant box. We have to access the web server via port forwarding, so we are visiting https://app.domain.com:44300, although Nginx is serving on port 443 as normal.

Our ADFS configuration works perfectly with the toolkit (nice job!) except for one small part - SAML responses are deemed invalid because the current URL does not match the expected URL. I debugged and found that the `Utils::getSelfPort()` method is returning `443` (the port that Nginx is running on) and not `44300` (the actual port and the one which is in our local dev metadata).

In essence this is because line 500 checks for `$_SERVER["SERVER_PORT"]` and returns that value.

My proposed change is to extract the code from the `else` block of this method into a private method and refactor as follows:

```php
    public static function getSelfPort()
    {
        $portnumber = null;

        if (self::$_port) {
            $portnumber = self::$_port;
        } else if (self::getProxyVars() && isset($_SERVER["HTTP_X_FORWARDED_PORT"])) {
            $portnumber = $_SERVER["HTTP_X_FORWARDED_PORT"];
        } else if (isset($_SERVER["SERVER_PORT"]) && $_SERVER["SERVER_PORT"] == self::getSelfPortFromSelfRawHost()) {
            $portnumber = $_SERVER["SERVER_PORT"];
        } else {
            $portnumber = self::getSelfPortFromSelfRawHost();
        }
        return $portnumber;
    }

    private static function getSelfPortFromSelfRawHost()
    {
            $currentHost = self::getRawHost();

            // strip the port
            if (false !== strpos($currentHost, ':')) {
                list($currentHost, $port) = explode(':', $currentHost, 2);
                if (is_numeric($port)) {
                    $portnumber = $port;
                }
            }
    }
```

This way it will only return the value of `$_SERVER["SERVER_PORT"]` if it matches the actual value from the raw host.

I'm happy to submit a PR for this if deemed appropriate.

**Comment by pitbulk** [comment]
Have you read that part of the documentation? [url-guessing-methods](https://github.com/onelogin/php-saml#url-guessing-methods)

If I'm not wrong, nginx should write a valid port value at $_SERVER["HTTP_X_FORWARDED_PORT"]
so all you need to do is to enable the proxy vars by:
```
setProxyVars(true)
```

**Comment by garethellis36** [comment]
Nginx doesn't seem to expose that default (at least, without additional configuration). I have worked around the problem by setting the port with Utils::setSelfPort() but this requires additional code to work out the actual port in the client application, so if this could be resolved within the library it would be ideal. Perhaps my PR is not the right solution though.

**Comment by pitbulk** [comment]
That change was not applied since that change the behavior of the current toolkit.

In your solution you give priority to the  $_SERVER['HTTP_HOST'] vs $_SERVER['SERVER_PORT'],

in the current code, $_SERVER['SERVER_PORT'] has priority over the port extracted from the $_SERVER['HTTP_HOST'].

That change can break environments using the toolkit.
