### ISSUE TITLE
Deprecated mcrypt dependency

### ISSUE THREAD

**Issue by ccorliss** [onelogin/php-saml#240]
mcrypt has been deprecated in php 7.1
http://php.net/manual/en/migration71.deprecated.php

![image](https://user-images.githubusercontent.com/264715/28680457-42c97bda-72ab-11e7-8c60-44fc6a1e2135.png)

Is there any plan to replace this dependency with something else?

**Comment by pitbulk** [comment]
Branch 3.0.0 is not using mcrypt anymore.
