### ISSUE TITLE
composer update removing files

### ISSUE THREAD

**Issue by liamkavfc** [onelogin/php-saml#241]
So when you make a copy of the settings.php, where is the best place to store these where the vendor files will still call to them.

My reason behind the question is, I made a copy of settings_example.php -> settings.php, edited it accordingly then save it in the same directory as settings_example which is inside the vendor files. Now, when composer ran the recent update, it completely wiped out my settings file. How has everyone else dealt with this problem?

**Comment by LukasReschke** [comment]
As per https://github.com/onelogin/php-saml#option-2-composer:

> Your settings are at risk of being deleted when updating packages using composer update or similiar commands. So it is highly recommended that instead of using settings files, you pass the settings as an array directly to the constructor (explained later in this document). If you do not use this approach your settings are at risk of being deleted when updating packages using composer update or similiar commands.

So pass it to `OneLogin_Saml2_Settings` as array a done at https://github.com/onelogin/php-saml/blob/818d6ee07e3797fd7e4006bff01bd2abc295cb65/demo1/metadata.php#L15 and https://github.com/onelogin/php-saml/blob/818d6ee07e3797fd7e4006bff01bd2abc295cb65/demo1/settings_example.php#L5-L25

**Comment by AzaZPPL** [comment]
You could also set the environment variable `ONELOGIN_CUSTOMPATH`. This set's the config directory to the `ONELOGIN_CUSTOMPATH` and the certs under `ONELOGIN_CUSTOMPATH/certs/`
