### ISSUE TITLE
IdP x509 certificate is required in 2.11.0, but it shouldn't be according to SAML 2.0 specification

### ISSUE THREAD

**Issue by alex-vlasov** [onelogin/php-saml#245]
Latest changes in 2.11.0 make x509 certificate required - https://github.com/onelogin/php-saml/commit/84aa522b27a8d44cfc2f0229aa8963b9de438eec
If it's not provided we get an error `idp_cert_or_fingerprint_not_found_and_required`.

While it's common sense to always use signing in SAML, the specification doesn't require it.
https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf - starts on line 3000.
It says that SAML messages `may be signed`.

**Comment by pitbulk** [comment]
Providing a cert or fingerprint was always a requirement for php-saml in order to validate SAMLResponse signature.

A signature on the whole message or the assertion is a MUST on SAML standard.

**Comment by alex-vlasov** [comment]
While I totally agree with you that it's a must, we have a spec that says otherwise. Given your library claims SAML2.0 support we may need to take it into consideration.
Here are excerpts from the spec I post a link to:

> A digital signature is not always required in SAML. ... As another example, the SAML relying party or SAML requester may have obtained an assertion or protocol message from the SAML asserting party or SAML responder directly (with no intermediaries) through a secure channel, with the asserting party or SAML responder having authenticated to the relying party or SAML responder by some means other than a digital signature.
