### ISSUE TITLE
PHP7.1 support after deprecating ext/mcrypt

### ISSUE THREAD

**Issue by michalkleiner** [onelogin/php-saml#246]
With PHP7.1.x, functions using ext/mcrypt in 
https://github.com/onelogin/php-saml/blob/master/extlib/xmlseclibs/xmlseclibs.php are deprecated and cause the decryption to fail.

These are e.g. mcrypt_module_open or mcrypt_enc_get_iv_size.

Is there a plan on upgrading this library to use supporting PHP7.1+?

**Comment by pitbulk** [comment]
There is a branch that eliminates the mcrypt dependency: [remove_mcrypt](https://github.com/onelogin/php-saml/tree/remove_mcrypt)

And [3.0.0](https://github.com/onelogin/php-saml/tree/3.0.0) version works with no mcrypt

**Comment by bytestream** [comment]
@pitbulk sorry to dig this up. I'm looking at the https://github.com/onelogin/php-saml/tree/remove_mcrypt branch (and the comparison: https://github.com/onelogin/php-saml/compare/master...remove_mcrypt)

It looks as though you've set a hard-dependency of PHP 5.6 but I believe xmlseclibs later reverted the PHP dependency back to 5.4, see:
https://github.com/robrichards/xmlseclibs/pull/123
https://github.com/robrichards/xmlseclibs/pull/138

Please could you pull that change and update the branch?

**Comment by pitbulk** [comment]
@bytestream I think 3.0.0 branch is what you need, not remove_mcrypt

**Comment by pitbulk** [comment]
Done:
* remove_mcrypt https://github.com/onelogin/php-saml/commit/06a94653172a7029d8087842e030af80126a4a2f
* 3.0.0 https://github.com/onelogin/php-saml/commit/19aefe2b03ee4368203cbc7bc9225a0b508f7a0b
