### ISSUE TITLE
tracking a session without $_SESSION ?

### ISSUE THREAD

**Issue by porjo** [onelogin/php-saml#247]
I'm using php behind a load balancer and don't use `$_SESSION` as a result.

I'd like to use php-saml as a SP, and track the request ID from the SSO to ACS. The examples show the requestID being saved into `$_SESSION` in the SSO step and being retrieved in the ACS step and passed as an argument to `processResponse()`.

I realise that checking the request ID against responses isn't mandatory, however it seems like good practice. And I'd prefer not to rely on setting a cookie in the user's browser.

If `inResponseTo` value were exposed in the response object, I could check that against the database to see if there's a matching request ID. Is that a change the library author would support making?

**Comment by pitbulk** [comment]
You can store the request ID on session, file, database or whatever.
The code you see at demo1 is just an example of how use the php-saml toolkit.

There is not change required on php-saml that prevent you to store request ID on database and provide it later on the isValid method of the SAMLResponse to verify it with the inResponseTo value.

**Comment by porjo** [comment]
As `inResponseTo` value is private, I would literally have to try every request ID in my database against `isValid()` !

So my question is can `inResponseTo` value be exposed publicly e.g. via a new `getResponseId()` or `getInResponseTo()` method? That way I only need to do a single database lookup.

**Comment by lexakozakov** [comment]
@pitbulk Could please give any example? If requestID is stored in database, how can we identify what requestID should be fetched from database for processResponse()?  

Thank you.

**Comment by pitbulk** [comment]
@lexakozakov 
You only need to validate that the Response_To attribute from the SAMLResponse exists on the database (you stored it previously in the SP-initiated login flow, when generated the AuthNRequest.

To avoid reply attacks, you should also store the ID of the SAMLResponse and verify that a SAMLResponse with ID=XXX is only processed one time.

You can set a short expiration time on those stored values. (SAML Message used to be a validation of 3-5 min) so when the Message is invalidated due the time, you don't need to keep its ID registered on your database.
