### ISSUE TITLE
ADFS Invalid Signature on Logout

### ISSUE THREAD

**Issue by dragosnicolescu** [onelogin/php-saml#251]
Hello,

I'm trying to use the Onelogin PHP SAML library to integrate our SP with an ADFS IdP. 

Everything works smoothly, apart from Logout. 
For Logout, I'm using Redirect Binding, and manage to get a "Success" status code from ADFS. The problem is I can't get the IdP signature for the Logout response to validate in Onelogin.

I'm getting the following errors:

> error:0906D06C:PEM routines:PEM_read_bio:no start line
error:04091068:rsa routines:INT_RSA_VERIFY:bad signature
 
in `xmlseclibs.php`, function `verifyOpenSSL`, inside `openssl_verify` (I'm using `openssl_error_string` to get the errors).

For signature validation, I have the IdP X509 certificate in settings. I'm using the certificate listed in ADFS under "Token-signing". It's the first time I'm using ADFS, so there might me something I'm missing on that end, too.

This is my settings file (replaced certificate values with "..."):

```
<?php
$spBaseUrl = 'https://10.25.40.46'; //or http://<your_domain>
$settingsInfo = array (
    'compress' => array (
        'requests' => true,
        'responses' => true
    ),

    // Security settings
    'security' => array (
        'nameIdEncrypted' => false,
        'authnRequestsSigned' => false,
        'logoutRequestSigned' => true,
        'logoutResponseSigned' => true,
        'signMetadata' => false,


        'wantMessagesSigned' => true,
        'wantAssertionsEncrypted' => false,
        'wantAssertionsSigned' => false,
        'wantNameId' => true,
        'wantNameIdEncrypted' => false,
        'requestedAuthnContext' => false,
        'requestedAuthnContextComparison' => 'exact',
        'wantXMLValidation' => true,
        'relaxDestinationValidation' => false,

        'signatureAlgorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
        'digestAlgorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',

        'lowercaseUrlencoding' => true,
    ),

    'sp' => array (
        'entityId' => $spBaseUrl.'/Projects/GzSaml/vendor/onelogin/php-saml/demo1/metadata.php',
        'assertionConsumerService' => array (
            'url' => $spBaseUrl.'/Projects/GzSaml/vendor/onelogin/php-saml/demo1/index.php?acs',
        ),
        'singleLogoutService' => array (
            'url' => $spBaseUrl.'/Projects/GzSaml/vendor/onelogin/php-saml/demo1/index.php?sls',
        ),
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',

        // Usually x509cert and privateKey of the SP are provided by files placed at
        // the certs folder. But we can also provide them with the following parameters
        'x509cert' => '-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----',
        'privateKey' => '-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----',
    ),
    'idp' => array (
        'entityId' => 'https://sso.bd.biz/adfs/ls',
        'singleSignOnService' => array (
            'url' => 'https://sso.bd.biz/adfs/ls',
        ),
        'singleLogoutService' => array (
            'url' => 'https://sso.bd.biz/adfs/ls',
        ),
        'x509cert' => '-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----',
    ),
);
```

Am I missing something when it comes to configuration, or could there be a problem in the Openssl functions?

**Comment by pitbulk** [comment]
The settings look good, maybe instead the full string with head and footer you can set just the string.
Use [format_x509cert](https://www.samltool.com/format_x509cert.php) and [format_privatekey](https://www.samltool.com/format_privatekey.php)

**Comment by dragosnicolescu** [comment]
No luck. 
I've used [validate_logout_res](https://www.samltool.com/validate_logout_res.php) to try to validate the logout response i get from ADFS and it, too, says the signature is invalid.

Just to confirm: the 'x509cert' setting for the IdP should contain the Certificate (pem format) that is found in ADFS under "Token-signing", right? 
Also, there should be no private key on the SP for this certificate, as it is only used for signature validation (from my understanding). 

I can't understand why `openssl_verify` would give the 

> error:0906D06C:PEM routines:PEM_read_bio:no start line

error for this certificate.

**Comment by pitbulk** [comment]
In order to validate signatures of SAML Messages sent by the Identity Provider, the Service Provider requires a certificate registered on the settings at the IdP section ([x509cert](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L102))

In order to sign or let the IdP encrypt, Service Provider needs a public cert/private key on the [SP section](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L66).

Read that [tutorial about openssl](https://www.zimuel.it/blog/sign-and-verify-a-file-using-openssl) and try to validate the SAMLMessage directly with the openssl command. If you are not able to validate it with openssl, something should be wrong (certificate or ADFS configuration).

**Comment by dragosnicolescu** [comment]
Still not being able to solve this issue, I thought I'd check the Logout Response sent by the Onelogin IdP (app.onelogin.com).  
I used the "SAML Test Connector (IdP w/ attr w/ sign response)" template, and to my surprise, there was no signature on the Logout Response. Upon further reasearch, I came across the same issue raised by someone else one year ago ([here](https://stackoverflow.com/questions/37954468/onelogin-signout-response-missing-signature)). 
I know this has nothing to do with the PHP library, but any idea if this been solved in the meantime, is there another connector template I should use?

**Comment by pitbulk** [comment]
Have you tried using the [lowercaseUrlencoding](
https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L101) parameter.

Try configure it as true.

**Comment by dragosnicolescu** [comment]
Yes, I had "lowercaseUrlencoding" set to True, but that setting is used when the SP is signing requests, not checking signatures on responses.

What is used for responses is "retrieveParametersFromServer" ([source](https://github.com/onelogin/php-saml/issues/130), [source](https://github.com/onelogin/php-saml/pull/37)). This finally fixed my problem.

The issue was that ADFS posted lowercase urlencode (%2f, %2b, etc) messages, and the toolkit was rebuilding the signed message with upercase urlencode (%2F, %2B, etc). Of course, the signature did not validate. 

As others have mentioned in the cited sources, retrieveParametersFromServer set to True seems like it would be a more standard-compliant default. It would also be nice to have better documentation for this parameter. Also, since both "lowercaseUrlencoding" and "retrieveParametersFromServer" were put in for ADFS compatibility, maybe unite them?
