### ISSUE TITLE
Direct email for security issues?

### ISSUE THREAD

**Issue by danielbachhuber** [onelogin/php-saml#257]
Hello,

I help maintain [WP SAML Auth](https://github.com/pantheon-systems/wp-saml-auth) on behalf of [Pantheon](https://pantheon.io/).

One of Pantheon's clients had a security audit done of their codebase and a few minor security issues were found with this library.

Rather than [report each individually](https://www.onelogin.com/security), I'd prefer to pass along the report that was produced. Is there a direct email I can correspond with? Mine is [on my GitHub profile](https://github.com/danielbachhuber/) if you'd like to email me directly.

Thanks!

**Comment by pitbulk** [comment]
Sent you a mail.
