### ISSUE TITLE
Certificate empty variable

### ISSUE THREAD

**Issue by flysen** [onelogin/php-saml#262]
Use an array with the settings data, in the array I declare  'x509cert' => 'xxxxx' and 'privateKey' > 'nnn'.
That works without any problem until I change `authnRequestsSigned = true` in the **security array**. When I set that to **true** it throws an error:
`[2017-10-09 18:03:05] WEB.ERROR: SP Private key not found. Exception Type: OneLogin_Saml2_Error [] {"uid":"8a93698","method":"GET","route":"/saml/metadata","userId":null}`
That error are thrown from https://github.com/onelogin/php-saml/blob/6ab8488da916744d6816589ab2d0330a17c060d8/lib/Saml2/Settings.php#L604-L613

Because the cert and key are not found from the SP array in settings.php
https://github.com/onelogin/php-saml/blob/6ab8488da916744d6816589ab2d0330a17c060d8/lib/Saml2/Settings.php#L691-L701

It works if I create sp.srt and sp.key and put them in the /certs folder. Is there a way of using array instead? Could it be a problem with `$this->_sp['x509cert']`?

**Comment by pitbulk** [comment]
https://github.com/onelogin/php-saml/blob/master/settings_example.php#L66

Explained [here](https://github.com/onelogin/php-saml#certs)

**Comment by flysen** [comment]
Thanks @pitbulk for looking in to this. I think I understand the documentation regarding how to handle certificate and key for SP.
Thought I could choose to provide the SP crt and key **via array** OR **file**. The array method doesn't work using security.

Just close the ticket if it is irrelevant or don't hesitate to get back and I can try to reproduce step by step.

Brgd
Fredrik

**Comment by pitbulk** [comment]
Maybe you are not defined the value on the array properly.

When you set the value on the array, the data is loaded by [_loadSettingsFromArray](https://github.com/onelogin/php-saml/blob/6ab8488da916744d6816589ab2d0330a17c060d8/lib/Saml2/Settings.php#L237)
```
        if (isset($settings['sp'])) {
            $this->_sp = $settings['sp'];
        }
```
so when the [getSPcert](https://github.com/onelogin/php-saml/blob/6ab8488da916744d6816589ab2d0330a17c060d8/lib/Saml2/Settings.php#L687) method is called, that method should read and return the
$this->_sp['x509cert'] value, and [checkSPCerts](https://github.com/onelogin/php-saml/blob/6ab8488da916744d6816589ab2d0330a17c060d8/lib/Saml2/Settings.php#L655) should return true if also a privateKey was defined.


Can you debug your app and at [php-saml/lib/Saml2/Settings.php](https://github.com/onelogin/php-saml/blob/6ab8488da916744d6816589ab2d0330a17c060d8/lib/Saml2/Settings.php#L604-L613) try print  values of:
- $sp['x509cert']
- $sp['privateKey'].

**Comment by flysen** [comment]
My skills how php-saml are implemented into the [xibo](https://github.com/xibosignage/xibo-cms/releases/tag/1.8.2) are limited. But i works perfect expect the SP certificates in the array. Sorry I can't provide you with more detailed debug but here are some :-(

Implementation in xibo `$authentication = new \Xibo\Middleware\SAMLAuthentication();` and then the array [SAML as its authentication provider](https://xibo.org.uk/manual/en/users_saml.html).

I have it up and running with the `sp.crt` and `sp.key`  in `vendor/onelogin/php-saml/certs/`. No problem at all!

If I remove/rename `sp.crt` and `sp.key` from `vendor/onelogin/php-saml/certs/` and put the values into the array `'sp' => array` `'x509cert' => 'my cert'` and `'privateKey' > 'my key with bits=4096'` both are in one line and comments are removed.

The error when truying to login again is ~100 lines:
`
[2017-10-19 12:44:53] WEB.ERROR: Invalid array settings: sp_certs_not_found_and_required Exception Type: OneLogin_Saml2_Error [] {"uid":"ebd2658","method":"GET","route":"/login","userId":null}
[2017-10-19 12:44:53] WEB.ERROR: Invalid array settings: sp_certs_not_found_and_required Exception Type: OneLogin_Saml2_Error [] {"uid":"81b1acd","method":"GET","route":"/login","userId":null}
...
...
`
Thanks for taking time.
Brgd
Fredrik

**Comment by pitbulk** [comment]
Hi @flysen,

What version of php-saml are you using?
I noticed that xibo at Xibo is set the [2.10](https://github.com/xibosignage/xibo-cms/blob/master/composer.json#L58) version. Can you try and install the latest?

The SAML Auth object is initailized as follows:
```
$auth = new \OneLogin_Saml2_Auth($this->app->configService->samlSettings);
```

and that $samlSettings is initalized [here](https://github.com/xibosignage/xibo-cms/blob/master/lib/Service/ConfigService.php#L203).

You should add there a
```
print_r($samlSettings);
```

to see if the 'x509cert' and 'privateKey' is there... if is there means that something is wrong with the php-saml module. If is not there means that something removes its values, that you had set on the saml settings file..

P.S I created the first SAML attempt on  Xibo, but it changed a lot :)

**Comment by flysen** [comment]
Morning @pitbulk thanks for taking time.
I've added the print_r and can confirm that the `privateKey` are missing in the array:
`settings.php` (key and crt are truncated by me)
`
...
'sp' => array (
        'entityId' => 'https://diskus-demo.ub.uu.se/saml/metadata',
        'assertionConsumerService' => array (
            'url' => 'https://diskus-demo.ub.uu.se/saml/acs',
        ),
        'singleLogoutService' => array (
            'url' => 'https://diskus-demo.ub.uu.se/saml/sls',
        ),
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
        'x509cert' => 'MIIFAzCCAuugAwIBAgIJAONjaHZu0gBEMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNVBAMTFGRpc2t1cy1kZW1vLnViLnV1LnNlMB4XDTE3MTAwNTE0MTgwNVoXDTI3MTAwMzE0MTgwNVowHzEdMBsGA1UEAxMUZGlza3VzLWRlbW8udWIudXUuc2UwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC7TVocn7onWp4lnTIBFETrHkW3FWi78t/vqaRu/FodUpJFXCSjvYUKNcsX0krwA8s...',
        'privateKey' > 'MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQC7TVocn7onWp4lnTIBFETrHkW3FWi78t/vqaRu/FodUpJFXCSjvYUKNcsX0krwA8sDsZxOxQnlbyY2BE0byA/fe9bz43BDhJ30FJPFQlC+1oNJbTchYIEtr84GzxThZJ4EAh0AE7X+4NjJOsLmjUeDU5cQhVZwmvNEFA9R4LBoJaGksXYGSGIpEVu0sUmDBVjz+1Z1HL1Kyogim4mDDhIdDYIvAT5TzQyNCfRtrk+hr/L38/8mvlkEIRpipBVveQR+PaQxK1/3NGNoLaxJ4IbJvUP+iQifeL1/yR/UwBeEHRhyO+QFEvgGArFidGvlhI5XgO6O1v2tzwd5T9biIbnP1uQL...',
	'security' => array (
        	'nameIdEncrypted' => false,
       		'authnRequestsSigned' => true,
        	'logoutRequestSigned' => true,
        	'logoutResponseSigned' => true,
        	'signMetadata' => true,
        	'wantMessagesSigned' => false,
        	'wantAssertionsSigned' => false,
        	'wantAssertionsEncrypted' => false,
        	'wantNameIdEncrypted' => false,
    ),
    'contactPerson' => array (
...
`
Output from the array:
`
[sp] => Array
        (
            [entityId] => https://diskus-demo.ub.uu.se/saml/metadata
            [assertionConsumerService] => Array
                (
                    [url] => https://diskus-demo.ub.uu.se/saml/acs
                )

            [singleLogoutService] => Array
                (
                    [url] => https://diskus-demo.ub.uu.se/saml/sls
                )

            [NameIDFormat] => urn:oasis:names:tc:SAML:2.0:nameid-format:transient
            [x509cert] => MIIFAzCCAuugAwIBAgIJAONjaHZu0gBEMA0GCSqGSIb3DQEB...
            [0] => 1
        )

    [security] => Array
        (
            [nameIdEncrypted] => 
            [authnRequestsSigned] => 1
            [logoutRequestSigned] => 1
            [logoutResponseSigned] => 1
            [signMetadata] => 1
            [wantMessagesSigned] => 
            [wantAssertionsSigned] => 
            [wantAssertionsEncrypted] => 
            [wantNameIdEncrypted] => 
        )

    [contactPerson] => Array
`
The **privateKey** are missing.

I'll try to upgrade to latest `php-saml-2.11.0`, xibo using `v.2.10.2` today. I'm not sure how to upgrade but I give it a try.

Regards
Fredrik

**Comment by flysen** [comment]
Upgraded to latest `php-saml-2.11.0` (copy the directory). The result is the same as above.
/Fredrik

**Comment by pitbulk** [comment]
Since the PrivateKey is not there, it seems there is some issue on the Xibo implementation, is not related to the php-saml toolkit.

If you defined the PrivateKey properly on the settings and is not there when you use it to build the Auth object, that means that Xibo made something to it..

**Comment by flysen** [comment]
Thanks, moving the question to xibo.
cheers
Fredrik

**Comment by flysen** [comment]
@pitbulk sorry for this, but here is the problem:
`'privateKey' > 'MIIJQQIBADANBgkq` should be `'privateKey' => 'MIIJQQIBADANBgkq`

Feel really bad for taking your time. Thanks for all support!
Fredrik
