### ISSUE TITLE
Metadata expiration (validUntil) timestamp

### ISSUE THREAD

**Issue by juanpscotto** [onelogin/php-saml#265]
How to change the validUltil timestamp generated for the metadata ??

**Comment by pitbulk** [comment]
The [getSPMetadata](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L802) method does not accept parameters, you will need to use directly the Metadata [builder](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L26) and provide validUntil and cacheDuration values.

**Comment by whatch** [comment]
I don't see any way to provide these parameters to the build tool? Is this something we can just edit by hand and not worry about?

**Comment by pitbulk** [comment]
On the [view](https://github.com/onelogin/php-saml/blob/master/demo1/metadata.php#L16) that generates the metadata, you only need to extend the [getSPMetadata](https://github.com/onelogin/php-saml/blob/master/demo1/metadata.php#L16) method.
