### ISSUE TITLE
Missing attributes returned when using  $auth->getAttributes();

### ISSUE THREAD

**Issue by PierreTrp** [onelogin/php-saml#274]
I used your "demo1" files to try to login/logout on my app and it works.

But on your doc, you say that `$attributes = $auth->getAttributes();` return 

```
Array
(
    [cn] => Array
        (
            [0] => John
        )
    [sn] => Array
        (
            [0] => Doe
        )
    [mail] => Array
        (
            [0] => john.doe@example.com
        )
    [groups] => Array
        (
            [0] => users
            [1] => members
        )
)
```

It doesn't.

I need to know in which group the user is, or at least which role he have but the only thing i get is 

```
array(4) {
  ["samlUserdata"]=>
  array(5) {
    ["memberOf"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
    ["PersonImmutableID"]=>
    array(1) {
      [0]=>
      string(0) ""
    }
    ["User.LastName"]=>
    array(1) {
      [0]=>
      string(2) "xxx"
    }
    ["User.email"]=>
    array(1) {
      [0]=>
      string(17) "xxx"
    }
    ["User.FirstName"]=>
    array(1) {
      [0]=>
      string(3) "xxx"
    }
  }
  ["samlNameId"]=>
  string(17) "xxx"
  ["samlNameIdFormat"]=>
  string(54) "xxx"
  ["samlSessionIndex"]=>
  string(37) "_xxx"
}
```

How am i suppose to get groups/roles and other important user info on login...?

**Comment by pitbulk** [comment]
getAttributes method read the data available from the Assertion of the SAMLResponse sent by the Identity Provider.

If IdP is not sending the data that you need in your SP, you will need to configure it properly.

What you see on demo1 example is that, an example.

**Comment by PierreTrp** [comment]
Alright thanks
