### ISSUE TITLE
Since PHP 7.2 the mcrypt extension doesn't exists anymore

### ISSUE THREAD

**Issue by ruben-haegeman** [onelogin/php-saml#278]
Since PHP 7.2 the mcrypt extension isn't released anymore since it was deprecated for 7.1

The composer.json file does allow it to be installed with PHP 7.2. An upgrade should be made to the library to move away from mcrypt.

**Comment by pitbulk** [comment]
See https://github.com/onelogin/php-saml/issues/255

**Comment by arc92** [comment]
Any solution for windows servers or Xampp?

**Comment by Vadik19950103** [comment]
I want install mcrypt on windows xamp server
please help me

**Comment by khadev** [comment]
hi

1-First, you should download the suitable version for your system from here:
 https://pecl.php.net/package/mcrypt/1.0.3/windows

2-Later, you should copy php_mcrypt.dll under ../xampp/php/ext/ 

3-you should enable extension like extension=mcrypt from xampp/php/php.ini

personly i modified the php.ini file and i add this line :

extension=imap
extension=mcrypt
 
of course these two lines has the 3 dll file saved on ../xampp/php/ext/  as :

php_imap.dll
php_mcrypt.dll

**Comment by Kirti003Shukla** [comment]
> hi
> 
> 1-First, you should download the suitable version for your system from here:
> https://pecl.php.net/package/mcrypt/1.0.3/windows
> 
> 2-Later, you should copy php_mcrypt.dll under ../xampp/php/ext/
> 
> 3-you should enable extension like extension=mcrypt from xampp/php/php.ini
> 
> personly I modified the php.ini file and i add this lines :
> 
> extension=imap
> extension=mcrypt
> 
> of course, these two lines have the 3 dll file saved on ../xampp/php/ext/ as :
> 
> php_imap.dll
> php_mcrypt.dll

I am not able to resolve my problem, so posting over closed issue. I followed the same procedure but now I am receiving an error as whoops something went wrong. Please let me know how to resolve the issue.
php 7.3.16
installed this
php_mcrypt-1.0.3-7.3-ts-vc15-x64.zip
updated php.ini as
 extension=mcrypt
xampp v3.2.4

**Comment by mohamadRaafatKamel** [comment]
> hi
> 
> 1-First, you should download the suitable version for your system from here:
> https://pecl.php.net/package/mcrypt/1.0.3/windows
> 
> 2-Later, you should copy php_mcrypt.dll under ../xampp/php/ext/
> 
> 3-you should enable extension like extension=mcrypt from xampp/php/php.ini
> 
> personly I modified the php.ini file and i add this lines :
> 
> extension=imap
> extension=mcrypt
> 
> of course, these two lines have the 3 dll file saved on ../xampp/php/ext/ as :
> 
> php_imap.dll
> php_mcrypt.dll


Thanks it work

**Comment by jain-priyal** [comment]
> > hi
> > 1-First, you should download the suitable version for your system from here:
> > https://pecl.php.net/package/mcrypt/1.0.3/windows
> > 2-Later, you should copy php_mcrypt.dll under ../xampp/php/ext/
> > 3-you should enable extension like extension=mcrypt from xampp/php/php.ini
> > personly I modified the php.ini file and i add this lines :
> > extension=imap
> > extension=mcrypt
> > of course, these two lines have the 3 dll file saved on ../xampp/php/ext/ as :
> > php_imap.dll
> > php_mcrypt.dll
> 
> I am not able to resolve my problem, so posting over closed issue. I followed the same procedure but now I am receiving an error as whoops something went wrong. Please let me know how to resolve the issue.
> php 7.3.16
> installed this
> php_mcrypt-1.0.3-7.3-ts-vc15-x64.zip
> updated php.ini as
> extension=mcrypt
> xampp v3.2.4

Facing same issue. How did you resolve this?
php 7.3.12
used php_mcrypt-1.0.3-7.3-ts-vc15-x64.zip
updated php.ini with
extension=php_mcrypt.dll
wamp 3.2.0
restarted all wamp services
php_mcrypt is showing in the extensions list. But when I try to run 'php artisan migrate' I still get 
error saying "Mcrypt PHP extension required."

**Comment by brymacha** [comment]
Hello,
~you should download the suitable version for your system from here:
https://pecl.php.net/package/mcrypt/1.0.3/windows
~Extract and paste php_mcrypt.dll in /xampp/php/ext/ folder
~Edit php.ini file in /xampp/php/ by adding the line:
extension=php_mcrypt.dll

~Restart apache, its done.

**Comment by ahtshambhatti** [comment]
> hi
> 
> 1-First, you should download the suitable version for your system from here:
> https://pecl.php.net/package/mcrypt/1.0.3/windows
> 
> 2-Later, you should copy php_mcrypt.dll under ../xampp/php/ext/
> 
> 3-you should enable extension like extension=mcrypt from xampp/php/php.ini
> 
> personly I modified the php.ini file and i add this lines :
> 
> extension=imap
> extension=mcrypt
> 
> of course, these two lines have the 3 dll file saved on ../xampp/php/ext/ as :
> 
> php_imap.dll
> php_mcrypt.dll

Thanks It worked... 💯

**Comment by faysalcse28** [comment]
of course, these two lines have the 3 dll file
Which 3 dll?

**Comment by kabircse** [comment]
Take this file from here,
https://windows.php.net/downloads/pecl/releases/mcrypt/
