### ISSUE TITLE
Support for FriendlyName mapping for getAttributes

### ISSUE THREAD

**Issue by crazytonyi** [onelogin/php-saml#281]
Currently, `OneLogin_Saml2_Response::getAttributes()` maps the `AttributeStatement` of a response against the `Name` attribute of the `Attribute` element. Many IdPs set the `Name` attribute of the `Attribute` elements to the `urn:oid` URN (usually based on x500 or x520 LDAP attribute names). It could be useful, since OneLogin is already right there in the XML of the `Attribute` to check for a `FriendlyName` attribute as well and map the the attributes against that `FriendlyName` as well. Something like:

        foreach ($entries as $entry) {
            $attributeName = $entry->attributes->getNamedItem('Name')->nodeValue;
            if( $entry->attributes->getNamedItem('FriendlyName') ) {
                   $attributeFriendlyName = $entry->attributes->getNamedItem('FriendlyName');
            }

And then further down when setting the value:

            $attributes[$attributeName] = $attributeValues;
            if( $attributeFriendlyName ) {
                   $attributes[$attributeFriendlyName] = $attributeValues;
            }

This could make it easier for a third-party application to allow mapping of known "friendlyName" attribute names to local user attributes.

**Comment by pitbulk** [comment]
There is a PR to solve that.. I will merge it soon:
https://github.com/onelogin/php-saml/pull/270

**Comment by slaughter550** [comment]
@pitbulk are you planing on merging #270 soon? Could really use it for a project my company is working on

**Comment by pitbulk** [comment]
It was merged
