### ISSUE TITLE
Wrong return type in phpdoc for getSessionExpiration

### ISSUE THREAD

**Issue by Voziv** [onelogin/php-saml#287]
In [`OneLogin_Saml2_Auth` on line 397](https://github.com/onelogin/php-saml/blob/3.0.0/lib/Saml2/Auth.php#L397) stats that the return value will be `DateTime|null` however checking [where the property `_sessionExpiration` is set](https://github.com/onelogin/php-saml/blob/3.0.0/lib/Saml2/Auth.php#L211) it actually gets set as an `int`.

----

I'll make a quick PR changing it from DateTime to int to be consistent with what's being returned currently.

**Comment by Voziv** [comment]
PR #288

**Comment by stof** [comment]
Fixed in #308
