### ISSUE TITLE
how i can Install 3.0.0  with my Laravel-saml2 Package

### ISSUE THREAD

**Issue by techmatevaibhav** [onelogin/php-saml#289]
When i run composer install again its install with v2.12.
how i can use 3.0.0 branch.

i am using **https://github.com/aacotroneo/laravel-saml2**
 package and v2.12.0 is the dependency of this.

**Comment by pitbulk** [comment]
You will need to modify laravel-saml2 composer file.

**Comment by techmatevaibhav** [comment]
Yes but that folder also in vendor so any other way we can directly change. Without any vendor folder file change ?
