### ISSUE TITLE
only http-post supported? 

### ISSUE THREAD

**Issue by awm086** [onelogin/php-saml#290]
My idp provided me with the saml metadata including the following.:
```
   <md:SingleSignOnService Location="[someURL]" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"/>
        <md:SingleSignOnService Location="[SOMEURL]" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"/>
```
 I have everything set up through an interface that work with this package. so far but when I try to use it I get an error saying that only http-post is  supported. Normally using the standard samlephp library 2 SingleSignOnService would be configured with their bindings. like 

```
'SingleSignOnService' => array(
        0 => array(
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
          'Location' => 'SOMEURL',
        ),
        1 => array(
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'SOMEURL',
        ),
      ),

```
 I am not sure how to accomplish that with php-saml. I looked at the readme and saw the only http-post is supported but further down I saw that http-redirect is also supported. I am no expert with saml and I am not sure if this is an issue with my config or it's a limitation of this package.

**Comment by pitbulk** [comment]
php-saml uses HTTP-Redirect for all except receiving SAMLResponse on SSO process where a HTTP-POST is required.

If your IdP supports HTTP-Redirect and HTTP-POST for the SingleSignOnService... just put the HTTP-Redirect on the settings.
```
singleSignOnService' => array (
            // URL Target of the IdP where the Authentication Request Message
            // will be sent.
            'url' => 'SOMEURL',
            // SAML protocol binding to be used when returning the <Response>
            // message. OneLogin Toolkit supports the HTTP-Redirect binding
            // only for this endpoint.
            'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        ),
```

**Comment by awm086** [comment]
Thanks for the quick response. I am not sure why was this happening. I am using pingidentity for idp, and I asked them to change the ACS url from http:url to https:url thinking this may be causing a redirect which results in the "http post only" error. This resulted in getting the following error. 
```
RuntimeException encountered while processing SAML authentication response: Error(s) encountered during processing of ACS response. Type(s): invalid_response; reason given for last error: The response was received at http://[DOMAIN]/saml/acs instead of https://[Domain]saml/acs in Drupal\samlauth\SamlService->acs() (line 151 of /app/web/modules/contrib/samlauth/src/SamlService.php).
```

**Comment by pitbulk** [comment]
Is the service under some proxy/load balancer?

Then review this: https://github.com/onelogin/php-saml#working-behind-load-balancer

**Comment by awm086** [comment]
yes, probably due ssl offloading. Any helpful resources you know of?

**Comment by pitbulk** [comment]
setProxyVars(true)
