### ISSUE TITLE
PHP 7.2 deprecated string assertions

### ISSUE THREAD

**Issue by francislavoie** [onelogin/php-saml#291]
Example:
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L441

See http://php.net/manual/en/function.assert.php 
>Warning: Using string as the assertion is DEPRECATED as of PHP 7.2.

These all need to be updated to be compatible with 7.2

**Comment by pitbulk** [comment]
Duplicated issue.

Follow the original: https://github.com/onelogin/php-saml/issues/255

**Comment by francislavoie** [comment]
I wouldn't really say this is a duplicate. This is a completely separate
compatibility issue.

**Comment by pitbulk** [comment]
Well, not duplicate issue but at the end, the fact is that PHP7.2 is incompatible with the php-saml 2.X branch for several reasons (mcrypt, asserts,...)
You can see how in the [3.0.0 branch](https://github.com/onelogin/php-saml/blob/3.0.0/lib/Saml2/Utils.php#L65) assertion stuff was already handled. And it pass [Travis CI on PHP 7.2](https://github.com/onelogin/php-saml/blob/3.0.0/.travis.yml#L8).

Once namespaces are implemented we gonna be ready for officially release the 3.0.0 version.

**Comment by francislavoie** [comment]
Ah, okay thanks for clarifying
