### ISSUE TITLE
Getting "Signature validation failed. SAML Response rejected"

### ISSUE THREAD

**Issue by simonattr** [onelogin/php-saml#292]
I have tried to validate the response using https://www.samltool.com/validate_response.php
and get the message "Assertion signature validation failed."

There is no KeyInfo element in the response, is this element required?

Thanks in advance, please let me know if you require any additional information.

**Comment by simonattr** [comment]
Now getting the result "the saml response is valid" when I validate the response using https://www.samltool.com/validate_response.php - looks like I was using the wrong certificate.

But still getting response "Signature validation failed. SAML Response rejected" when trying to authenticate.

**Comment by pitbulk** [comment]
samltool.com uses internally the php-saml tookit.

The error of the SAMLResponse validation seems related to the Signature validation.

There is a generic error that is what you see: "[Signature validation failed. SAML Response rejected](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L386)" but you can debug the [validateSign](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L1280) method to get the possible reason.

Another way to verify that the signature is wrong is to directly use the [xmlsec1](https://www.aleksey.com/xmlsec/) binary, executing for example:
```
xmlsec1 --verify --X509-skip-strict-checks --id-attr:ID "urn:oasis:names:tc:SAML:2.0:protocol:Response" --trusted-pem cert.crt saml_response.xml

or

xmlsec1 --verify --X509-skip-strict-checks --id-attr:ID "urn:oasis:names:tc:SAML:2.0:protocol:Assertion" --trusted-pem cert.crt saml_response.xml
```

**Comment by simonattr** [comment]
Many thanks pitbulk I wasn't aware of the validateSign method I will see what it returns.

**Comment by simonattr** [comment]
The problem has been resolved.  After getting the KeyInfo element added to the response everything is working fine.
