### ISSUE TITLE
Multiple SAML libraries may allow authentication bypass via incorrect XML canonicalization and DOM traversa

### ISSUE THREAD

**Issue by techmatevaibhav** [onelogin/php-saml#295]
Hello @pitbulk 
Hope you are doing Great.

Do you have any idea https://www.kb.cert.org/vuls/id/CHEU-AVBRX8 related this issue in php-saml packege ? 

able mentioned issue fixed in ruby-saml, pathon-saml and paython3-saml any update regarding php-saml

**Comment by pitbulk** [comment]
Not affected #293
