### ISSUE TITLE
Problem validating signature

### ISSUE THREAD

**Issue by ashwah** [onelogin/php-saml#298]
We are attempting to connect a PHP based SP with a SimpleSAMLphp IdP but we are running into bother validating the generated SAML assertion. I am not sure whether this is a fault at the IdP end, or if it something going wrong on the processing the token.

It appears to be failing at the certificate verfication stage. In www.samltool.com I also get a 'Signature validation failed. SAML Response rejected'.

We notice that the when we hit the openssl_verify() function the value that is passed to the function is different to the value in the original assertion.

For example. When debugging the function we can see the data as:

```
<ds:SignedInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
  <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <ds:Reference URI="#_61a112e3504fa3e28f8e4962dbe5c2188c2908a929">
    <ds:Transforms>
      <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    </ds:Transforms>
    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <ds:DigestValue>i8bYboPkxcMjbAJ/kh1D/XQu87U=</ds:DigestValue>
  </ds:Reference>
</ds:SignedInfo>
```

Whereas the full response (from $_POST) is:

```
<?xml version="1.0"?>
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_61a112e3504fa3e28f8e4962dbe5c2188c2908a929" Version="2.0" IssueInstant="2018-03-19T17:25:03Z" Destination="xxx/saml/consume" InResponseTo="ONELOGIN_8bd36a185c34c2515f0a1cd2485c1f1a0cb58cf1">
  <saml:Issuer>http://dev-idp.microserve-qa.io/simplesamlphp/saml2/idp/metadata.php</saml:Issuer>
  <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <ds:Reference URI="#_61a112e3504fa3e28f8e4962dbe5c2188c2908a929">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <ds:DigestValue>i8bYboPkxcMjbAJ/kh1D/XQu87U=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>
    <ds:SignatureValue>sEPMaHPE/H/f+Z9NRA4dykue4QkRMbjsrqhGkPIOfaics2ym4fFp7FilovpjxlRcC8EY3FNX+ouWKzRFFLQODVyVaObfqVP8fuWS65uagU4CFPsKkgikDp8bwDXCtTDgO4rI9rpXRj1ShwXRoAFdRZjx/phop/F/c76U+7TrdyBH7Ei2Y/2LFXIYEMTwNtMQDWC1It1g40GEv/hu63df48GXguy56t2wIF64Hj8DLWK0Y1+bFK9ne9IbuufYUJ7tsmkFsNoh7Mr34B6BkC5Ztk3DtOrxWwFYLr9uLRK9wHC/SpSoTaUPrj9ZkinnKGaeo82KwV7WdPCfe8uHpOg5Yw==</ds:SignatureValue>
    <ds:KeyInfo>
      <ds:X509Data>
        <ds:X509Certificate>###</ds:X509Certificate>
      </ds:X509Data>
    </ds:KeyInfo>
  </ds:Signature>
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </samlp:Status>
  <saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_0557fabfec5de08f4b29dabbde839057473caf02ef" Version="2.0" IssueInstant="2018-03-19T17:25:03Z">
    <saml:Issuer>xxx/simplesamlphp/saml2/idp/metadata.php</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
        <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
        <ds:Reference URI="#_0557fabfec5de08f4b29dabbde839057473caf02ef">
          <ds:Transforms>
            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
          </ds:Transforms>
          <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
          <ds:DigestValue>M5KQzoMOrbREYbLFQ5SEu6J5zWM=</ds:DigestValue>
        </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue>LejzsXKOEewsCCXXcJBcuZguqcPXW74m4liHTcpU7jiSLxXsqF49E7fJIIxeR3wWxPxLQPPA9CSyDghKRQOs3Voke49GYTRcJSU4tlYaRRlPnD51XnZLiY9IsZfh8QsAJoCfOgZ3GsS8IranJUz2s0O95fotwIWS72MYebY2ydsAwC7xi6vypWVkuEAwGMu2QrJyCVdoBzGDMKhkOY/1PtZxaH0Ot8C4AWpJ3PkusFbkax4Y7NFA/RlEBvhH39ZXzOGrAYh0up9pvHr+IUDIYCXZz8bOxvoq3JBm9wbgFfISaJE5gb+FVESx12qGq0i+pf6IKqOdVWAvIOfGtRcFGg==</ds:SignatureValue>
      <ds:KeyInfo>
        <ds:X509Data>
          <ds:X509Certificate>###</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </ds:Signature>
    <saml:Subject>
      <saml:NameID SPNameQualifier="xxx" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_9fcda110d1e4498792c8a4a8c5bab88551785452c4</saml:NameID>
      <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml:SubjectConfirmationData NotOnOrAfter="2018-03-19T17:30:03Z" Recipient="xxx/saml/consume" InResponseTo="ONELOGIN_8bd36a185c34c2515f0a1cd2485c1f1a0cb58cf1"/>
      </saml:SubjectConfirmation>
    </saml:Subject>
    <saml:Conditions NotBefore="2018-03-19T17:24:33Z" NotOnOrAfter="2018-03-19T17:30:03Z">
      <saml:AudienceRestriction>
        <saml:Audience>ab-app-local</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml:AuthnStatement AuthnInstant="2018-03-19T16:21:20Z" SessionNotOnOrAfter="2018-03-20T01:25:03Z" SessionIndex="_db82070a08db26022021ca6e42d37c2822027ace9e">
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>
  </saml:Assertion>
</samlp:Response>
```

So I notice the difference between "<ds:SignedInfo>" in the verify function, but "<ds:SignedInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">" in the original assertion. These should be the same, right? And the fact that they are different is why it's failing?

I'm trying to figure out if this is a bug with php-saml, or xmlseclibs, or just my response is wrong.

Now it's late and I'm tired...

**Comment by pitbulk** [comment]
samltool.com uses php-saml so you should have the same result trying to validate a SAMLResponse in both sides.

Can you provide the original base64 encoded version of your SAMLResponse? (any extra space on the XML is enough to invalidate it)

**Comment by ashwah** [comment]
Thanks @pitbulk for your speedy reply! Here is an encoded response, not the same one but will be the same structure: 

PHNhbWxwOlJlc3BvbnNlIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIHhtbG5zOnNhbWw9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIElEPSJfYzgxODlmNmVkYmFkZGM0YmFiMzI4YTM1Y2NkNDNmOWYwOWNhZGM1ODc3IiBWZXJzaW9uPSIyLjAiIElzc3VlSW5zdGFudD0iMjAxOC0wMy0yMFQxMDowMDo0NloiIERlc3RpbmF0aW9uPSJodHRwOi8vYWJzdWdhcmNvbW11bml0eS5kb2Nrc2FsL3NhbWwvY29uc3VtZSIgSW5SZXNwb25zZVRvPSJPTkVMT0dJTl85NGMwY2FlOGE5YmRkOTM1ZTE4NGYxNTJkYzc4Y2M3YTgzMDMxYTA1Ij48c2FtbDpJc3N1ZXI+aHR0cDovL2Rldi1pZHAubWljcm9zZXJ2ZS1xYS5pby9zaW1wbGVzYW1scGhwL3NhbWwyL2lkcC9tZXRhZGF0YS5waHA8L3NhbWw6SXNzdWVyPjxkczpTaWduYXR1cmUgeG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPgogIDxkczpTaWduZWRJbmZvPjxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+CiAgICA8ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3JzYS1zaGExIi8+CiAgPGRzOlJlZmVyZW5jZSBVUkk9IiNfYzgxODlmNmVkYmFkZGM0YmFiMzI4YTM1Y2NkNDNmOWYwOWNhZGM1ODc3Ij48ZHM6VHJhbnNmb3Jtcz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz48ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8+PC9kczpUcmFuc2Zvcm1zPjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPjxkczpEaWdlc3RWYWx1ZT51bUNnYjRuUFNNOEtVMU1teUl5ckpmbDZnZzg9PC9kczpEaWdlc3RWYWx1ZT48L2RzOlJlZmVyZW5jZT48L2RzOlNpZ25lZEluZm8+PGRzOlNpZ25hdHVyZVZhbHVlPmdVWlYyR2pINy82TWRtUHFqQk5KK2Z4cmVEWVBNSE1OUjhRS3ZlRWVKTkJJM01aUTZIVHVIL2tpeWJPN2RHaXQyZ0pzdHpVSGVZR1l6NUQrSGM0dHlUQjN3czRVQUVIc01weWUzbUg0K1ZLdUFERDRLMmpLc2Rwck42eWNQVkVEanFncnhobTkvZEYzMVBNSFcvblJ6cXpoL1VCR3FxTjNGTW81VUhIU244TGZRVmJxRzYwTktvaExicXNabHpOUEswZTVqL3hBS0tLRXJXVTVCaXZET0ZyMXJ2TkdNNWhiQkhXRWVGTnRuTVAwRzdacHhjSFREOHVWUGttNEo0emhUUFhraWtCRUdTOE1PZlFkWjBQY25MLzdSSktjelF2MFE5cGRVays0VmpkQUpYS1RPcDhlbFNpTkVlK1NQdlZmTS9GNTRySjZCQkpjV1lPczVJbFgwQT09PC9kczpTaWduYXR1cmVWYWx1ZT4KPGRzOktleUluZm8+PGRzOlg1MDlEYXRhPjxkczpYNTA5Q2VydGlmaWNhdGU+TUlJRFhUQ0NBa1dnQXdJQkFnSUpBTWVUNFlRYlB5M3RNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1FVXhDekFKQmdOVkJBWVRBa0ZWTVJNd0VRWURWUVFJREFwVGIyMWxMVk4wWVhSbE1TRXdId1lEVlFRS0RCaEpiblJsY201bGRDQlhhV1JuYVhSeklGQjBlU0JNZEdRd0hoY05NVGd3TXpFMU1UVXlOREF5V2hjTk1Ua3dNekUxTVRVeU5EQXlXakJGTVFzd0NRWURWUVFHRXdKQlZURVRNQkVHQTFVRUNBd0tVMjl0WlMxVGRHRjBaVEVoTUI4R0ExVUVDZ3dZU1c1MFpYSnVaWFFnVjJsa1oybDBjeUJRZEhrZ1RIUmtNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXdWNFBaYmkyejZGQ0hnYzl4cE9nYy9WdTFBOUV5M3BlMnNhaWs5QnRRM3pwVG5TMmxvcVZXNjViMGhRY3pCdC9ScU8rSHRFQ3ZGUHFrTlNQaUNMeGEwSUoxQ1NFaEcyTVhxaEQxbnlDNXEyRG9VdG5iOFpJOEhrUlNoL1FVaXBTeE1EeStvN0ZEQmNxM3o4OUtHSUF2VWQ3cTQwRWdGN1JwZ0I5U2doa0IzQmgrUVdpTkdxN1BjMld1UWxacnBYWWVwYVExVkt2Ynl6dUpTYmYydVlEL3lWZHdLblRwZlp5c2hadUpESmpjdjdnQzRCR2txVDFsN2hwcWZQZGQ2SnVrR0FSSlI1enFFWnZzZ2RlSE5DMVpFSkRvdEtOMS9oN2lKU2JTTzkxOG16cVFnWW1qdmRQZUFJOTVLNG5XYjJJMnB5SlFyRGZTM0VoMGFadk1EYmJnd0lEQVFBQm8xQXdUakFkQmdOVkhRNEVGZ1FVV0pJRWNZN0JhYzU4MXh2NzlnRnMzdEUxS2RZd0h3WURWUjBqQkJnd0ZvQVVXSklFY1k3QmFjNTgxeHY3OWdGczN0RTFLZFl3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFITXRSNVowSmpmSWErZGFNLzNxaXFLS2lrN0hRSGh3SW5xVkdiWXZrSXQyVmRIQUJSM1VXWFJsY2FoakY2MnRucFBMRWZSWm4zMEt1aFQyaDE2RDZOZGxnbW1kOFNGOTkvUXMrRVZ1dHJibnNiVGRpTTJBNGM4NzUvSWM2b3FyZ0tmVm8wVlJ1VjQ1QlMvdlFyV3ovVXpGVU1UOGpoWDRIZ1VhbUlLaDNLLzhSN3RNbVRkRkhya3RydVJYaG9nbmNZdWFBNXNwSFNBZEE1U2IyaG4vZnpna3NGTGc5YUFoMHVKbnU1bFlCdTJJbjQ1TlJjdWpPbHpmSGZpTEJYZUJjanZ3Qk53cmtqblQzcmd4YTlvbWJGYjlxQ1ZQN244UWhkVjEwazFudTQ3ZHBqUGptdHdEY2U5WHVWVWJzWkdpNkhKQkJHdm56OWxxaWFwRkFUZTlPcXc9PTwvZHM6WDUwOUNlcnRpZmljYXRlPjwvZHM6WDUwOURhdGE+PC9kczpLZXlJbmZvPjwvZHM6U2lnbmF0dXJlPjxzYW1scDpTdGF0dXM+PHNhbWxwOlN0YXR1c0NvZGUgVmFsdWU9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDpzdGF0dXM6U3VjY2VzcyIvPjwvc2FtbHA6U3RhdHVzPjxzYW1sOkFzc2VydGlvbiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4bWxuczp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIElEPSJfNTk4MzBlNGJmYTA4YzY1OTdiMzBjYmRiNTMwZDQ1NDY3MWMwZDI2NDVjIiBWZXJzaW9uPSIyLjAiIElzc3VlSW5zdGFudD0iMjAxOC0wMy0yMFQxMDowMDo0NloiPjxzYW1sOklzc3Vlcj5odHRwOi8vZGV2LWlkcC5taWNyb3NlcnZlLXFhLmlvL3NpbXBsZXNhbWxwaHAvc2FtbDIvaWRwL21ldGFkYXRhLnBocDwvc2FtbDpJc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+CiAgPGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz4KICAgIDxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjcnNhLXNoYTEiLz4KICA8ZHM6UmVmZXJlbmNlIFVSST0iI181OTgzMGU0YmZhMDhjNjU5N2IzMGNiZGI1MzBkNDU0NjcxYzBkMjY0NWMiPjxkczpUcmFuc2Zvcm1zPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48L2RzOlRyYW5zZm9ybXM+PGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIi8+PGRzOkRpZ2VzdFZhbHVlPkVUL3hsckdNR3A3Y29oRFRJSThld3NwMVUwdz08L2RzOkRpZ2VzdFZhbHVlPjwvZHM6UmVmZXJlbmNlPjwvZHM6U2lnbmVkSW5mbz48ZHM6U2lnbmF0dXJlVmFsdWU+cWt0OGkxRjRrM0lUQ0lLNFVjR3dsc3dZdGwvTi81RXNidm85UE44SXRCUzRhakwxK2dZTXFUL1FvSHZaT0FtODVldVFSUzZZUmMyVW9JNlpLTFhtSFViTy80SkVMOVI2aCtURnRucVZVbk1tbkxPVzVlbXdEcExIekxVV1BreXB3czVjN3U4cWFQcWxJVHZRa2d4UXpQU0t0amRMMFJTZkwxQlpFWDU2SHo4ZkxlYVltcEdQM2F5RXlkUFlOeXROUVFmN0xtTlZORXFJdDVmM2ZxaHFjTC9VblZFYW82YWtCWUhsaHpRQzdxS1hTMCtFc0ZJMGlYLytkS0drY2swMzlQK1kyM0NPbkpvZCtyWDdzWHMzd1p3Vnh0eDBuZXJCaFQ1NS8wbVlad05uRmEyeFNYdkR6cGQ4dFNaM1JUcUtMOEY0ajFHYkVRaDNFZUxacldCUWRRPT08L2RzOlNpZ25hdHVyZVZhbHVlPgo8ZHM6S2V5SW5mbz48ZHM6WDUwOURhdGE+PGRzOlg1MDlDZXJ0aWZpY2F0ZT5NSUlEWFRDQ0FrV2dBd0lCQWdJSkFNZVQ0WVFiUHkzdE1BMEdDU3FHU0liM0RRRUJDd1VBTUVVeEN6QUpCZ05WQkFZVEFrRlZNUk13RVFZRFZRUUlEQXBUYjIxbExWTjBZWFJsTVNFd0h3WURWUVFLREJoSmJuUmxjbTVsZENCWGFXUm5hWFJ6SUZCMGVTQk1kR1F3SGhjTk1UZ3dNekUxTVRVeU5EQXlXaGNOTVRrd016RTFNVFV5TkRBeVdqQkZNUXN3Q1FZRFZRUUdFd0pCVlRFVE1CRUdBMVVFQ0F3S1UyOXRaUzFUZEdGMFpURWhNQjhHQTFVRUNnd1lTVzUwWlhKdVpYUWdWMmxrWjJsMGN5QlFkSGtnVEhSa01JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd1Y0UFpiaTJ6NkZDSGdjOXhwT2djL1Z1MUE5RXkzcGUyc2FpazlCdFEzenBUblMybG9xVlc2NWIwaFFjekJ0L1JxTytIdEVDdkZQcWtOU1BpQ0x4YTBJSjFDU0VoRzJNWHFoRDFueUM1cTJEb1V0bmI4Wkk4SGtSU2gvUVVpcFN4TUR5K283RkRCY3Ezejg5S0dJQXZVZDdxNDBFZ0Y3UnBnQjlTZ2hrQjNCaCtRV2lOR3E3UGMyV3VRbFpycFhZZXBhUTFWS3ZieXp1SlNiZjJ1WUQveVZkd0tuVHBmWnlzaFp1SkRKamN2N2dDNEJHa3FUMWw3aHBxZlBkZDZKdWtHQVJKUjV6cUVadnNnZGVITkMxWkVKRG90S04xL2g3aUpTYlNPOTE4bXpxUWdZbWp2ZFBlQUk5NUs0bldiMkkycHlKUXJEZlMzRWgwYVp2TURiYmd3SURBUUFCbzFBd1RqQWRCZ05WSFE0RUZnUVVXSklFY1k3QmFjNTgxeHY3OWdGczN0RTFLZFl3SHdZRFZSMGpCQmd3Rm9BVVdKSUVjWTdCYWM1ODF4djc5Z0ZzM3RFMUtkWXdEQVlEVlIwVEJBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUhNdFI1WjBKamZJYStkYU0vM3FpcUtLaWs3SFFIaHdJbnFWR2JZdmtJdDJWZEhBQlIzVVdYUmxjYWhqRjYydG5wUExFZlJabjMwS3VoVDJoMTZENk5kbGdtbWQ4U0Y5OS9RcytFVnV0cmJuc2JUZGlNMkE0Yzg3NS9JYzZvcXJnS2ZWbzBWUnVWNDVCUy92UXJXei9VekZVTVQ4amhYNEhnVWFtSUtoM0svOFI3dE1tVGRGSHJrdHJ1Ulhob2duY1l1YUE1c3BIU0FkQTVTYjJobi9memdrc0ZMZzlhQWgwdUpudTVsWUJ1MkluNDVOUmN1ak9semZIZmlMQlhlQmNqdndCTndya2puVDNyZ3hhOW9tYkZiOXFDVlA3bjhRaGRWMTBrMW51NDdkcGpQam10d0RjZTlYdVZVYnNaR2k2SEpCQkd2bno5bHFpYXBGQVRlOU9xdz09PC9kczpYNTA5Q2VydGlmaWNhdGU+PC9kczpYNTA5RGF0YT48L2RzOktleUluZm8+PC9kczpTaWduYXR1cmU+PHNhbWw6U3ViamVjdD48c2FtbDpOYW1lSUQgU1BOYW1lUXVhbGlmaWVyPSJhYi1hcHAtbG9jYWwiIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6dHJhbnNpZW50Ij5fY2VjOTZlZmUyYTRkNjg0YWY3ZTRkZDc5ODQ3ZWVmMzk3OTUzMjk2YjQ0PC9zYW1sOk5hbWVJRD48c2FtbDpTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+PHNhbWw6U3ViamVjdENvbmZpcm1hdGlvbkRhdGEgTm90T25PckFmdGVyPSIyMDE4LTAzLTIwVDEwOjA1OjQ2WiIgUmVjaXBpZW50PSJodHRwOi8vYWJzdWdhcmNvbW11bml0eS5kb2Nrc2FsL3NhbWwvY29uc3VtZSIgSW5SZXNwb25zZVRvPSJPTkVMT0dJTl85NGMwY2FlOGE5YmRkOTM1ZTE4NGYxNTJkYzc4Y2M3YTgzMDMxYTA1Ii8+PC9zYW1sOlN1YmplY3RDb25maXJtYXRpb24+PC9zYW1sOlN1YmplY3Q+PHNhbWw6Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMTgtMDMtMjBUMTA6MDA6MTZaIiBOb3RPbk9yQWZ0ZXI9IjIwMTgtMDMtMjBUMTA6MDU6NDZaIj48c2FtbDpBdWRpZW5jZVJlc3RyaWN0aW9uPjxzYW1sOkF1ZGllbmNlPmFiLWFwcC1sb2NhbDwvc2FtbDpBdWRpZW5jZT48L3NhbWw6QXVkaWVuY2VSZXN0cmljdGlvbj48L3NhbWw6Q29uZGl0aW9ucz48c2FtbDpBdXRoblN0YXRlbWVudCBBdXRobkluc3RhbnQ9IjIwMTgtMDMtMjBUMTA6MDA6NDZaIiBTZXNzaW9uTm90T25PckFmdGVyPSIyMDE4LTAzLTIwVDE4OjAwOjQ2WiIgU2Vzc2lvbkluZGV4PSJfY2NmYzVlYTg1NzczOTBhMWU1M2Q3ZjBiMzBlYjVmMjUxMDc3OTExZTAxIj48c2FtbDpBdXRobkNvbnRleHQ+PHNhbWw6QXV0aG5Db250ZXh0Q2xhc3NSZWY+dXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFjOmNsYXNzZXM6UGFzc3dvcmQ8L3NhbWw6QXV0aG5Db250ZXh0Q2xhc3NSZWY+PC9zYW1sOkF1dGhuQ29udGV4dD48L3NhbWw6QXV0aG5TdGF0ZW1lbnQ+PC9zYW1sOkFzc2VydGlvbj48L3NhbWxwOlJlc3BvbnNlPg==

**Comment by ashwah** [comment]
OK I have figured out that my config was incorrect :(

I was only able to do this because of the wealth of old issues in the channel. Thank you so much for providing this resource.

My solution was to ensure that within the app (SP) I had the IdP's certificate as well as the SP's own. The following example settings file illustrated that both cert need to be available to php-saml. https://github.com/onelogin/php-saml/blob/master/settings_example.php#L93

Thanks again :)
