### ISSUE TITLE
IdP setup

### ISSUE THREAD

**Issue by moremau** [onelogin/php-saml#301]
Sorry, 
I do not understand how:
"IdP setup
Once the SP is configured, the metadata of the SP is published at the metadata.php file. Configure the IdP based on that information."

The SP metadata has information about SP, how do I do the SP metadata get information for IdP?

**Comment by pitbulk** [comment]
What IdP are you using?

**Comment by moremau** [comment]
Ciao, sto seguendo questa guida di AdID:
Ho registrato il mio SP tramite l'interfaccia di backoffice disponibile all'indirizzo https://idp.spid.gov.it:8080. Ho inserito I dati dell'IDP scaricati tramite relativo metadata da https://idp.spid.gov.it:8080/#/infoidp ma non riesco a fare la chimata ottengo sempre il seguente errore:
"Error when processing the authentication request"

**Comment by pitbulk** [comment]
You will need to register the SP metadata [here](https://idp.spid.gov.it:8080/#/services)
and add to the SP SAML settings:
```
'idp' => array (
        'entityId' => 'https://idp.spid.gov.it',
        'singleSignOnService' => array (
            'url' => 'https://idp.spid.gov.it/samlsso',
        ),
        'singleLogoutService' => array (
            'url' => 'https://idp.spid.gov.it/samlsso',
        ),
        'x509cert' => 'MIICNTCCAZ6gAwIBAgIES343gjANBgkqhkiG9w0BAQUFADBVMQswCQYDVQQGEwJVUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDTALBgNVBAoMBFdTTzIxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0xMDAyMTkwNzAyMjZaFw0zNTAyMTMwNzAyMjZaMFUxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJDQTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzENMAsGA1UECgwEV1NPMjESMBAGA1UEAwwJbG9jYWxob3N0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUp/oV1vWc8/TkQSiAvTousMzOM4asB2iltr2QKozni5aVFu818MpOLZIr8LMnTzWllJvvaA5RAAdpbECb+48FjbBe0hseUdN5HpwvnH/DW8ZccGvk53I6Orq7hLCv1ZHtuOCokghz/ATrhyPq+QktMfXnRS4HrKGJTzxaCcU7OQIDAQABoxIwEDAOBgNVHQ8BAf8EBAMCBPAwDQYJKoZIhvcNAQEFBQADgYEAW5wPR7cr1LAdq+IrR44iQlRG5ITCZXY9hI0PygLP2rHANh+PYfTmxbuOnykNGyhM6FjFLbW2uZHQTY1jMrPprjOrmyK5sjJRO4d1DeGHT/YnIjs9JogRKv4XHECwLtIVdAbIdWHEtVZJyMSktcyysFcvuhPQK8Qc/E/Wq8uHSCo=',
    ),
```

P.S1 github Issues should be used to report bugs or malfunction of the php-saml library, no doubts about SAML integrations. 
P.S2 IdP data published at: https://idp.spid.gov.it:8080/assets/idp-metadata.xml
