### ISSUE TITLE
Dead code in \OneLogin\Saml2\Settings

### ISSUE THREAD

**Issue by stof** [onelogin/php-saml#306]
The \OneLogin\Saml2\Settings accepts settings as `array|object|null` according to the phpdoc: https://github.com/onelogin/php-saml/blob/ea70c2b11d98cf69f4b8574011b41b7984547f1c/src/Saml2/Settings.php#L117-L123

However, the implementation tells a different story:

- there is an instanceof check for a non-existent class `\Settings`, so everything in this block is dead code
- passing an object will trigger an error saying `Invalid array settings:`

https://github.com/onelogin/php-saml/blob/ea70c2b11d98cf69f4b8574011b41b7984547f1c/src/Saml2/Settings.php#L133-L162

this refers to the 3.0 branch of the repo

**Comment by pitbulk** [comment]
Nice catch, that part of code was for supporting the old Saml Settings class.

**Comment by stof** [comment]
Passing an object is totally unsupported now ?

**Comment by pitbulk** [comment]
Yes, previously we supported to parse a Saml/Settings object so old builds with old settings could just provide the Settings object to the Saml2/Settings object to construct it. 
But since Saml classes were removed, we don't need to take care of it on Saml2/Auth / Saml2/Settings.
