### ISSUE TITLE
Error returned from online SAML tool

### ISSUE THREAD

**Issue by mikevbaker** [onelogin/php-saml#317]
Hi all,

I'm not sure this is the right place for this issue. I'm getting an error when I try to use the (php) online saml tool. I actually found two tools, one works and the other one doesn't when using the same values. 

When I use the tool located at https://www.samltool.com/sp_metadata.php and fill it in with these values...
entityID : http://localhost:8080/sso/G87RO........sidl
Attribute consumer : http://localhost:8080/sso/acs
Logout service : http://localhost:8080/sso/logout
x.509 :
-----BEGIN CERTIFICATE-----
MIICjDCCAfWgA....
....wFOFN1X+k9gnBbdvVV1lik4wY=
-----END CERTIFICATE-----
I'm using the localhost values because that's where I'm testing while I wait for the actual ones from another department. I generated the private key and cert values using the online tool https://www.samltool.com/self_signed_certs.php.
I get the error INVALID ARRAY SETTINGS: IDP_CERT_OR_FINGERPRINT_NOT_FOUND_AND_REQUIRED. I have tried also providing the private key and x.509 cert at the bottom of the form but still get the same result. I don't see a place on the form for an IDP cert or a fingerprint.
The other tool I found is at https://developers.onelogin.com/saml/online-tools/build-metadata/sp. Using that tool and the exact same values I'm able to get the SAML metadata just fine. I'm trying to document this for the future. I found this other tool in the documentation. Can someone tell me if this form is actually broken or is this user error? What's missing that I need to provide?

TIA, Mike

**Comment by pitbulk** [comment]
Hi @mikevbaker,

thanks for reporting that. It seems is a bug introduced recently. I will fix asap.

**Comment by pitbulk** [comment]
@mikevbaker the bug was fixed.

**Comment by mikevbaker** [comment]
Thanks!
