### ISSUE TITLE
Single Logout failure in destination check...

### ISSUE THREAD

**Issue by jenelso2** [onelogin/php-saml#319]
Hello,

I'm working on a Shibboleth project and I'm having a problem getting single logout to work against the SP using OneLogin.  In the /lib/Saml2/LogoutRequest.php file on line 358 it compares destination to currentURL and throws the WRONG_DESTINATION error.  The $currentURL variable is a very long URL with a SAMLRequest parameter, while the destination attribute in the XML is the same URL without the SAMLRequest parameter. I believe that the order of arguments in the strpos() check are backwards in this code, as the strpos() function is haystack,needle - not needle,haystack.  If I switch them around, single logout works fine.

If I'm incorrect here, please let me know.

Thanks,

-Jeremy

**Comment by pitbulk** [comment]
Do you have a PR?

**Comment by jenelso2** [comment]
I do not have a Pull Request.

**Comment by pitbulk** [comment]
I mean [Pull Request](https://help.github.com/articles/about-pull-requests/), The code you changed to make it work.

**Comment by jenelso2** [comment]
I didn't create a Pull Request for this code change, I just changed it manually on my server to see if it worked.  Would you like me to create a fork and pull request for this?

**Comment by jenelso2** [comment]
I didn't create a PR for this, I just changed it on my server to see if it works.  Would you like me to create a branch or fork and pull request?

Thanks.

**Comment by pitbulk** [comment]
Yes please

**Comment by jenelso2** [comment]
Pull Request created.  https://github.com/onelogin/php-saml/pull/320

Thanks.
