### ISSUE TITLE
Non http(s) redirects should be allowed

### ISSUE THREAD

**Issue by gitnik** [onelogin/php-saml#322]
As per this line https://github.com/onelogin/php-saml/blob/3.0.0/src/Saml2/Utils.php#L289, only http(s) URLs are allowed to be redirected to. IMO this is not something the library should take care of, especially considering the URL is checked for general valitidy one line afterwards. 

For our exact use case, we want to redirect to `mibrowsers://<url>` instead of `https://<url>`, so that we can make use of [this](https://www.mobileiron.com/en/endpoint-security/secure-workspace). Again, IMO the use case doesn't even matter, the library should not care about the protocol in general. Or at the very least this check should be configurable. What's your view on this?

**Comment by pitbulk** [comment]
The FILTER_VALIDATE_URL consider an URL without protocol as valid, that why we validate the protocol previously.

You can provide a PR that modify the regex to add the 'mibrowsers' as a valid protocol.

**Comment by gitnik** [comment]
I don't think that a very scalable approach. Then someone else will need to add another protocol in a couple of months.

I think for a tightly controlled environment the package should allow skipping the check altogether. What about adding another parameter for this?

**Comment by pitbulk** [comment]
The toolkit has several years is that is the first petition.

I don't want to add a new setting parameter.

What about adding a new parameter to the Utils class: allowed_redirect_protocols
by default http and https, and a way to modify it programarically?

**Comment by gitnik** [comment]
I've created a small pull request :)
