### ISSUE TITLE
Is there any customizations required for it to work with tikiwiki?

### ISSUE THREAD

**Issue by bithya** [onelogin/php-saml#326]
Hello all, 
We are trying to create saml sso from tikiwiki to onelogin cloud using onelogin/php-saml. Although the saml trace shows it is successful and onelogin/php-saml is properly setup to work with tikiwiki 18 no luck in passing the login screen.
Any help is dearly appreciated

**Comment by pitbulk** [comment]
I read that tiki18 has removed the support for [mcrypt](https://dev.tiki.org/Removing%20MCrypt%20as%20a%20dependency) that is required by the master branch of php-saml.

So you have 2 options:
* Use the [3.0.0-namespaceless](https://github.com/onelogin/php-saml/tree/3.0.0-namespaceless) branch which code is compatible with the current TikiWiki plugin
* Use the [3.0.0](https://github.com/onelogin/php-saml/tree/3.0.0) branch and adapt the TikiWiki plugin (basically, use namespaces)
