### ISSUE TITLE
automatically log in the user in the background

### ISSUE THREAD

**Issue by ChrisB9** [onelogin/php-saml#334]
Hello,

We, for our project, currently have the following workflow:
Person signs into our login service via the app. The app then authenticates with the adfs but currently by redirect and we do somehow have to handle that redirect and make the user basically sign in again. Our service then registers the successfully authenticated user after adfs redirect.
Because this sounds ridiculous, we want to ease this process and let our service do the login for the user.
Is it possible to attach the needed parameters for the login, so that it automatically is filled out and completed or do we have to crawl the website and pretend to be the user?

Does anyone have already experience with that?
Greetings
Chris

**Comment by pitbulk** [comment]
Why the app is not delegating the authentication directly on ADFS?
```
Normal login + Log via ADFS 
```

User credentials should not be sent from app to ADFS. This is not how SAML protocol works.
