### ISSUE TITLE
We're sorry, but something went wrong

### ISSUE THREAD

**Issue by bzbzh** [onelogin/php-saml#341]
Hey,

I get this message using $auth->login:
> We're sorry, but something went wrong.
> 
> We've been notified about this issue and we'll take a look at it shortly.

And yet log-in directly from portal clicking on the company app is working.

The URL giving this error looks like:
`[xxx].onelogin.com/trust/saml2/http-post/sso/8[...]1?SAMLRequest=lVNNj9[....]3D&RelayState=htt[....]dex.php`

**Comment by pitbulk** [comment]
That error message came from OneLogin and not from the php-saml toolkit.

Can you verify that the user you are trying to log in has access to the App (Check it on the SAML connector at OneLogin)?

**Comment by bzbzh** [comment]
It has since I can log to the app directly from OneLogin website (clicking the app logo).

**Comment by pitbulk** [comment]
Then you will need to create a support ticket at OneLogin since the error came from the OneLogin platform.

This github space is to solve code issues, not for offer this kind of support.

**Comment by bzbzh** [comment]
Will do. Thx.

**Comment by RamjiVE** [comment]
@pitbulk  @bzbzh  any update on that? I'm facing the same issue

**Comment by Meru3m** [comment]
[Here](https://stackoverflow.com/questions/62210294/saml-implementation-using-onelogin-in-coldfusion-throwing-error/70094916#70094916) they faced the same error and for me the answer of [Moonis Abidi](https://stackoverflow.com/users/7791324/moonis-abidi) worked. 
You just need to logout from the OneLogin Admin Pane before trying to login.
