### ISSUE TITLE
Allow for Mapping of attributes with capital letters

### ISSUE THREAD

**Issue by jtsafran** [onelogin/php-saml#342]
Thank you for the great plugin!

Would it be possible to update the plugin to accept attributes with capital letters?  If the login sends a claim of FirstName -> Jesse, the plugin ignores the value as it only seems to look for an attribute of firstname.

Thanks,
Jesse

**Comment by pitbulk** [comment]
I don't think so, the php-saml toolkit returns the attributes as they are, it does not lowercase the names.

See for example this test:
https://github.com/onelogin/php-saml/blob/master/tests/src/OneLogin/Saml2/ResponseTest.php#L101
