### ISSUE TITLE
Ignored Exception inside IdPMetadataParser::parseRemoteXML

### ISSUE THREAD

**Issue by thejahweh** [onelogin/php-saml#344]
It took us a couple of hours to find out, that the connection timed out. And only because, the error gets ignored and nothing is logged.

This line makes no sense:
https://github.com/onelogin/php-saml/blob/eda6530f216fe562fb973095a14cb9733bf34eae/lib/Saml2/IdPMetadataParser.php#L42-L43
The line above `throw new Exception(curl_error($ch), curl_errno($ch));` makes even less sense, because it gets ignored below.

**Comment by pitbulk** [comment]
True,

do you have a PR with your proposal?
