### ISSUE TITLE
Uncaught Error: Class 'OneLogin_Saml2_Auth' not found

### ISSUE THREAD

**Issue by jasonrundell** [onelogin/php-saml#347]
Followed the README. All dependent PHP libs installed. Tried with Composer setup and non-Composer setup. Tried with demos. There's no such method `OneLogin_Saml2_Auth` within code base.

**Comment by pitbulk** [comment]
What version of the library are you using?

The use of OneLogin_Saml2_Auth is compatible with 2.X, the 3.X version requires the use of Namespaces.

**Comment by jasonrundell** [comment]
@pitbulk 3.0 (https://github.com/onelogin/php-saml/releases/latest)

I think I'm dead in the water anyway because I have to deploy a SAML solution to a php 5.2 production environment in the long run. *sigh* ... slow companies ... upgrade always in the back of the Backlog Bus.

**Comment by Raul6469** [comment]
Hi, I'm facing exactly the same issue. I'm using PHP 7.3.7 and Composer 1.8.6.

Here is what I'm trying to do with php-saml 3.1.0: 
```php
require __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/vendor/onelogin/php-saml/_toolkit_loader.php';

require_once 'authentication/settings/saml-settings.php';

$auth = new OneLogin_Saml2_Auth($SAML_SETTINGS);
```

And this is what I get:
```
Fatal error: Uncaught Error: Class 'OneLogin_Saml2_Auth' not found in C:\xampp\htdocs\sfpoc\index.php
```

@pitbulk You mention that `OneLogin_Saml2_Auth` is compatible with 2.X, but 2.X requires _mcrypt_, which seems to be deprecated. 

Any help would be appreciated, thanks 🙏

**Comment by pitbulk** [comment]
@Raul6469 

php-saml 3.X uses namespaces so you may use Onelogin\Saml2\Auth
php-saml 2.X does not use namespace, so use OneLogin_Saml2_Auth

php-saml 3.X does not use mcrypt and is compatible with PHP 7.X

You are using PHP 7.3.7 so you must use php-saml 3.X  See the demo:
https://github.com/onelogin/php-saml/blob/3.2.1/demo1/index.php

**Comment by Raul6469** [comment]
Thank you very much for your help @pitbulk ! Works fine now
