### ISSUE TITLE
Onelogin SAML 2.0 SSO Login with custom login page for PHP Website

### ISSUE THREAD

**Issue by rajashrigoli** [onelogin/php-saml#351]
I need your help on Onelogin SAML 2.0 SSO Login with custom login page for PHP Website. I was unable to figure out the process of implementation in php.Can you guys share me a sample Onelogin SAML 2.0 SSO Login with custom login page php demo or share me the process for successful integration.

We have integrated onelogin SAML 2.0 SSO in our website its working fine, but when we click on login with sso its redirected to onelogin's login page. We want to create custom login page in our website for login purpose.

**Comment by pitbulk** [comment]
> We have integrated onelogin SAML 2.0 SSO in our website its working fine, but when we click on login with sso its redirected to onelogin's login page. We want to create custom login page in our website for login purpose.

This is not how SAML works, on SAML, the user is redirected from the App (Service Provider) to the Identity Provider, credentials are provided at the IdP directly, so the Login page belong the IdP, not the Service Provider.

If you are trying to implement a custom login page using OneLogin, instead use SAML, better review
https://developers.onelogin.com/api-docs/1/login-page/login-user-via-api

**Comment by silvia-kidwai** [comment]
I have implemented my custom login page with OneLogin using https://developers.onelogin.com/api-docs/1/login-page/login-user-via-api. It allows me to sign in to other SAML configured apps successfully. But when I use Api to `log_user_out` i.e https://developers.onelogin.com/api-docs/1/users/log-user-out. It only logs out from current application. But not from other apps.

Can you please guide me how can I also logout from all apps using OneLogin API

**Comment by farzam-azhar** [comment]
I have implemented my custom login page with OneLogin using https://developers.onelogin.com/api-docs/1/login-page/login-user-via-api. It allows me to sign in to other SAML configured apps successfully. But when I use Api to log_user_out i.e https://developers.onelogin.com/api-docs/1/users/log-user-out. It only logs out from current application. But not from other apps.

Can you please guide me how can I also logout from all apps using OneLogin API

**Comment by farzam-azhar** [comment]
> > We have integrated onelogin SAML 2.0 SSO in our website its working fine, but when we click on login with sso its redirected to onelogin's login page. We want to create custom login page in our website for login purpose.
> 
> This is not how SAML works, on SAML, the user is redirected from the App (Service Provider) to the Identity Provider, credentials are provided at the IdP directly, so the Login page belong the IdP, not the Service Provider.
> 
> If you are trying to implement a custom login page using OneLogin, instead use SAML, better review
> https://developers.onelogin.com/api-docs/1/login-page/login-user-via-api

I have implemented my custom login page with OneLogin using https://developers.onelogin.com/api-docs/1/login-page/login-user-via-api. It allows me to sign in to other SAML configured apps successfully. But when I use Api to log_user_out i.e https://developers.onelogin.com/api-docs/1/users/log-user-out. It only logs out from current application. But not from other apps.

Can you please guide me how can I also logout from all apps using OneLogin API

**Comment by pitbulk** [comment]
Single Logout feature is only available when SAML flow is involved.

Are you providing access to the users on your apps using SAML flow or are you using Onelogin API instead?

The log-user-out endpoint will delete the sessions related to Onelogin only. We will improve its documentation to stop confusion.

**Comment by farzam-azhar** [comment]
Currently I am giving access to users on my app using OneLogin session token API.
It allowed them to sign in on other SAML configured apps since cookie is created by OneLogin in browser.

Can you please confirm if I want to use Single Log Out feature, I must use OneLogin UI for users login purpose ?

**Comment by pitbulk** [comment]
@farzam-azhar,

In order to implement your SLO experience, without using SAML, there is something you can try.

Currently, OL platform offers a webhooks:
https://developers.onelogin.com/api-docs/1/events/webhooks

You can subscribe your apps to the (7 - User Logout event) so when the user log out from Onelogin, you can have a notification on the suscribed app and then logout the user.
