### ISSUE TITLE
FR: Streamline security signMetadata key and certificate loading

### ISSUE THREAD

**Issue by FrittenKeeZ** [onelogin/php-saml#356]
Currently `$config['security']['signMetadata']` relies on its own `certs` folder for explicit key certificate (`[keyFileName => 'metadata.key', certFileName => 'metadata.crt']`).
It would be nice if this could be streamlined with how SP and IdP keys and certificates are loaded, so they can be provided as text instead of file names.

**Comment by pitbulk** [comment]
Basically, be able to support something like:

$config['security']['signMetadata'] = array(
 'x509cert' => '',
' privateKey' => ''
);

So basically
1. Modify the [validation of SignMetadata values](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L603
) allowing 'x509cert' and ' privateKey' as valid array keys.

2. Extend the [getSPMetadata](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L814) to retrieve $keyMetadata and $certMetadata from 'x509cert' and 'privateKey' values, previously formatting them.

3. Add tests to cover that new feature

Is someone interested in implement such feature?
