### ISSUE TITLE
The response was received at ${url_to_acs} instead of ${unix_path_to_acs} 

### ISSUE THREAD

**Issue by r0ulito** [onelogin/php-saml#357]
Hello there.
I've got some problems to use onelogin with a PHP app. 

We need to receive the response on the url of the acs.
So I set everything in settings.php to match our needs. 
But the only way to have a response is to set the host name in that file. 
I think it comes from the loadPaths() method in OneLogin_Saml2_Settings class. 

I don't know if I'm clear, I can provide you more information, but I'm stuck behind a confidentiality clause, and I don't want to give more info than needed. 

Sorry for the lack of precise information, don't hesitate asking

**Comment by pitbulk** [comment]
You can rename the real domain by "example.com" and private keys/public cert by XXX.
Right now I can't understand what is the issue based on the info you provided.

**Comment by r0ulito** [comment]
Seems like reading the doc 4 times wasn't enough.
You are right. 
Added 'baseurl' => 'myurl' to settings.php made the trick. 
Thanks

**Comment by maharjanmilan** [comment]
My **acs url** was at https://domain/sso/{organizationId}/acs I had my **baseurl** setup as ```$baseUrl = 'https://domain'``` and was defining acs url as ```$acsUrl = $baseUrl . '/sso/{organizationId}/acs'``` This was always return this error "The response was received at ..... "

The way to solve this was to setup $baseUrl as ```$baseUrl = https://domain/sso/{organizationId}``` and acs url as ```$acsUrl = $baseUrl . "/acs"```
