### ISSUE TITLE
IDP Logout response go to ACS route

### ISSUE THREAD

**Issue by arturslogins** [onelogin/php-saml#359]
Hello 
I have questions about SAML Logout 

My Idp provider tells me that he can't configure 3 URL's  where is 
1. Metadata url (realm)  
2. /saml/acs (replay) 
3. /saml/logout 

He can set configuration only for  reaml and reaply wich is POST  where i receive data from provider.
When i send  /saml/logout  request to Idp -  i get back in response GET answer to /saml/acs  route 

Is that possible to configure /acs route, wich can process /logout response? 
Or maybe there is other solution for that? 

In idp documentation says that changes should be made according to WS-Federation Passive Profile standart. 
`//'wtrealm' => $spentityid,
//'wctx' => $returnTo
'wreply' => $returnTo
`
What does it means?

**Comment by pitbulk** [comment]
WS-Fed is a different protocol than SAML.

What IdP are you using? ADFS?

**Comment by arturslogins** [comment]
Ye it's kinda ADFS and Metadata is the same as for ADFS

**Comment by arturslogins** [comment]
Next solution maybe what i will do ir to setup simplesaml lib but this one looks easier to configure

**Comment by pitbulk** [comment]
On ADFS you can enable a SAML IdP and register a SAML SP.

https://tsmatz.wordpress.com/2016/12/29/azure-ad-saml-federation-application-tutorial/

Similar applies to php-saml.

**Comment by arturslogins** [comment]
I need result the same as it's realized here: https://github.com/mak-it/omniauth-latvija
