### ISSUE TITLE
How to find the default connection method used in SAML 2.0

### ISSUE THREAD

**Issue by natarajanandh** [onelogin/php-saml#361]
Kindly let us know, what are all the connection method available in SAML2.0 and which one used by default. Also, please let us know, where we can find those information.

**Comment by pitbulk** [comment]
Sorry but this communication channel is to fix issues related to php-saml. Not to learn the SAML 2.0 protocol.

You can start reading the documentation hosted at: http://saml.xml.org/saml-specifications
