### ISSUE TITLE
Composer require file structure different to that of readme - directories missing

### ISSUE THREAD

**Issue by albertStaalburger** [onelogin/php-saml#362]
Problem:
`composer require onelogin/php-saml` doesn't contain all the required folders, the `lib` directory is "missing".
Based on the documentation after installation there should be a folder `vendor/onelogin/php-saml`.
The folder structure currently after composer installation is: 
```
   onelogin
      api
         src ...
         tests ...
```
I can't seem to find the `php-saml` directory that is required to make the necessary calls as is used in demo1 and demo2

**Comment by elmonty** [comment]
I see the same issue. The documentation contains this:

> The toolkit is hosted on github. You can download it from:
> 
> Lastest release: https://github.com/onelogin/php-saml/releases/latest
> Master repo: https://github.com/onelogin/php-saml/tree/master

The file downloaded from the first link (/releases/latest) contains only two folders: **cert** and **src**. Yet the "Getting Started" section of the documentation says this:

> The new OneLogin SAML Toolkit contains different folders (certs, endpoints, extlib, lib, demo, etc.) and some files.

This leads me to believe that the zip file at /releases/latest is incorrect.  Where can I download the actual toolkit?

**Comment by pitbulk** [comment]
You see the 3.X branch not master/2.X

The file you download only contains the minimum files require to execute the project.

If you need all the files, clone the repository.

**Comment by elmonty** [comment]
Then the instructions shouldn't specify those links if they're not the ones to get started with.

Even when I download the master repository, several folders are not included in the zip file, including: demo-old, demo2, endpoints, locale, and tests.
