### ISSUE TITLE
Changes in 3.x branch?

### ISSUE THREAD

**Issue by justageek** [onelogin/php-saml#365]
HI, this is really a question about what has changed from the 2.15 branch to 3.x, we are considering upgrading but are concerned about breaking our current implementation and how much regression testing might be required.  Any feedback is appreciated.

**Comment by kynx** [comment]
The biggest change is the switch to namespaces. We were already aliasing the PSR-1 class names in our use statements. IIRC, I just changed those. 

You’ll need to upgrade sooner, if just for the php7.2 support. Though if you haven’t already got integration tests, writing some _before_ the upgrade would be wise ;)

HTH

**Comment by pitbulk** [comment]
- Namespaces
- Compatible with PHP 7.2
- xmlseclibs files not part of the code anymore (handle it has composer dependence).

Compare the code of the demo files and you will see the changes, basically, the use of namespaces.
