### ISSUE TITLE
Add <saml:Subject> to AuthnRequest 

### ISSUE THREAD

**Issue by amnuts** [onelogin/php-saml#366]
I'd like to pass the user's login username on to the IdP so that it could use the information to 'pre-fill' the login form if it wanted to.  From a little searching around I understand this is possible by supplying the `<saml:Subject>` node into the AuthenRequest.  However, I've had a look at the `OneLogin_Saml2_AuthnRequest` but it doesn't look like it's capable of adding a subject.

Is there another way to do this or could it be added an an enhancement?

Thanks!

**Comment by pitbulk** [comment]
The toolkit does not support Subjects on AuthRequest, but you can extend the AuthRequest class and use it on an extended class of Auth.

**Comment by amnuts** [comment]
👍 thanks for the info @pitbulk - confirms what I thought.

**Comment by pitbulk** [comment]
@amnuts We decided to support it soon
