### ISSUE TITLE
Set DomainHint in v2.6.0

### ISSUE THREAD

**Issue by citosid** [onelogin/php-saml#368]
I'm using version 2.6.0 in a production enviroment. 

Is there anyway to set the domain_hint so the home realm discovery page is ignored?

**Comment by pitbulk** [comment]
The login and logout methods have a 
```
@param array $parameters Extra parameters to be added to the GET
```

So you can define not only the 'domain_hint', but any other parameter that you requires.

**Comment by citosid** [comment]
Thank you @pitbulk ! I tried that but did not work.

I tried to do what it says [here][1], but it did not work. I tried modifying the authn request xml and adding things to the query string, but it still goes to the home discovery realm page. 

It is interesting that other services we have use OIDC and there that page is correctly skipped if the user is hinted.

[1]: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-authentication-for-federated-users-portal

**Comment by pitbulk** [comment]
If you try that and you use some browser extension to record the HTTP(s) traffic, you will verify that the domain_hint parameter is provided like you requested.

I don't have a deep knowledge on Azure, but reading the documentation, it seems that the
'domain_hint' parameter is for OIDC, SAML expects a 'whr' parameter

```
Domain hints

blablabla

WS-Federation: whr=contoso.com in the query string.

SAML: Either a SAML authentication request that contains a domain hint or a query string whr=contoso.com.

Open ID Connect: A query string domain_hint=contoso.com. 
```

**Comment by citosid** [comment]
I ended up giving up on this. We will change to OIDC later. It seems that not matter what we do, it will ignore it.

Thank you for your support!
