### ISSUE TITLE
Path to Schema on fileshare

### ISSUE THREAD

**Issue by carlhussey** [onelogin/php-saml#369]
I have a setup where there are two web servers and a single file-share that hosts the files. Depending on the traffic, the load balancer will send the user to server 1 or server 2 and then the files are loaded appropriately. 

The issue I am running into is in the Utils.php file within the validateXML function. There is a line that is looking for the schema file to validate the SAML response with.

For some reason, using the fileshare setup, I am unable to get this to work without making a change and putting the schema files directly on the two servers and referencing them locally.

```
   public static function validateXML($xml, $schema, $debug = false)
    {
        assert(is_string($xml) || $xml instanceof DOMDocument);
        assert(is_string($schema));

        libxml_clear_errors();
        libxml_use_internal_errors(true);

        if ($xml instanceof DOMDocument) {
            $dom = $xml;
        } else {
            $dom = new DOMDocument;
            $dom = self::loadXML($dom, $xml);
            if (!$dom) {
                return 'unloaded_xml';
            }
        }

        //$schemaFile = __DIR__ . '/schemas/' . $schema;
        $schemaFile = 'file://C:\inetpub\wwwroot\config\schemas\\'. $schema;
```

The error I receive if I don't do this is as follows:

Invalid Schema in` \\fileshare\root\resources\Classes\OneLogin\src\Saml2\Utils.php on line 135 failed to load external entity.`

Is this an issue with OneLogin being able to reference files from a file-share within how the schemaValidate works or is there something PHP related I need to look into?

**Comment by pitbulk** [comment]
I never used file-sharing so don't know why this is failing to you.

The way to get the schema path:
```
$schemaFile = __DIR__ . '/schemas/' . $schema;
```
is a very common PHP approach so I wonder that is fails only for the toolkit.

_DIR_ is Magic constant that returns current directory location which may be different for both servers.
