### ISSUE TITLE
Upgraded to PHP 5.6 → 7.2 and the following system error occurred.

### ISSUE THREAD

**Issue by taketomon** [onelogin/php-saml#370]
I got following error after upgrading PHP version from 5.6 to 7.2.

>Failure evaluating code:  is_array($settings)  stacktrace: 
>  /app/vendor/onelogin/php-saml/lib/Saml2/Settings.php(363): assert('is_array($setti...')
>  /app/vendor/onelogin/php-saml/lib/Saml2/Settings.php(216): OneLogin_Saml2_Settings->checkSettings(Array)
>  /app/vendor/onelogin/php-saml/lib/Saml2/Settings.php(98): OneLogin_Saml2_Settings->_loadSettingsFromArray(Array)
>  /app/vendor/onelogin/php-saml/lib/Saml2/Auth.php(66): OneLogin_Saml2_Settings->__construct(Array)
>  /app/vendor/aacotroneo/laravel-saml2/src/Aacotroneo/Saml2/Saml2ServiceProvider.php(54): OneLogin_Saml2_Auth->__construct(Array)
>  /app/bootstrap/cache/compiled.php(1353): Aacotroneo\Saml2\Saml2ServiceProvider->Aacotroneo\Saml2\{closure}(Object(Illuminate\Foundation\Application), Array) ...

I used following php-saml and laravel-saml2 version.
* onelogin/php-saml: 2.9.1
* aacotroneo/laravel-saml2: 0.8.1

If there is any solution, please share me.
Thanks in advance.

**Comment by pitbulk** [comment]
If you plan to use PHP 7.2, then you need to use:
aacotroneo/laravel-saml2  1.X
onelogin/php-saml 3.X

**Comment by taketomon** [comment]
thanks so much @pitbulk  
I will try it right away.
