### ISSUE TITLE
How to configure `CertificateProtectedTransport`

### ISSUE THREAD

**Issue by sclausen** [onelogin/php-saml#387]
I need to implement SAML authentication for an application and have been told by the administrator of the idp that I have to use `<saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:CertificateProtectedTransport</saml:AuthnContextClassRef>`. Unfortunately, I haven't found anything regarding `CertificateProtectedTransport` in this repository. Do you have any information about this setting?

**Comment by pitbulk** [comment]
In the settings set as [requestedAuthnContext](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L70) the value urn:oasis:names:tc:SAML:2.0:ac:classes:CertificateProtectedTransport

Maybe you can send a PR to include it as an option on the toolkit.

**Comment by sclausen** [comment]
Thanks it works great, but requestedAuthnContext needs to be an array of strings in this case.
