### ISSUE TITLE
Destination check with multiple environment

### ISSUE THREAD

**Issue by OssiPesonen** [onelogin/php-saml#388]
Our enterprise has Azure AD where our current company user pool is located. We have multiple web environments for the same platform and our Azure Apps are controlled by a separate IT department. Currently, if I want to have SSO enabled for one of our environments I would have to request a separate App to be made and users added from the pool to the app. This is a pain and can take days. If i wanna make changes, again, days.

I created an AWS API Gateway and Lambda service which handles the SAMLResponse Azure sends it, reads the RelayState and redirects the user to the environment the request originated from with SAMLResponse in GET parameters. 

Basic stuff when dealing with, for example, multisite solutions where there's one platform but multiple domains. With social media logins you have to create a portal point because otherwise you have to create an app for each of the domains.

Now, our issue is the library's Destination check interferes with this setup. When I set the SP assertionConsumerService url address to API Gateway ("https://....execute-api.eu-west-1.amazonaws.com/.../) the Destination is set to this, and the check fails when our domain is example.com/login.php which handles the 'true' processing. Lambda is just a portal point that redirects the user back to the original location.

Now, is there any way to get around this because it's really a pain if I have to fork the library instead of somehow overwriting this check?

**Comment by pitbulk** [comment]
you can set relaxDestinationValidation to true and see if Azure AD is able to not send the Destination parameter

otherwise, you will need to play with the host, protocol, port and baseurlpath parameters
of the [Utils class](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L23)
to simulate that AWS is the real endpoint.

**Comment by OssiPesonen** [comment]
Well I created a 'hack' to get past this.

```
\OneLogin\Saml2\Utils::setBaseURL("https://example.com/redirect_portal);
\OneLogin\Saml2\Utils::setBaseURLPath("/redirect");

$serverSuperGlobalValues = [];
$nullKeys = ['SCRIPT_NAME','QUERY_STRING','REQUEST_URI'];

foreach($nullKeys as $k) {
    $serverSuperGlobalValues[$k] = $_SERVER[$k];
    $_SERVER[$k] = null;
}

$auth->processResponse($requestID);

# Restore original values
foreach($nullKeys as $k) {
    $_SERVER[$k] = $serverSuperGlobalValues[$k];
}
```

These solutions are executed by professionals and should not be tried at home!
