### ISSUE TITLE
OneLogin_Saml2_ValidationError, SAMLResponse is not base64 encoded

### ISSUE THREAD

**Issue by straldev** [onelogin/php-saml#390]
We have been using OneLogin as a SAML2 SP with several IdPs without issue, but we are getting stuck with a specific client's IdP. When they attempt to utilize SAML2 we get a "OneLogin_Saml2_ValidationError 'SAML Response could not be processed'".

Digging in I realized that the issue is this line, from OneLogin_Saml2_Response​::​__construct

`$this->response = base64_decode($response);`

Here, $reponse is the actual raw, not base64 encoded, XML document. When base64_decode() gets a hold of this, it returns "false" (I suspect because it's being asked to decode a non-encoded string)​, which raises the exception a few lines lower.

The IdP is a backpatched version of ​Apereo CAS​ 3.4.12​. According to our client, they use this IdP with several SPs without issue, and per their testing those SPs are accepting a non-base64 encoded SAMLResponse value.​​

Under any circumstance should the SAMLResponse POST parameter NOT be base64 encoded? It seems that it is suppose to be encoded, but then I'm not sure why Apereo CAS would ever send it without encoding.

If a non-base64 SAMLResponse is allowed, is there a way to get php-saml to support this?

Thanks!

**Comment by pitbulk** [comment]
Are you sure they are using HTTP-POST binding?
Are you sure the SAMLResponse XML came in plain text?

A fast and easy patch is to base64encode the SAMLResponse before sent it to the Response if it came in plain text, but that format is against the standard

**Comment by straldev** [comment]
I just logged the raw POST value and it is definitly XML in plain text. I also captured some values from other clients and their's is base64 encoded. The client confirmed that they are using "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" binding.

Thanks for any insight you can provide!

**Comment by straldev** [comment]
Thanks for the help @pitbulk, I will advice the client to contact thier CAS vender.
