### ISSUE TITLE
Showing "Not authenticated" when the request is made "NameID not found in the assertion of the Response"

### ISSUE THREAD

**Issue by gauravjain024** [onelogin/php-saml#392]
Showing "Not authenticated" when the request is made 
Don't know what's the main cause of it.
And Attributes are also blank
"NameID not found in the assertion of the Response"

**Comment by pitbulk** [comment]
If at the setting the "wantNameId" is set to true (default value), then the toolkit will invalidate SAMLResponses with no NameID, 

when SAMLResponse is invalidated, the demo will show "Not authenticated" and attributes are not retrieved since the SAMLResponse was invalidated.
