### ISSUE TITLE
Assertion queries fail when IdPs omit samlp:Response node

### ISSUE THREAD

**Issue by flashbackzoo** [onelogin/php-saml#396]
Using version 3.3.0 I'm getting the following error:

`Unexpected number of Response signatures found. SAML Response rejected.`

See https://github.com/onelogin/php-saml/blob/3.3.0/src/Saml2/Response.php#L994

The problem is a mismatch between the assertion signature path and the structure of the SAML response from our IdP.

**Assertion signature path:**
`/samlp:Response/saml:Assertion/ds:Signature`
https://github.com/onelogin/php-saml/blob/3.3.0/src/Saml2/Utils.php#L37

**SAML response:**
```xml
<saml2:assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" id="" issueinstant="" version="2.0">
    ...
    <ds:signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        ...
    </ds:signature>
    ...
</saml2:assertion>
```

The response doesn't have a root `samlp:Response` node, so the query fails.

There are a few other places where the assertion path is hardcoded too:
* https://github.com/onelogin/php-saml/blob/3.3.0/src/Saml2/Response.php#L383
* https://github.com/onelogin/php-saml/blob/3.3.0/src/Saml2/Response.php#L1034
* https://github.com/onelogin/php-saml/blob/3.3.0/src/Saml2/Response.php#L1050

Looking through the changelogs I see a similar issue was addressed way back in v2.3.0:

> Resolve namespace problem. Some IdPs uses saml2p:Response and saml2:Assertion instead of samlp:Response saml:Assertion.

As a short term workaround I've created a fork and updated the hardcoded XPath queries, which works for now, but I would like more long term solution.

Do you have any thoughts on a nice way to make the paths configurable?

**Comment by pitbulk** [comment]
IdP should not omit samlp:Response, it goes against the SAML standard.

**Comment by flashbackzoo** [comment]
Thanks for the quick reply @pitbulk I'll close this. It was a bug in our codebase removing the response node.
