### ISSUE TITLE
BREAKING CHANGE in 3.3.0

### ISSUE THREAD

**Issue by estahn** [onelogin/php-saml#400]
Just FYI: Since 3.3.0 introduces a breaking change (change from default behaviour) it should have been bumped to 4.0.0 instead.

**Comment by pitbulk** [comment]
I don't consider it a " breaking change", as defined in the README in several [places](https://github.com/onelogin/php-saml#security-warning)
```
In production, the strict parameter MUST be set as "true"
```

We intentionally deliver it as it is.
