### ISSUE TITLE
3.3.0 broken

### ISSUE THREAD

**Issue by ThomasLabstep** [onelogin/php-saml#403]
Hello,

We just did a package upgrade from 3.1.0 to 3.3.0 and we are now getting 'invalid_response' from our provider with this new version.

Any idea what might be a breaking change?

```
CHANGELOG
=========
v.3.3.0
* Set true as the default value for strict setting
* Relax comparision of false on SignMetadata
* Fix CI
```

The following versions are working fine:
3.1.1
3.2.0
3.2.1

Our config:
```
single_sign_on_service_binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
single_logout_service_binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
```

Thanks!

**Comment by pitbulk** [comment]
As detailed on the changelog and readme, "Version 3.3.0 sets strict mode active by default"

It seems your instance had strict mode disabled which is terrible in production instances, that why we are forcing it to enable by default.

If you enable debug or retrieve the getLastErrorReason you will see the cause for the toolkit rejecting the SAMLResponse.

**Comment by estahn** [comment]
@ThomasLabstep see https://github.com/onelogin/php-saml/issues/400

**Comment by ThomasLabstep** [comment]
@pitbulk Thank you for the explanation.
@estahn Thank you.

We don't manage the production instance.
We're only integrating with them.
We will notify them about this.
