### ISSUE TITLE
processSLO will fail on redirect if responseUrl field of IdP settings is empty but present

### ISSUE THREAD

**Issue by Matthius** [onelogin/php-saml#407]
As the title says.
I just had an issue when fetching an IdP remotely, the IdP settings would look like that: 

```
    [singleSignOnService] => Array
        (
            [url] => https://lala.com
            [binding] => urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
        )

    [singleLogoutService] => Array
        (
            [url] => https://lala.com
            [responseUrl] => ''
            [binding] => urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect
        )
```

On Auth.php of the lib, when processing an SLO request, the code would only check if the field singleLogoutService->responseUrl would exist, and then process, instead of checking if empty.

Original:
```
    public function getSLOResponseUrl()
    {
        $idpData = $this->_settings->getIdPData();
        if (isset($idpData['singleLogoutService']) && isset($idpData['singleLogoutService']['responseUrl'])) {
            return $idpData['singleLogoutService']['responseUrl'];
        }
        return $this->getSLOurl();
    }
```

Fix:

```
    public function getSLOResponseUrl()
    {
        $idpData = $this->_settings->getIdPData();
        if (isset($idpData['singleLogoutService']) && isset($idpData['singleLogoutService']['responseUrl']) && !empty($idpData['singleLogoutService']['responseUrl'])) {
            return $idpData['singleLogoutService']['responseUrl'];
        }
        return $this->getSLOurl();
    }
```

This way if the field is empty (for whatever reason), it will check for the 'url' field, as expected.

Can someone confirm this?

N.B.: maybe there is also an issue with the IdPMetadataParser::parseRemoteXML($url); returning an empty responseUrl field instead of nothing? Didn't check this one.

**Comment by pitbulk** [comment]
If the metadata contains a responseUrl element with empty value, it should be parser as empty.
Can you check if the parser is returning an empty responseUrl even if the element does not exists?

If on the settigs, the responseUrl is defined, I think should be used, otherwise set it as nil or not use it.

**Comment by pitbulk** [comment]
Ok I think that's the issue
```
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/IdPMetadataParser.php#L145
```
