### ISSUE TITLE
Firefox Showing security warning for sp shibboleth connector in onelogin

### ISSUE THREAD

**Issue by Rushi1807** [onelogin/php-saml#420]
![image](https://user-images.githubusercontent.com/58320679/72317834-84ed8200-36c0-11ea-9a6e-2781ce7f9961.png)

**Comment by pitbulk** [comment]
That happens when you send POST data between HTTPs --> HTTP

**Comment by Rushi1807** [comment]
any Solution to this because if i change http to https then saml authentication fails give error want http got https!
