### ISSUE TITLE
Make use of the PHP version requirements in composer.json

### ISSUE THREAD

**Issue by yourithielen** [onelogin/php-saml#421]
I'm currently on the 2.x branch and plan to do an upgrade to PHP 7.4. When i ran `composer require php:^7.4`, no warmings were shown for this library. Only by chance i read: 

> The 3.X branch is compatible with PHP > 7.1, so if you are using that PHP version, use it and not the 2.X or the master branch

What about fixing the PHP requirements in `composer.json`?

**Comment by pitbulk** [comment]
Fixed https://github.com/onelogin/php-saml/commit/c3803254a2ffb36bd0cdbcaf200469309973dd52

**Comment by yourithielen** [comment]
@pitbulk Maybe add it to the 2.x branch too and create a new tag ( I really don't know what to do with the existing 2.x tags, propbably leave them as they are)? And I also would suggest adding an upper bound to the highest version supported in the 3.x branch, see https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md. This avoids creating the same situation in the future with the 3.x branch.

So ideally you would do this for the 3.x branch: `"php": ">=5.4 <=7.4"`and when 7.5 is released bump it to 7.5.
