### ISSUE TITLE
Failed login for missing InResponse to at top-level Response node

### ISSUE THREAD

**Issue by gmazzap** [onelogin/php-saml#428]
I'm integrating with an IdP that does *not* provide `InResponse` attribute as top-level `Response` node.

They provide the `InResponse` value as attribute of the node at `Response/Assertion/Subject/SubjectConfirmation/SubjectConfirmationData`.

I looked at the specs and it seems that `InResponse` atribute for top-level `Response` node is optional.

Would you consider to edit the Response validy check method to look in `Response/Assertion/Subject/SubjectConfirmation/SubjectConfirmationData` for `InResponse` if top-level `Response` does not have it?

It would mean that the lines https://github.com/onelogin/php-saml/blob/5fbf3486704ac9835b68184023ab54862c95f213/src/Saml2/Response.php#L199-L201 would change to this:

```php
if ($this->document->documentElement->hasAttribute('InResponseTo')) {
    $responseInResponseTo = $this->document->documentElement->getAttribute('InResponseTo');
} else {
    $confirmationData = $this->document->getElementsByTagName('SubjectConfirmationData');
    if ($confirmationData->length > 0) {
        $responseInResponseToNode = $confirmationData
            ->item(0)
            ->attributes
            ->getNamedItem('InResponseTo');
        $responseInResponseTo = $responseInResponseToNode
            ? $responseInResponseToNode->nodeValue
            : null;
    }
}
```

Note how nothing would change if `InResponseTo` is part of the top-level `Response` node.

Maybe the retrieval of `InResponseTo` could be moved to a separate method, something like:

```php
    private function getInResponseTo()
    {
        if ($this->document->documentElement->hasAttribute('InResponseTo')) {
            return $this->document->documentElement->getAttribute('InResponseTo');
        }

        $confirmationData = $this->document->getElementsByTagName('SubjectConfirmationData');
        if ($confirmationData->length <= 0) {
            return null;
        }

        $responseInResponseToNode = $confirmationData
            ->item(0)
            ->attributes
            ->getNamedItem('InResponseTo');

        return $responseInResponseToNode ? $responseInResponseToNode->nodeValue : null;
    }
```

I'd be happy to send a PR.

**Comment by pitbulk** [comment]
```
I looked at the specs and it seems that InResponse attribute for top-level Response node is optional.
```

The spec describes it as an Optional attribute but it refers to the case of IdP-initiated SSO
On an SP-initiated flow, the InResponseTo on the SAMLResponse MUST exist

Extracted from [SAML core documentation ](https://www.oasis-open.org/committees/download.php/7473/sstc-saml-core-2.0-draft-15-diff.pdf)
```
Section 3.2.1.1 Complex Type StatusResponseType

InResponseTo [Optional]
A reference to the identifier of the request to which the response corresponds, if any. If the response is not generated in response to a request, or if the ID attribute value of a request cannot be determined (because the request is malformed), then this attribute MUST NOT be present. Otherwise,
it MUST be present and its value MUST match the value of the corresponding request's ID attribute
value.
```
So I can't accept your suggestion. 


The SubjectConfirmationData elements and its InResponseTo attribute, are both optionals. 
That why is only [checked if present](https://github.com/onelogin/php-saml/blob/b962da1fa70402d7ef63bba5351cad2a4e69fb7f/lib/Saml2/Response.php#L313) and not required in the code

**Comment by gmazzap** [comment]
Hi @pitbulk and thanks for your thoughtful response.

Reading carefully the specs you're indeed correct. But I can also assure you that there are implementations out there that are not compliant because I'm dealing with one of them (.NET-based IIUC).

The code I proposed would not affect standard-compliant servers but would be error-tolerant. But I can understand you don't want to tolerate errors.

> The SubjectConfirmationData elements and its InResponseTo attribute, are both optionals.

I saw that and in fact, my implementation _tries_ to read them and would cause no error of sort if those optional node and/or attribute are not present.

All that said I totally understand if you are not willing to accept my proposal (please close this issue if so). In that case, I will try to deal with the non-compliant server in some way.

Thanks for your time anyway.

**Comment by pitbulk** [comment]
You can always extend the SAMLResponse and Auth classes with the custom classes with the specific changes your project requires, overriding the specific methods.
