### ISSUE TITLE
The response was received at http:// instead of https:// and reverse proxy issue

### ISSUE THREAD

**Issue by wilkolazki** [onelogin/php-saml#430]
Hi,

We are trying to implement saml for the first time and I have stumbled over the issue with response being rejected because the protocol filed does not match. The exception is:
```
The response was received at http://example.com/acs instead of https://example.com/acs
```
The only thing that differs is the protocol field. And the sole reason that it differs is that we use a revese proxy which takes care of the ssl encryption and forwards the traffic to the server via plain  http. 
The exception is thrown in OneLogin\Saml2\Response class. I am looking into source but I do not see any option to disable protocol check. 

How can we overcome this problem? 
We are using php-saml 3.0.0 via the [asasmoyo/yii2-saml](https://github.com/asasmoyo/yii2-saml/) package.

Best regards,
Szymon Wilkołazki

**Comment by wilkolazki** [comment]
Never mind, I have just found your README file...

**Comment by mkraibt** [comment]
@wilkolazki I have same issue, how did you sort it out ? I am using yii2 in  docker with nginx proxy server.

**Comment by bzbzh** [comment]
@mkraibt the according section in README file starts here: https://github.com/onelogin/php-saml#url-guessing-methods

A solution that could work seems to use `setProxyVars(true)`

**Comment by perrywu1008** [comment]
I was reading the README but couldn’t quite grasp what "When the PHP application is behind a proxy or a load balancer we can execute setProxyVars(true) " meant. Essentially, it means you need to insert an extra line of code before creating the Auth object:

`
\OneLogin\Saml2\Utils::setProxyVars(true); // It’s a static method, so just call it.
$auth = new \OneLogin\Saml2\Auth($settings);
`
