### ISSUE TITLE
Signature validation failed. Logout Response rejected

### ISSUE THREAD

**Issue by sc-keyzo** [onelogin/php-saml#433]
Hi

I'm using php_saml with Microsoft ADFS and I appear to have an odd issue with signature validation following a request to logout.  The logout appears to succeed:

`<samlp:LogoutResponse ID="_32430e08-5b84-4115-bfd1-f8e96d0d9a51"
                      Version="2.0"
                      IssueInstant="2020-06-22T10:24:21.722Z"
                      Destination="https://adfsclient.testit.co.uk/demo1/index.php?sls"
                      Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                      InResponseTo="ONELOGIN_ebeae7345ace4969304de29c63ca3a8dec62a174"
                      xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                      >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://adfs.testitnow.net/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
</samlp:LogoutResponse>`

But i receive the following error in my browser:

`Signature validation failed. Logout Response rejected

invalid_logout_response
You have the following attributes:
Name	 												Values
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn		 simon@testitnow.net

uid														simon`

Please can you provide some guidance as to why this is happening.  Here is a full list of the SAML sent and received:

### Login

`<samlp:Response ID="_f7c0ec7a-fb59-46c4-8a1c-6a2aaf769a41"
                Version="2.0"
                IssueInstant="2020-06-22T10:18:47.672Z"
                Destination="https://adfsclient.testit.co.uk/demo1/index.php?acs"
                Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                InResponseTo="ONELOGIN_f2e8c9c76dc3dcd3928f5d820d7574278ea8a63c"
                xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://adfs.testitnow.net/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
    <Assertion ID="_b86f86e6-ddcb-4c44-9ec9-118207a31bd0"
               IssueInstant="2020-06-22T10:18:47.640Z"
               Version="2.0"
               xmlns="urn:oasis:names:tc:SAML:2.0:assertion"
               >
        <Issuer>http://adfs.testitnow.net/adfs/services/trust</Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
                <ds:Reference URI="#_b86f86e6-ddcb-4c44-9ec9-118207a31bd0">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
                    <ds:DigestValue>XyJpRcv4I00bO0L9Iq+/a+DZy11cpJ8MumUCGDMHHL0=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>islOfXmgAHFXDp9A78A9ekE4OePv+...ZqWhHIAW+4110DoS1nsNg==</ds:SignatureValue>
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>MIIFvDCCBKSgAwIBAgI...</ds:X509Certificate>
                </ds:X509Data>
            </KeyInfo>
        </ds:Signature>
        <Subject>
            <NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">simon@testitnow.net</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="ONELOGIN_f2e8c9c76dc3dcd3928f5d820d7574278ea8a63c"
                                         NotOnOrAfter="2020-06-22T10:23:47.672Z"
                                         Recipient="https://adfsclient.testit.co.uk/demo1/index.php?acs"
                                         />
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2020-06-22T10:18:47.625Z"
                    NotOnOrAfter="2020-06-22T11:18:47.625Z"
                    >
            <AudienceRestriction>
                <Audience>https://adfsclient.testit.co.uk/demo1/metadata.php</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn">
                <AttributeValue>simon@testitnow.net</AttributeValue>
            </Attribute>
            <Attribute Name="uid">
                <AttributeValue>simon</AttributeValue>
            </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2020-06-22T10:18:47.235Z"
                        SessionIndex="_b86f86e6-ddcb-4c44-9ec9-118207a31bd0"
                        >
            <AuthnContext>
                <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>`

### Logout Request

`<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                     ID="ONELOGIN_ebeae7345ace4969304de29c63ca3a8dec62a174"
                     Version="2.0"
                     IssueInstant="2020-06-22T10:24:21Z"
                     Destination="https://adfs.testitnow.net/adfs/ls/"
                     >
    <saml:Issuer>https://adfsclient.testit.co.uk/demo1/metadata.php</saml:Issuer>
    <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">simon@testitnow.net</saml:NameID>
    <samlp:SessionIndex>_b86f86e6-ddcb-4c44-9ec9-118207a31bd0</samlp:SessionIndex>
</samlp:LogoutRequest>`

### Logout Response

`<samlp:LogoutResponse ID="_32430e08-5b84-4115-bfd1-f8e96d0d9a51"
                      Version="2.0"
                      IssueInstant="2020-06-22T10:24:21.722Z"
                      Destination="https://adfsclient.testit.co.uk/demo1/index.php?sls"
                      Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified"
                      InResponseTo="ONELOGIN_ebeae7345ace4969304de29c63ca3a8dec62a174"
                      xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                      >
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://adfs.testitnow.net/adfs/services/trust</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
</samlp:LogoutResponse>`

**Comment by poettian** [comment]
I meet same issue when using Azure AD.

**Comment by pitbulk** [comment]
Have you tried if the setting [lowercaseUrlencoding](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L117) fix the issue?

```
'lowercaseUrlencoding' => true,
```

**Comment by poettian** [comment]
This error occurs when issuing Sp-initiate Logout.As you point out,the problem is caused by upcaseUrlEncoding. But change this setting not useful.`$retrieveParametersFromServer = true`  in `processSLO()` is ok.`urlencode() in lib/Saml2/Utils.php:1514` is the reason.Thanks for your help.@pitbulk

**Comment by bytestream** [comment]
@poettian @pitbulk what was the fix here? I have `'lowercaseUrlencoding' => true,` and `$retrieveParametersFromServer = true` but still get `Signature validation failed. Logout Response rejected` when using Azure AD

**Comment by pitbulk** [comment]
Can you confirm only 1 IdP cert is used at Azue AD and it is registered at php-saml?

**Comment by gareth41** [comment]
I also had this exact same problem with Azure AD and logout response being rejected.  Setting 'lowercaseUrlencoding' => true, and $retrieveParametersFromServer = true solved the issue.
