### ISSUE TITLE
3.5.0 PHP version constraints

### ISSUE THREAD

**Issue by bytestream** [onelogin/php-saml#448]
https://packagist.org/packages/onelogin/php-saml if you compare tags 3.4.1 and 3.5.0 the PHP version constraints are downgraded.

Was this intended?

I am using 3.4.1 on PHP 7.2 - 7.4 without any issues.

**Comment by ecsecta** [comment]
+1

**Comment by arokettu** [comment]
It's much funnier #449

**Comment by bytestream** [comment]
@arokettu suggest to close that to avoid duplication 👍

**Comment by bytestream** [comment]
I'm closing this as the issue is now resolved.

https://github.com/onelogin/php-saml/releases/tag/3.5.1
