### ISSUE TITLE
Does php-saml support passive login?

### ISSUE THREAD

**Issue by martynbiz** [onelogin/php-saml#45]
Hi,

Does php-saml support pasive login - where a check at the IdP can be made without forcing the user to login if they have not authenticated. For example, if a user accesses one of our homepages on an applcication they don't need to be authenticated. However, I would like to update their status whether or not they are logged in (logged in? yes! Show welcome text and logout button .. otherwise, show register button and login button) so I am hoping to at least check whether they are logged in or not on every page load. 

Currently I'm playing with SimpleSAMLphp. It allows for passive login but does so using redirects. This works OK, but breaks the back button in Firefox and we have to do some hacking. Also I was kinda hoping that this would have been done from the application using curl requests before returning to the browser. I guess the guys at SSP know what they are doing though and have opted for redirects as a preferred solution.

Anyway I was keen to know if this ability is available in saml-php and if so, a quick overview of how it works (redirects, curl etc). It's kinda the main feature I'm interested in of other SAML client/servers. Thereafter, I might make the time to experiment more with php-saml for our online applications. 

Would really appreciate if you could just explain briefly how this works - if php-saml offers it.

Best regards
Martyn

**Comment by axis80** [comment]
Is it still the case that OneLogin does not support passive login?  I am seeing conflicting / confusing information and hoping someone can provide me with an authoritative answer.

This section of the Readme suggests that the app does support passive:

`$isPassive` - When true the `AuthNRequest` will set the `Ispassive='true'`

However, when I use this parameter I get this error message in my logs: "The status code of the Response was not Success, was Responder -> Passive authentication not supported."  

I'm not clear on whether that error message is coming from OneLogin or from the IDP.

**Comment by pitbulk** [comment]
The php-saml toolkit supports it, but based on the SAMLResponse with  "The status code of the Response was not Success, was Responder -> Passive authentication not supported." Is the IdP the one that does not support it.

**Comment by axis80** [comment]
Posting a followup here for others who land on this discussion from a search engine.  With the IDP I am using, it turns out the error message "The status code of the Response was not Success, was Responder -> Passive authentication not supported." simply means that the user is not currently logged in, so the IDP was unable to complete the passive login request.  It is worded very badly.  It does not actually indicate that the IDP doesn't support passive mode.  The important thing to look at is the StatusCode in the response.  A failed passive login attempt will return the code urn:oasis:names:tc:SAML:2.0:status:NoPassive.

**Comment by Aleksandr1705** [comment]
Has anyone solved this problem?

**Comment by pitbulk** [comment]
In order to execute a passive execution all you need to do is to call the login method with the isPassive=true
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/AuthnRequest.php#L37

If the IdP has an opened session, then a valid SAMLResponse with Status=Success will be returned without require any action by the end user.

If the IdP has not an opened session, then a SAMLResponse with Status=NoPassive will be returned, you could then execute an active flow

**Comment by Aleksandr1705** [comment]
It's works, if only i added 'urn:federation:authentication:windows' to the requestedAuthContext parameter.

**Comment by pitbulk** [comment]
That depends on how your IdP handles the AuthNRequest.

Maybe in your environment, there is no active session at the IdP at all, but is able to authenticate users by NTML

**Comment by Aleksandr1705** [comment]
Why IsPassive parameter  not included in configuration file? It is very necessary function, that allows to login without enter authentication information on IDP in corporate network with domain users. For what we used SSO. php-saml library used in many projects, for example zabbix. And if we need use passive mode, we need to edit source files. It is not correct.

**Comment by pitbulk** [comment]
as I told you previously, it is controlled by a method parameter of the login function, which is a more dynamic way than controlling it in an static setting file

**Comment by Aleksandr1705** [comment]
I can not specify parameter to the login method, because this method used in the vendor's files.

**Comment by pitbulk** [comment]
> I can not specify parameter to the login method, because this method used in the vendor's files.
Any plugin/extension using php-saml should offer the same parameters that the php-saml toolkit offers.

The laravel-saml2projects supports the isPassive attribute:
https://github.com/aacotroneo/laravel-saml2/blob/master/src/Aacotroneo/Saml2/Saml2Auth.php#L113

so I don't get why you can't execute an AuthNRequest with isPassive enabled there. Is simple.

If you review the examples offered in the [documentation](https://github.com/aacotroneo/laravel-saml2#usage)
instead:
```
protected function unauthenticated($request, AuthenticationException $exception)
{
     ....

    $saml2Auth = new Saml2Auth(Saml2Auth::loadOneLoginAuthFromIpdConfig('mytestidp1'));
    return $saml2Auth->login('/my/redirect/path');
}
```

you will need to have something like:
```
protected function unauthenticated($request, AuthenticationException $exception)
{
     ....

    $saml2Auth = new Saml2Auth(Saml2Auth::loadOneLoginAuthFromIpdConfig('mytestidp1'));
    return $saml2Auth->login('/my/redirect/path', [], false, true,true);
}
```

And you can extend the Saml2Controller defining a custom controller
```
use Aacotroneo\Saml2\Http\Controllers\Saml2Controller;

class MySaml2Controller extends Saml2Controller
{
    public function login()
    {
        $loginRedirect = '...'; // Determine redirect URL
        $this->saml2Auth->login($loginRedirect, [], false, true,true);
    }
}
```

**Comment by Aleksandr1705** [comment]
If i develop my own project, i can use this method. When i use third-party application, i can only edit config file.
