### ISSUE TITLE
IDP Metadata parser fails to parse X509 Certificate

### ISSUE THREAD

**Issue by Chad-R-S** [onelogin/php-saml#450]
When parsing some IDP metadata it was failing to parse out the X509 certificate, though it did exist in the XML. I think this might be an issue with the `IdPMetadataParser`. It uses the following xPath to discover the X509 certificate data:

`'./md:KeyDescriptor[not(contains(@use, "encryption"))]/ds:KeyInfo/ds:X509Data/ds:X509Certificate'`

However, I believe the use of a prefix (such as `ds:`) is optional...? That is why it fails in my case, as these elements do not have the `ds:` prefix on them in the metadata. Would it make sense to adjust the xPath query to not care about the prefix on these elements? Such as:

`'./md:KeyDescriptor[not(contains(@use, "encryption"))]/*[local-name() = \'KeyInfo\']/*[local-name() = \'X509Data\']/*[local-name() = \'X509Certificate\']'`

**Comment by pitbulk** [comment]
Even if the ds isn't in use, the namespace should be defined in the XML.
What IdP are you using? is a self-made IdP?

**Comment by Chad-R-S** [comment]
> Even if the ds isn't in use, the namespace should be defined in the XML.
> What IdP are you using? is a self-made IdP?

Yes, it's a self-made IdP (not by me though, a customer). The XML portion with the key looked like this:

```xml
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <X509Data>
        <X509Certificate>
FakeCertDataForThisPost
        </X509Certificate>
    </X509Data>
</ds:KeyInfo>
````

**Comment by pitbulk** [comment]
If the ds is defined, then X509Data and X509Certificate should have the ds:  prefix

**Comment by Chad-R-S** [comment]
Sounds like it was an issue with their IdP metadata in general then. I think what confused me is that looking at the SAML 2.0 spec, if references that the KeyInfo element as being prefixed by `ds`, and that seems to be a requirement I guess? though other KeyInfo references (such as in signing) it seems that the prefix is completely optional.
