### ISSUE TITLE
Usage of xmlseclib, why not composer require

### ISSUE THREAD

**Issue by ecsecta** [onelogin/php-saml#451]
Hi, Is there a reason why the xmlseclib is included as copy  and not added by composer require?
Are there any relevant changes made to the code of xmlseclib?
Thanks for an info on this!

**Comment by pitbulk** [comment]
Hi @ecsecta 

The 2.X branch is an old branch that I keep alive due to compatiblity.

If you are new to the toolkit, you should be using the 3.X branch who uses composer to handle its dependencies as you suggested.

**Comment by ecsecta** [comment]
Alright, thank you very much for the info and quick reaction!
