### ISSUE TITLE
Add AttributeName support in <Attribute />?

### ISSUE THREAD

**Issue by articque** [onelogin/php-saml#452]
I have a SAML response from Microsoft Azure AD and the Attribute contains "AttributeName" key instead of "Name"
It seems to be not supported.

In my example below, attribute "UPN" was not found when saml response is read :
```
  <Attribute AttributeName="UPN" AttributeNamespace="http://schemas.xmlsoap.org/claims">
    <AttributeValue>
      my_name@company.com
    </AttributeValue>
  </Attribute>

```
I use v3.4.1

**Comment by pitbulk** [comment]
AttributeName is not a standarized SAML Attribute
Standard values are Name, NameFormat and FriendlyName

Ref
-  http://www.datypic.com/sc/saml2/e-saml_Attribute.html
- https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf    2.7.3.1 Element <Attribute>

I see Azure AD normally offers Attributes with Name instead AttributeName.
See:  https://docs.microsoft.com/es-es/azure/active-directory/develop/reference-saml-tokens

Have you made a customization or something?
Can you clarify what are you using?

**Comment by articque** [comment]
The configuration has been modified in order to follow the standard value "Name"
And it's works now.

Thanks for the response. You can close the issue.
