### ISSUE TITLE
Session Expiration is not set using Azure as IDP

### ISSUE THREAD

**Issue by Michandrz** [onelogin/php-saml#455]
In the Joomla SAML I've been trying to get the IDP NotOnOrAfter, but it seens that it's not getting set within the library:
die(print_r($saml_lib)); yields:
```
...
[_sessionExpiration:OneLogin_Saml2_Auth:private] => 
...
[_lastAssertionNotOnOrAfter:OneLogin_Saml2_Auth:private] =>
...
```

it is being sent from the IDP:
```
            <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">awuS9SQRz3Vn0bONDjc1uXInbXKIkCzt_9-3E2svKd4</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="ONELOGIN_8d50678ef3309b28d7bb8c09caff029bacceaded"
                                         NotOnOrAfter="2020-12-10T13:36:27.595Z"
                                         Recipient="[redacted]"
                                         />
```

and again
```

        <Conditions NotBefore="2020-12-10T12:31:27.595Z"
                    NotOnOrAfter="2020-12-10T13:36:27.595Z"
                    >

```

**Comment by pitbulk** [comment]
The session expiration can be retrieved using the method [getSessionExpiration](https://github.com/onelogin/php-saml/blob/3.6.0/src/Saml2/Auth.php#L454) which get the value from the Response method [getSessionNotOnOrAfter](https://github.com/onelogin/php-saml/blob/370a5d9c8432ede5776f278edcdcf3b8e8212cc6/lib/Saml2/Response.php#L716) 

The time values you shared are not related to the session expiration time, but with the SAML Message.

**Comment by Michandrz** [comment]
getSessionExpiration returned null. If that's not correct time values, which in the message specify that?

**Comment by pitbulk** [comment]
SessionIndex and SessionNotOnOrAfter are attributes of the [saml:AuthnStatement](http://www.datypic.com/sc/saml2/e-saml_AuthnStatement.html) of the [saml:Assertion](http://www.datypic.com/sc/saml2/e-saml_Assertion.html) and both are available at the auth object, but are optional. If the IdP does not set them, means that the SP is free to set any time.

Even if the SessionNotOnOrAfter is provided by the IdP, depends on the SP implementation, to care of it or not.
