### ISSUE TITLE
Conflict on 2 demo1 project sessions are shared but in reality it should not be

### ISSUE THREAD

**Issue by ketanvekariya** [onelogin/php-saml#460]
Hello I had create 2 application app1 and app2 both contains php-saml. Both app has different configurations onelogin with saml test connector app advance. Now when I access demo1 of app1 and successful login if I am trying to access app2/demo1 it will automatically get logged in. Even both are different then it should not be get logged in

Sessions of the app1/demo1 is accessible in app2/demo1. I think this is the biggest issue. I don't want to make this session accessible on in each other. How can I prevent this?

**Comment by pitbulk** [comment]
I guess you are hosting both app1 and app2 using the same domain and server.
Something like  http://example.com/app1/demo1   and  http://example.com/app2/demo1

If you review the code, demo1/index.php [registers user data](https://github.com/onelogin/php-saml/blob/master/demo1/index.php#L86) in the global $_SESSION parameter.  app1 and app2 shares the session scope, so what is registered in app1 is available in app2.

Stackoverflow:  
- https://stackoverflow.com/questions/854105/multiple-php-sessions
- https://stackoverflow.com/questions/9153716/sharing-session-variables-between-multiple-subdomains/15219421

**Comment by ketanvekariya** [comment]
@pitbulk thanks for your reply. Really appreciated. But suppose there is case where 2 demo1 will reside on same domain then how it will be possible to manage both in single domain


xyz.com/onelogin/index.php
xyz.com/onelogindekstop/index.php

**Comment by ketanvekaria** [comment]
@pitbulk I changes all the session variables on both apps for example.

For App1
$_SESSION['samlUserdata1'] = $auth->getAttributes();
            $_SESSION['samlNameId1'] = $auth->getNameId();
            $_SESSION['samlNameIdFormat1'] = $auth->getNameIdFormat(); likewise for rest of all sessions vars
For App2
$_SESSION['samlUserdata2'] = $auth->getAttributes();
            $_SESSION['samlNameId2'] = $auth->getNameId();
            $_SESSION['samlNameIdFormat2'] = $auth->getNameIdFormat(); likewise for rest of all sessions vars


But still it's conflicting.

**Comment by pitbulk** [comment]
Try to define the session.cookie_path as well
```
<?php 
    session_name("app1");
    ini_set("session.cookie_path","/app1/");
    session_start();
?>
```

**Comment by ketanvekaria** [comment]
> Try to define the session.cookie_path as well
> 
> ```
> <?php 
>     session_name("app1");
>     ini_set("session.cookie_path","/app1/");
>     session_start();
> ?>
> ```

Sure let me try that

**Comment by jewelsd1967** [comment]
What in the hell is this? On Jan 12, 2021 03:26, ketanvekaria <notifications@github.com> wrote:

Try to define the session.cookie_path as well
<?php 
    session_name("app1");
    ini_set("session.cookie_path","/app1/");
    session_start();
?>


Sure let me try that

**Comment by ketanvekaria** [comment]
Still there is no luck
