### ISSUE TITLE
Issuer Url contains newLine and space chars

### ISSUE THREAD

**Issue by MarcoBevilacqua** [onelogin/php-saml#463]
Hi, 

creating an AuthnRequest with [spid/laravel](https://github.com/italia/spid-laravel/)  package produces a malformed value in the xml because of this particular snippet of code (that was patched a couple of months ago [here](https://raw.githubusercontent.com/italia/spid-laravel/master/patches/php-saml-3.3.0-spid.patch)) in AuthnRequest.php 

![image](https://user-images.githubusercontent.com/3083440/106291408-de810a00-624b-11eb-920e-94450c4cc4db.png)

Not being on a single line adds some \n and whitespaces into the text value of the tag, causing SAML validation for italian SPID to fail 

![Immagine 2021-01-29 160748](https://user-images.githubusercontent.com/3083440/106291676-3a4b9300-624c-11eb-920a-68d669c3b091.png)

Issuer and entityID URLs are the same, but in the SAML request this is not well formed and fails validation.

Is there anyone that already faced this kind of issue? 

Thanks in advance

**Comment by pitbulk** [comment]
> Not being on a single line adds some \n and whitespaces into the text value of the tag, causing SAML validation for italian SPID to fail

Where are those \n or whitespaces added? are in the saml:Issuer content?

As you see [here](https://github.com/onelogin/php-saml/blob/3.6.0/src/Saml2/AuthnRequest.php#L164): 
```
    <saml:Issuer>{$spEntityId}</saml:Issuer>
```
No extra space or whitelines are added to the body, only the value of $spEntityId
and there is no format, so I don't think I that Issuer you shared belong this toolkit.


In the patch you introduced, you should be adding
```
<saml:Issuer
    NameQualifier="{$spEntityId}"
    Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
>{$spEntityId}</saml:Issuer>
```
instead of
```
<saml:Issuer
        NameQualifier="{$spEntityId}"
        Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">
        {$spEntityId}
    </saml:Issuer>
```
to avoid the issues you are experiencing.

**Comment by MarcoBevilacqua** [comment]
Thank you @pitbulk, after some extra check I realized that the issue is not in this package but just in the linked patch from another repo. Sorry for bothering, I just assumed the codebase being identical, which is not. 

thank you again, i will close the issue
