### ISSUE TITLE
Wrong third parameters for the getSelfRoutedURLNoQuery in Utils.php

### ISSUE THREAD

**Issue by arthurju** [onelogin/php-saml#467]
Hello,

I'm facing a bug on Utils.php

The code :
`$pos = strpos($selfRoutedURLNoQuery, "?");`
`if ($pos !== false) {`
`$selfRoutedURLNoQuery = substr($selfRoutedURLNoQuery, 0, $pos-1);`
`}`

I'm using this bundle on a Nginx web server routing 2 symfony applications.
On my first app I log my users with SSO and the remote IDP return to the URL I defined => myproject.com/app/saml/acs.
The return request go through the function getSelfRoutedURLNoQuery and at the line 645 the function check if there is a "?" in the request (which in my conf NGINX does).
But if a "?" is found, the route is goes through substr and on my side there is a mistake with the third parameter $pos-1 which remove one char before the ?. So instead of have a route like _myproject.com/app/saml/acs_ I have a route like that : _myproject.com/app/saml/ac_
In my opinion is a bug and someone should fix into `$selfRoutedURLNoQuery = substr($selfRoutedURLNoQuery, 0, $pos);`

**Comment by pitbulk** [comment]
This method tries to get a substring from selfRoutedURLNoQuery if an ? appears

If you have 
```
myproject.com/app/saml/acs?xxxxx
```
then it calculates the position of ?, and then get the substring before the ?, so
```
myproject.com/app/saml/acs
``` 

Can you add a debug at this method and print before and after the line of the 
```
$selfRoutedURLNoQuery = substr($selfRoutedURLNoQuery, 0, $pos-1);
```
what values has $pos and $selfRoutedURLNoQuery?

**Comment by arthurju** [comment]
Indeed I have an uri like myproject.com/app/saml/acs?xxxxx.
The strpos ($pos) return 34 for my 60 length uri.
strpos return the position of the "?" substr start at 0 and must finish juste before the "?". So it must finish at the position 34 (at the $pos position). I don't understand why there is a minus one at the $pos which remove the last char before the ?
At the end the var $selfRoutedURLNoQuery return myproject.com/app/saml/ac and not myproject.com/app/saml/acs cause of the minus one after the $pos.

**Comment by pitbulk** [comment]
Feel free to update the unit test with your case

**Comment by dovbeta** [comment]
Thanks @pitbulk for this fix. Coult it be added to v3 too?

**Comment by pitbulk** [comment]
It is at 3.6.1 branch already: https://github.com/onelogin/php-saml/commits/3.6.1

**Comment by Joeb454** [comment]
@pitbulk we're impacted by this issue too, when do you see 3.6.1 being available as a release?

**Comment by pitbulk** [comment]
Versions 2.19.1, 3.6.1 and 4.0.0 released today.

Let me know if you experience any issues.

**Comment by Joeb454** [comment]
Amazing, thank you!
