### ISSUE TITLE
Make SP acs url optional

### ISSUE THREAD

**Issue by kboumedal** [onelogin/php-saml#470]
![image](https://user-images.githubusercontent.com/8987416/115268104-2ff9b080-a13a-11eb-819c-602cd5abc432.png)

In the [documentation](https://docs.microsoft.com/fr-fr/azure/active-directory/develop/single-sign-on-saml-protocol#authnrequest), the AssertionConsumerServiceURL parameter is optional.

**Comment by pitbulk** [comment]
Is optional to specify the ACS URL on the AuthNRequest since the IdP already has it stored on its side.
