### ISSUE TITLE
User was not found in local DB

### ISSUE THREAD

**Issue by pretendent0** [onelogin/php-saml#476]
Hey, I'm facing an issue where I'm successfully logged in with SSO user, but there's no currently user created in my database. Now it throws an 500 error. After logged in with SSO and if there's no user in my database i want to redirect user to error page with button that redirects it back to SSO login page. The issue is when i redirect user to my error page i don't have logout request URL  which is being generated here _Utils::redirect()_ :
   ```
if ($stay) {
            return $url;

        }
        header('Pragma: no-cache');
        header('Cache-Control: no-cache, must-revalidate');
        header('Location: ' . $url);
        exit();
    }
```
and i can't logout with logged in (IDP user).  Is there a way o save a generated URL to put it on the button that will send request to IDP?

**Comment by pitbulk** [comment]
login and logout methods have a $stay parameter tha rather than execute the Redirect, generates the URL with the SAML and other parameters.
