### ISSUE TITLE
Load IdP metadata

### ISSUE THREAD

**Issue by zer0uno** [onelogin/php-saml#479]
Few questions:
1. Is it possible to load an IdP metadata instead of having to configure the IdP information by hand in the `settings.php`?
2. Is it possible to declare more IdPs in the `settings.php`?

**Comment by kynx** [comment]
Sure. The setting are just an array that gets passed to the `OneLogin\Saml2\Auth` constructor. They can come from anywhere. Quite how you do it is down to your application and needs, but the demo code in the repo should get you started. In our case we store different `idp` configurations in the DB (securely, ahem) and have a UI where different customers can upload the IdP metadata and download the SP metadata.

Have a look at `OneLogin\Saml2\IdPMetadataParser::parseXML()` to turn the metadata xml into the appropriate array structure, and store that however you want.

Good luck!
