### ISSUE TITLE
IdPMetadataParser sets ServiceProvider data

### ISSUE THREAD

**Issue by Thorry84** [onelogin/php-saml#481]
In OneLogin_Saml2_IdPMetadataParser in the parseXML function the NameIdFormat is read from the XML and set into the result metadata array. However instead of it being set in the idp key in the array, it's set in the sp key instead. 

https://github.com/onelogin/php-saml/blob/88c5e59eb1bc65760f63edc57b502cc939d0d5b9/lib/Saml2/IdPMetadataParser.php#L192

Depending on the configuration, this causes a notice or worse. At the very least, the IdP parser shouldn't set anything about the SP?

**Comment by pitbulk** [comment]
The toolkit sets the value stored in ['sp']['NameIDFormat'] while building the Subject/NameId of the [AuthNRequest](https://github.com/onelogin/php-saml/blob/3.6.1/src/Saml2/AuthnRequest.php#L68).

The SP is able to use only the NameIdFormat that the IdP supports, so makes sense at the metadata parser to fill the toolkit sp setting with such value.

**Comment by Thorry84** [comment]
Can you explain this? The IdentityProvider config shouldn't have anything to do with the ServiceProvider config?
In my case my ServiceProvider communicates with a lot of different IdentityProviders, why would the metadata from one of these change the way my ServiceProvider is configured?

It also seems very strange to me, to configure the ServiceProvider and then have part of that configuration overridden by something that seems to be made for the IdentityProvider? The array key 'sp' isn't initialized in the code, which made me think this code only works if the ServiceProvider has been configured in advance?

If the NameIDFormat isn't configured on the ServiceProvider, wouldn't the default work well in every instance? Why is this needed?

**Comment by pitbulk** [comment]
Is true that you can use 1 SP - Multiple IdP by loading each time the right SP-IdP configuration, but the toolkit right now is designed to work 1 SP - 1 IdP.  That said, the IdPMetadataParser is oriented to fill the settings with the use of parseXML and 
injectIntoSettings.

With that in mind, the use of those method will retrieve the first supported NameIdFormat by the IdP and use it.

If you don't want to modify the already configured NameIDFormat, You can simply execute
```
unset($metadataInfo['sp']['NameIDFormat']);
```
before the call to injectIntoSettings

**Comment by Thorry84** [comment]
Is it required to have the NameIDFormat for the ServiceProvider match with the IdentityProvider? The parser seems to pick the first one available, unless a preferred one is supplied, then it attempts to pick that one and falls back to the first one if the preferred one isn't found.

The code doesn't initialize $metadataInfo['sp'] to be an array, like it does for $metadataInfo['idp'] on line 122. This made me think the code was wrong.

**Comment by pitbulk** [comment]
If the SP sends an AuthNRequest with a NameID which Format is not supported by the IdP the IdP could reject such AuthNRequest.

Is true that 'sp' is not initialized and it should.

Each IdP can have each own security requirements, NameIDFormat supported, request the SAML Messages sent by the SP to be signed .. so at the end, you don't need only to store the IdP data, but also those extra info.

**Comment by Thorry84** [comment]
Alright, thanks for all the info. I think I'm all set and now understand why the code was written like that. Came across as pretty weird and with the 'sp' key not being initialized I got confused and thought it was a mistake.

A more elegant solution would be for this parameter to be included in the IdentityProvider settings array for all the supported formats. Then in the ServiceProvider config a setting could be used if the SP prefers a certain format (optionally) and could throw an error if the requested format isn't included in the array of supported formats. That way the data about the IdentityProvider and the ServiceProvider gets a more clean separation.

But the current setup works fine and in the 1 SP - 1 IdP scenario it's not really an issue.

Thanks again for your time and effort!
