### ISSUE TITLE
What exactly is base path?

### ISSUE THREAD

**Issue by dakur** [onelogin/php-saml#483]
Hi, could you please elaborate a bit what exactly do you mean by `base path`? I know from docs how to set or modify it, however I don't know what it actually represents.

The problem is, that in our application we send SAML request from `/sign-in/somecompany/saml` URL and retrieve response at `/sign-in/somecompany/saml/finish`. But when the response comes and strict mode is enabled, it fails with `The response was received at /finish instead of /sign-in/somecompany/saml/finish`.

That was with no base path set. I've found out that setting base path to `/sign-in/somecompany/saml` fixes this issue, yet I'm not quite sure what this base path represents and if it has some other consequences. E.g. what if I use URL `/sign-in/somecompany/saml/request` for sending requests and `/sign-in/somecompany/saml` is not present in my app at all?

So the question is – what base path means? Is it just some kind of namespace?

Thank you for clarification.

**Comment by pitbulk** [comment]
FInd here an elaborate description of what basePath means:
https://swagger.io/docs/specification/2-0/api-host-and-base-path/
