### ISSUE TITLE
Support ForceAuthn attribute of AuthnRequest

### ISSUE THREAD

**Issue by mattzuba** [onelogin/php-saml#49]
Our organization has a need to use the ForceAuthn attribute along with Okta's support for it for some of our applications, but it looks like this support is missing from OneLogin_Saml2_AuthnRequest.

Any chance this can be added?

ref: https://spaces.internet2.edu/display/InCFederation/2013/12/08/ForceAuthn+or+Not

```
$ grep -rn ForceAuthn .
./lib/Saml2/schemas/saml-schema-protocol-2.0.xsd:163:                <attribute name="ForceAuthn" type="boolean" use="optional"/>
./tests/data/requests/authn_request.xml:1:<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_ONELOGIN103428909abec424fa58327f79474984" Version="2.0" IssueInstant="2014-11-13T11:39:34Z" ForceAuthn="false" IsPassive="false" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="http://example.com/acs">
```

**Comment by pitbulk** [comment]
Hi  mattzuba,

I decided not supporting the ForceAuth parameter since no many IdPs handle it because I don't don't want to add more parameters to the login / AuthNRequest constructor.   I wanted to keep the toolkit simple.

I will review your case.

**Comment by mattzuba** [comment]
Thanks, we'd appreciate a review of it.  I could work around it by extending the OneLogin classes and overloading the login method if needed since I've already created a Laravel Service Provider for it, but if this could be an undocumented feature, that'd be awesome!

**Comment by pitbulk** [comment]
I implemented your required feature.

**Comment by mattzuba** [comment]
Fantastic!  You're awesome!
