### ISSUE TITLE
NameIDFormat never used

### ISSUE THREAD

**Issue by zer0uno** [onelogin/php-saml#490]
As far as I saw in the code, it is possible to specify a `NameIDFormat` in the settings but the code never uses the value defined.

This is what `Saml::getSPMetadata()` does:

```
<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
```

This is what `AutnRequest::generateXml()` does:

```
<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" />
```

As you can see `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` is always used, nevertheless `Settings::_addDefaultValues()` does:

```
// Related to nameID
if (!isset($this->_sp['NameIDFormat'])) {
  $this->_sp['NameIDFormat'] = Constants::NAMEID_UNSPECIFIED;
}
```

**Comment by pitbulk** [comment]
```
This is what Saml::getSPMetadata() does:
<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>
```

Where you saw that?

The metadata generator[ takes care of NameIDFormat](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Metadata.php#L163) reading it from SP settings:
```
<md:NameIDFormat>{$sp['NameIDFormat']}</md:NameIDFormat>
```

The AuthNRequest also [takes care of the NameIDFormat provided](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/AuthnRequest.php#L58)
```
$nameIdPolicyStr = '';
        if ($setNameIdPolicy) {
            $nameIDPolicyFormat = $spData['NameIDFormat'];
            if (isset($security['wantNameIdEncrypted']) && $security['wantNameIdEncrypted']) {
                $nameIDPolicyFormat = OneLogin_Saml2_Constants::NAMEID_ENCRYPTED;
            }

            $nameIdPolicyStr = <<<NAMEIDPOLICY
    <samlp:NameIDPolicy
        Format="{$nameIDPolicyFormat}"
        AllowCreate="true" />
NAMEIDPOLICY;
        }
```

Not sure what code are you reading, but does not belong php-saml
