### ISSUE TITLE
unable to get $auth->getAttributes() data after login

### ISSUE THREAD

**Issue by shaikHanumanbabu** [onelogin/php-saml#491]
I successfully download this folder and integrated it. it always showing empty object when I call this function **$auth->getAttributes()** but **$auth->isAuthenticated()** shows true. how can I resolve this issue?

**Comment by pitbulk** [comment]
If the SAMLResponse does not contain an AttributeStatement element, then the getAttributes method will provide you an empty array.

Make sure you configure properly the IdP to release the attributes your app requires.
