### ISSUE TITLE
support for aes128-gcm

### ISSUE THREAD

**Issue by banananjiz** [onelogin/php-saml#497]
Is it possible to add aes128-gcm support? xmlseclibs are supporting it since version 3.1.0 (released in April 2020), php-saml is still using 3.0.4. Is there a special reason, why it was not updated?

**Comment by pitbulk** [comment]
3.X and 4.X branches [uses](https://github.com/onelogin/php-saml/blob/3.6.1/composer.json#L19) xmlsec 3.1.1
and GCM support was already added:
https://github.com/onelogin/php-saml/commit/7b4d4a6df94a782b4688ebb3d9c6a1334258376c
