### ISSUE TITLE
Some notes on ADFS as an SAML providor

### ISSUE THREAD

**Issue by CharlieCarisi** [onelogin/php-saml#498]
Hey, I've been trying to intergrate Snap-it with ADFS recently, and the user's manual is not very clear with ADFS claim transform rules. After testing and trying for a month, I found out that I have to add an "transform incoming claim" rule after an "send LDAP attribute as a claim" rule, otherwise snap-it will give an error 500. Just leave tip for anyone having a similar issue.

**Comment by pitbulk** [comment]
Have you provided such info to Snap-it team?  I guess they would like to catch the 500 and instead provide to the user an informative error.

Closing here, this is very specific to be registered in this generic implementation
