### ISSUE TITLE
minor doc error, OneLogin_Saml_Auth should read OneLogin_Saml2_Auth

### ISSUE THREAD

**Issue by xmikew** [onelogin/php-saml#50]
In the README.md

`OneLogin_Saml_Auth` is referenced in code example under the "Initiate SSO" subtitle. I believe it should read 'OneLogin_Saml2_Auth' -- at least that is when it started working for me.

I notice there is a OneLogin_Saml_Auth class, but its in lib/Saml, not lib/Saml2.

Thanks much.

**Comment by xmikew** [comment]
The code section right under the originally referenced one references `OneLogin_Saml_Auth` as well.

**Comment by pitbulk** [comment]
Thanks, will be fixed in the next commit.
