### ISSUE TITLE
where can I find the metadata

### ISSUE THREAD

**Issue by raayyaa** [onelogin/php-saml#501]
Hello,

I am trying to generate the metadata file, I have to indicate the parameters in the metadata.php file?
After that where can I find the metadata?
I thank you for your help

**Comment by pitbulk** [comment]
You add the SP info on its [settings file](https://github.com/onelogin/php-saml/blob/master/settings_example.php#L20), then the toolkit will generate the SP Metadata XML, you can inspect the metadata.php file to see how it generates it.

**Comment by raayyaa** [comment]
Hello,

Thank you for your answer, but the xml file has not been generated yet. I have some questions if you can help me on it. Thank you

- do I have to fill in the information of the idp too? 
they are already present in the x509 file that is provided by the idp, right?

- what is the entity ID of the SP? 
it's the link of my application right?
a forum says it's a link to the metadata file, but the application doesn't have a URL to access the metadata.

Also, where can i find this url "URL Location where the <Response> from the IdP will be returned"
![image](https://user-images.githubusercontent.com/38456239/149666565-1eea4f4c-3d50-4dcf-b6b3-2153aa91305c.png)


and this one too:
![image](https://user-images.githubusercontent.com/38456239/149666581-a75ad592-2e53-43a2-a7c4-9aea2e84de82.png)

Thank you for your help!
