### ISSUE TITLE
php-xml should be listed as depedency

### ISSUE THREAD

**Issue by xmikew** [onelogin/php-saml#51]
See title.

Thanks much!

- Mike

**Comment by pitbulk** [comment]
what OS are you using?

**Comment by xmikew** [comment]
Hi! I'm using RHEL v5. I had to yum update php53-XML to get DOMDocument etc. Maybe not a problem on a more modern OS?  

Thanks!

**Comment by pitbulk** [comment]
yeah, I think that in new versions php-xml is installed by default.

**Comment by xmikew** [comment]
Yes even modern RedHat variants still distribute a php-xml rpm that you must install. RHELv7 for example still has a php-xml rpm. Just depends on the distro you are running as far as Linux goes.

Thanks.

**Comment by pitbulk** [comment]
Ok, I updated the documentation.
