### ISSUE TITLE
some questions about a pulled request?

### ISSUE THREAD

**Issue by zbcchen** [onelogin/php-saml#518]
Hi 
I have pushed an improvement PR, and it has been merged, but I don't see this change on my composer dependence. So I want to know how to merge my PR to the composer package. That would be great if you could let me know.

**Comment by zbcchen** [comment]
the PR is here https://github.com/onelogin/php-saml/pull/510

**Comment by bzvestey** [comment]
Yes, as the composer package is deployed manually, so we will have to release another version to get the changes up there.

For some additional information for me, what version of the package are you currently pulling from composer?

**Comment by bzvestey** [comment]
hmmm, we are going to need to get your changes into the `4.x-dev` branch for it to show up in that version, as we had different branches for the versions supporting different version ranges of PHP.  The `master` branch is specifically for version 2.x.  I know this is a little confusing, and I am still learning how this repo is setup myself.

All that being said, here are the steps. I can start working on this stuff hopefully next week:
1. Move the updated code to the `4.x-dev` branch.
2. Create a new release and upload it to composer.

**Comment by zbcchen** [comment]
I will fix move my changes to the branch as soon as possible,
about the `4.x-dev` branch. I have some confusing, why can the branch not pass the tests?  If you have no time to resolve them,
when I move my changes, I will resolve them at the same time.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/90187037/156481377-1e5f62e4-10dd-4ec9-840d-b633e0fad44f.png">

**Comment by zbcchen** [comment]
I have created a new pr, and it has been merged into the branch which is composer uses.
