### ISSUE TITLE
Namespaces not referenced when processing SAMLResponse causing 'invalid_response' error

### ISSUE THREAD

**Issue by xmikew** [onelogin/php-saml#52]
My IDP returns different names of the XML SAML namespaces than what php-saml expects
For example, my responses look like:

`<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://host.example.com/saml-test.php" ID="myid_klajdlfkjaslkdjf" InResponseTo="ONELOGIN_lkajdlfkjasdlkfj" IssueInstant="2015-01-12T20:15:28.659Z" Version="2.0">`

The Assertion namespace is:
`xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"`

My responses fail to validate because the namespaces are hard-coded. For example, in the Auth class:
```
    /**
     * Verifies that the document has the expected signed nodes.
     *
     * @return bool
     */
    public function validateSignedElements($signedElements)
    {
        if (count($signedElements) > 2) {
            return false;
        }
        $ocurrence = array_count_values($signedElements);
        if ((in_array('samlp:Response', $signedElements) && $ocurrence['samlp:Response'] > 1) ||
            (in_array('saml:Assertion', $signedElements) && $ocurrence['saml:Assertion'] > 1) ||
            !in_array('samlp:Response', $signedElements) && !in_array('saml:Assertion', $signedElements)
        ) {
            return false;
        }
        return true;
    }
```

In the above code, the namespaces being used are saml and samlp. If I look at my `signedElements` array, I find `saml2:<element>` and `saml2p:<element>`.  Doing a cursory glace of the code, I don't see namespaces being taken into account but, I'm not experienced with DOMDocument, so maybe I'm missing it.

The first exception throw thus far for this error with debugging turned on is:

`Found an unexpected Signature Element. SAML Response rejected` which is what happens with validateSignedElements returns false, which in my case it does. There are lots of direct references to saml and saml2 in the xpath used in the code (not just in this function).

When I print `$signedElements` I get:

`array(2) { [0]=> string(15) "saml2p:Response" [1]=> string(15) "saml2:Assertion" }`

Thanks much,

\- Mike

**Comment by xmikew** [comment]
This is my current plan, pull out the namespaces in the Response constructor and then modify all the xpath to use this parsed namespaces defaulting to 'saml' and 'samlp'

Note: I would provide a pull request but I have not the PHP xp yet with PHP testing to get some proper tests passing etc. If you like the changes below for example, I'd be happy to provide a pr of the modifications if you think this is a worthy change.

Thanks as always,

\- Mike

```
    public function __construct(OneLogin_Saml2_Settings $settings, $response)
    {
        $this->_settings = $settings;

        $this->response = base64_decode($response);

        $this->document = new DOMDocument();
        $this->document = OneLogin_Saml2_Utils::loadXML($this->document, $this->response);
        $this->_samlPrefix = 'saml';
        $this->_samlpPrefix = 'samlp';
        $samlpNS = "urn:oasis:names:tc:SAML:2.0:protocol";
        $samlNS= "urn:oasis:names:tc:SAML:2.0:assertion";
        $samlpPrefix = $this->document->lookupPrefix($samlpNS);
        $samlPrefix = $this->document->lookupPrefix($samlNS);
        $assertionElements = array();

        // Quick check for the presence of EncryptedAssertion
        $encryptedAssertionNodes = $this->document->getElementsByTagName('EncryptedAssertion');
        if ($encryptedAssertionNodes->length !== 0) {
            $this->decryptedDocument = clone $this->document;
            $this->encrypted = true;
            $this->_decryptAssertion($this->decryptedDocument);
            $assertionElements = $this->decryptedDocument->getElementsByTagName('Assertion');
        } else {
          $assertionElements = $samlPrefix = $this->document->getElementsByTagName('Assertion');
        }

        if (!empty($assertionElements)) {
          $samlPrefix = $assertionElements->item(0)->lookupPrefix($samlNS);
        }

        if (isset($samlPrefix)) {
          $this->_samlPrefix = $samlPrefix;
        }
        if (isset($samlpPrefix)) {
          $this->_samlpPrefix = $samlpPrefix;
        }
```

**Comment by pitbulk** [comment]
@xmikew, what version of the php-saml toolkit are you using? maybe the packagist?

I think we solved this issue here: https://github.com/onelogin/php-saml/issues/43

As you can see in trunk the code that you posted does not exist anymore:
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Response.php#L526

I will release a new 2.3.0 version of the php-saml toolkit tomorrow and update the version of packagist. Sorry for inconvenience.

**Comment by xmikew** [comment]
Ah! I was just using the latest release which is v2.2.0. I should have checked master! Sorry I'll download master and see if that fixes my problems. I'll close this out or update it tomorrow when I get back in front of my code. Thanks!
