### ISSUE TITLE
Signature validation failed. SAML Response rejected

### ISSUE THREAD

**Issue by yuryfilippovich** [onelogin/php-saml#537]
IP send me next SAMLResponse:
<?xml version="1.0" encoding="UTF-8"?><saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="" ID="_35db3faeafd8032c3f049f126146e16a" InResponseTo="ONELOGIN_d2b286c66fe92f7b447967cebe5173337c22fcc3" IssueInstant="2022-10-31T03:57:36.040Z" Version="2.0"><saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">xxxx/shibboleth</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/><ds:Reference URI="#_35db3faeafd8032c3f049f126146e16a"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512"/><ds:DigestValue>JNQYHSrYdhWnVFC5jLOhYcEUyDtmF9Ea5OLrbVooVcSfqkmzhZioPw0MNBAxa2+cnvH2ldPePLFLJcR1sSX/iw==</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>evgUTaBsWeXlcVLlp6LVOgwO6QJXmjCRudjEqOz8DAioGn2eIEw3f+09V/wq+gypjbV2Pd9AGpoTv+SB9gmU7gnvyjV83b5+LTWtsQXumH+iCoN+h1dixBp0BP7p7Qk+ewE5vYyWigtergMh9sJVlBhV/Bz+7fPQQiodFl1Yp7fsfQqQJsT0vRqHU7FlrUohsFQ5U9OcVIpx2qX54EOootLSDJJbWS9v+Onk0dtCYXI86PHcvNtapb+M6VYI26aKWqmMyUs2bSOvtvtIM7GZdrCgNLJPmmFhkyn/Xv/K6QJxmiU4CEeW2fvBJeIYqO/KN0QNbBz1cMezt4die6p8/g==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIHIzCCBgugAwIBAgIQf8lAPPvGFvR0pKzV8eNO7jANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQG
EwJKUDElMCMGA1UEChMcU0VDT00gVHJ1c3QgU3lzdGVtcyBDTy4sTFRELjEkMCIGA1UEAxMbTklJ
IE9wZW4gRG9tYWluIENBIC0gRzcgUlNBMB4XDTIyMDQwMTA5MjM0NVoXDTIzMDUwMjA5MjM0NVow
cDELMAkGA1UEBhMCSlAxDjAMBgNVBAgTBU9zYWthMRIwEAYDVQQHEwlTdWl0YS1zaGkxGTAXBgNV
BAoTEE9zYWthIFVuaXZlcnNpdHkxIjAgBgNVBAMTGWdrLWlkcC5hdXRoLm9zYWthLXUuYWMuanAw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/vwdE7BQARPRbVB5cWeZIDLIdIYogkg+V
KJ1eWeXYxPoeuv9Wzys3g/FqUsKUbDRyGgScD0c8ScaX75vtWO6qvYby1aogxSG/6gpLb1t+Xq16
b367OnqbDTKqyoVkKuqkHif98d4YTqHG9q8Niqm6TynYyh/K0PtxzB1Q2FWzFAioHdTfNyDRWLWQ
45Pr45b7h07bmhXf4O8iY/g9a/PuXLVuvt+yvUj9ivkh5tXmTrzQH/P4eKvJH4vdoA9BE7qpWiNp
x7GmoYdwzbl9W7z+Rv1VIg2GopSFnsb00SKJURMNtlhmueqYP1fuY6uF7LiIwSZ2Dsha825wRhNG
f9k9AgMBAAGjggPNMIIDyTAfBgNVHSMEGDAWgBSwLuVR7fxKz6OH8ROQdi2djpSh4zCBigYIKwYB
BQUHAQEEfjB8MEoGCCsGAQUFBzAChj5odHRwOi8vcmVwbzEuc2Vjb210cnVzdC5uZXQvc3BwY2Ev
bmlpL29kY2E0L25paS1vZGNhNGc3cnNhLmNlcjAuBggrBgEFBQcwAYYiaHR0cDovL25paWc3cnNh
Lm9jc3Auc2Vjb20tY2VydC5qcDAkBgNVHREEHTAbghlnay1pZHAuYXV0aC5vc2FrYS11LmFjLmpw
MF0GA1UdIARWMFQwSAYKKoMIjJsbboFWAzA6MDgGCCsGAQUFBwIBFixodHRwOi8vcmVwbzEuc2Vj
b210cnVzdC5uZXQvc3BwY2EvbmlpL29kY2E0LzAIBgZngQwBAgIwHQYDVR0lBBYwFAYIKwYBBQUH
AwEGCCsGAQUFBwMCME0GA1UdHwRGMEQwQqBAoD6GPGh0dHA6Ly9yZXBvMS5zZWNvbXRydXN0Lm5l
dC9zcHBjYS9uaWkvb2RjYTQvZnVsbGNybGc3cnNhLmNybDAdBgNVHQ4EFgQUZHIVIyFjZLyht+IQ
PTZaSyzp0OkwDgYDVR0PAQH/BAQDAgWgMIIB9QYKKwYBBAHWeQIEAgSCAeUEggHhAd8AdwDoPtDa
PvUGNTLnVyi8iWvJA9PL0RFr7Otp4Xd9bQa9bgAAAX/keUEsAAAEAwBIMEYCIQCJ0n5skJqfzalQ
MVjHlAjLodAgwk+BB6DeveI/8WV0nQIhAIArIcVCNepT/sNuQHVu0Ov+20JuXJG9rCY6HgFbqdkH
AHUArfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvcgooAAAF/5HlG2gAABAMARjBEAiA/9+Xk
jMKUMyMW0sGgZGq9y9L1s33imywYYnW4PIa1zgIgXLldB0pj3fIiwLl2MGNykE5G2jnWB4olNSMp
+PvW+f8AdgCzc3cH4YRQ+GOG1gWp3BEJSnktsWcMC4fc8AMOeTalmgAAAX/keUlLAAAEAwBHMEUC
IARR2chNHP2gFM49L6J6zfSaEMJySWrPlaUcOxD7oE3sAiEA8zAR8q0zTNgvuMS4x813b3zAYA8n
3jkpnsfiJjwdQxIAdQB6MoxU2LcttiDqOOBSHumEFnAyE4VNO9IrwTpXo1LrUgAAAX/keUurAAAE
AwBGMEQCIBgm2kdfX5W2DYdxkHSgTPqWPPl1kUT61MsNUc+A9pRNAiALvbrlB61spYwtN72S2Njo
LL4qDqWOn1iyV9QFJ1ry+TANBgkqhkiG9w0BAQsFAAOCAQEAbAMwLlLu+uHIsCA/RiRn4I9VMSmT
RlXkS/iNQz5pRkqd0jSIyBXMSoXhpdPaJJULPvR2jNbGYDoiSmZ3i3WhAcOcinzNRfmIBr3V3ZgJ
YRnWBO5iGXk/o1HmxgGVvd/19Gprn2FN/zxHLRtRmEEEIJ8qj+uhCVS1mxE63RRPXDm+fvN8RQPW
dCAuSnxtg7yVzj7eZhOd/YG8/uyKSu36oQvE1NHb63fW8j+pGZ1SMITV5Ouow/Z3eCbNGy11Ejh2
RDg4XtWJoocCMBCGmoXWpuTEPCNTJ8NtTvYLYWaLRene9HMADA21vNHeXX1Snd3tQNiui8zK/9VF
LQniowz3uA==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2p:Status><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></saml2p:Status><saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_f49b6510d94c8495b9c91861a66ee2d2" Type="http://www.w3.org/2001/04/xmlenc#Element"><xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes128-gcm" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"/><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><xenc:EncryptedKey Id="_93624c858af3ec1c8f230e4e6571c55b" Recipient="https://www.jove.com/shibboleth" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><xenc:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#rsa-oaep" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" xmlns:ds="http://www.w3.org/2000/09/xmldsig#"/><xenc11:MGF xmlns:xenc11="http://www.w3.org/2009/xmlenc11#" Algorithm="http://www.w3.org/2009/xmlenc11#mgf1sha1"/></xenc:EncryptionMethod><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIC4jCCAcqgAwIBAgIJAMmZMgpgR98FMA0GCSqGSIb3DQEBBQUAMBQxEjAQBgNVBAMTCWpvdmUt
c2l0ZTAeFw0xNDA4MjYxOTI5NDVaFw0yNDA4MjMxOTI5NDVaMBQxEjAQBgNVBAMTCWpvdmUtc2l0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJpYESYD4dYzXNtXUSDK3W59M7Mr5MdC
Zxbr8I508aQkXIDwjBNqtr6a7HatHer5Zr7FU8jaddsO5hgFaOwdN/5EZfqpSDdS6YCop7Y7b5Mu
KW2IXQqyl3Uf6NVBuFb24x8Jq9PzmpWXE0O+qiRubp9kVR2DsIv5QJcAmMJn46jAyJefqOTTtoeO
T9PHHOuOd21k8zRmeFQq2hYgL+8pkVN6KvJMSR8+a7V0xL4TinO2NLgU+REPkh8dZwKkv3YiX5Zy
4NHsn8BkdNwlTkB2Opd90ociYnvvWjsLcM0jHLDs+Kg1BBqbtFFE2AivWioIclBIAGURdZnHyn5b
viGp8E0CAwEAAaM3MDUwFAYDVR0RBA0wC4IJam92ZS1zaXRlMB0GA1UdDgQWBBQJINSSKzlDshwk
hXdHrjR2mNn+zjANBgkqhkiG9w0BAQUFAAOCAQEAhrtgkBsbRvQLDtyhGbtMPbTTlGDHrnOXUFx5
TqqyGCqYgp86n7awj2kUypRW27QZr6a7LnyznASyXWWak0JXb90ZvPMR8bpvPEYR1HbGVQ94/+Kl
OtsR3SjP0swPElIYm9Ff3oNaM0uh3YAi9qhB/ZrTJmXcTDLZDgC3jOApjNV2nvtjb2Bu0ysNyKyJ
d48ZF72SR5zQKq4S7OcbHtttrk0/xeEHomt+Xw0PzB265Vr14OZoAO91jEvPdU4byrEQ+k+7huxT
c6arI5cagwL8GnpH6I0M6Ouj8T4RTmXHKWseJDXYCc9WNlN/qa6mttqxIIeSvf7w0qq4buQC7/jH
WQ==</ds:X509Certificate></ds:X509Data></ds:KeyInfo><xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><xenc:CipherValue>G8qlSNo+xiCeszt9eybGyhiIJu8lcy1N8RR56Hvzs59kRnH5jaWMYnZ4qzXVTtCNHXwMF1G7bQAReqyJYR0QB7uQMDuti6Dw6yYJJYvUAy8gPxic+b+UqYNEQ8Ytf5Dm+P+85sF2Tqk49ZmhWQWDw84qIavEALZRKCW1eRJy4dSKHyC49or1k0GsMsKbYCsAhQaa942aTwTjwRi77yGpS35UH9layj2AhRHE8tg1rxoxGtyaQsFFoQ3d3z+ohQeLh83ZVeo5l0/N/zfmPqaIbKyhDoi19Z+p53qOt5jZjDVDSiB4Bc2zxMdpu72A06R8UsJepPkr/Bh2xPHGP3LDOw==</xenc:CipherValue></xenc:CipherData></xenc:EncryptedKey></ds:KeyInfo><xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><xenc:CipherValue>Uw6UvFziGdxjYHDGagqdNwmi5PZt1e6rn/GapCm1F0hFF1XeRfu7Y2XheFBsrwP2P1z++iDhKCqX4gzsnUoPv7SumNL+kUedpEVMKaDtyB1NONGR6XJPx+fLPTiiLOADFAi/K1D1HSRcPiGNIUxDzldpBd6YNolnCw1FltS6mSHDwVaKGBS9cl4tOY+aZTIzA9lBS+rxcZ9og6kkG9TFjq8mr5cad7H5cRspbTgjEep+haJkvNM+FfuESY7PLWOxToLxqlh3eVSUNt1kegnIo07EvKmXp1PBNdjz+2fVb6Vu8WUei2lZRFOPqpr58AnrUXgCSBvNFhgkNcZeqPnNoxg57ujsHMjZnB2yqo+tRb5ZXSi4XKx5rTPFMBDciLGnI6+HwxyuCgj942IuIiHMVeB5iSZUTR/xXjgRkEPX2YYJzDvtKo55lBPoXn1xcsPLI1hWgYmIFk1stWzwvOKceJdYVaULKtr2ZEgsleTpF+knIzQpjCL3YoSluYzKLqLrTtFOm9MIWddtU3t8XsacebonNEalbQhYHFXCMTrjVTJeejy0hitINHK/0EhPHVeevRQh7GCrK6bHPRdt8a3Djg/8SnEDg0/qTH7OXLfa2SoDHQZaQ9KGHWQDiQam0+LAg/OzHQZwgifHLVf+ru00G7+G23o/r7UupcV45e3puerV22/q1ib/OV0TcJo+R1JcMXIuYycYdsW3XeY9GVKw1fWsdQdGwi+EWLQ1PVxP0RJxI90kayZl2hOpS2Qr0tMdxi1aaoFhvh2Gh6/deQH0GZA7VIYyxRDBBMLlwLAykm9ik3i2ShKYQwv64NUbGTjVXwFXIukYALg+mP4CusT0ydzVQOxiBZwH4v94lpTnCZCmg7pJ3W/R+syveFo1NpnWx3bcD0RgnKpH7ON4o5H0fyjUlAjessY+OhPeVYIu0uD0hRX6XUuMc/eVNkhNCHDwjASpNf10kTvvToStzODtLmSQeUXKnqHt2BJmmpu0IJs9khPT+hdkr1gpLzx8suPrWbrvlBAHYlt9w3DDBYe7qpworhNZl1/nKSE+UfUaXz0HbXSEOb9vbIo5UgikjSNg3omo+mXpxOuyGJ43RH89rglU4jhvSvWeOCBlORPiJ4Hpagd6WjviR8wArn5wW6xph/nEWpoAdVflO4Him1bmPisiTZFvQylpzV4FrjXk39CM3rs4800wkW5HyVhVm2aLKbLlNs/hSfmhWIG6j8g7H7BKb8Gyd0OVSGj4r74CYZjHROGxSilVvpoJmtH3BKZEz6600xrhhGYGDMuWJP/bhdUHEY9HD9AaqSmMuGznWAb4prmYIrXjpOp2GAzn3POtzl8Z6qsf7MQtZyd/bc42Vl4WDgu+Q3ZQpIA0pEhtQ0YUx7wuH5njvnaRIfD98Vb640kn5Y/YJde11wddcdIqFlF3f15mmSoYUkoNjUlu7ULv79xa2YU+Tidz3ToAHd41UYCBcN6dd+e+mXAc6Y2dZ3yRczpEDLKIjnj9ICfdP+Xd+v6d1cljtLyKHqlKEJyUOQ9flI/yaB2Tc87eY1Ch2ucv2uXQfSO2Qp4gpaQsZLo0hMLzTgfgiUKfW5sv3W78SNpJc+ZlTQAt4Ttd2OyCs1EDxfVWAtHXKahfyoA21GnORha7kXpVud/zpup+RH0b+42dcfY//5qKBI396p9BN6ggmO4Lql64L5FTLFevagF+5qdR4IFRyHNSrQpCqwq8hBhgjkebqFqnR/8vpYc4ZFJ2IzIhdo+qM/SSSDYoES0/DDLVVcnohc1NQfYTnhO8acrvDL8I84TtHA4AR8wto0aiHYL7Awa2QcCynFxPev0PLWoXQlUw6n90YfrPt+CgXFIg0pMSlPdMWhKFPjogRpUV5dz+5q0F/jrZoagY+X8lgsAmDVOYK6715fsqGN0z8Leu6qz/mY7tQvZ3CwZWlI4+LY0pWQ6TP4rgPqPJg8aJSzKDlFAWJE182Xd40l4MzGBL42US3gy2x+HI3K8Byr2hc3XHRlbxZiPQppBfz7FT69ST3gz1qFNb9TWORspjjmfTtgy5fL70WlGhpS4EqLZKdrYMRCgwH5+jfox5Ed9FRO1Tmcb4spSWCUZgFUks2rYGwwkSZZLP0MLy9XuqtfnRROvobvRjjQaEiQljp4/2iDR7zHDaeIJZ1Z3e+Itn6RMV9tW8Gp5XU3VtapAVyxGSyTPF2UFO8pGUxZ3cgXNWz/CHOTYQD5taHQ==</xenc:CipherValue></xenc:CipherData></xenc:EncryptedData></saml2:EncryptedAssertion></saml2p:Response>
KeyInfo:X509Data:X509Certificate element this cert is valid. But in IP metadata xml have other certificates. While login we parse this cert
in Utils.php file using XMLSecEnc::staticLocateKeyInfo($objKey, $objDSig) but after this overwrite it with cert from $multiCerts param ($objKey->loadKey($cert, false, true)) and get Signature validation failed. Can we set cert from SAMLResponse to validate somehow or it is problem on IP side and he should set valid certificate in his metadata xml ?
Thanks!

**Comment by vlkf** [comment]
how did you resolved this problem? I have a similar error.

**Comment by yuryfilippovich** [comment]
I error can be caused by many reasons. I closed issue because in my case it
was a problem on identity provider side ( he not update his metadata and I
have not valid sertificate in configuration. In general this error means
that signature in request was created by another certificate and you
certificate in ip config can't validate it

ср, 2 нояб. 2022 г., 15:57 vlkf ***@***.***>:
