### ISSUE TITLE
Wrong element order in generated metadata

### ISSUE THREAD

**Issue by ElteHupkes** [onelogin/php-saml#54]
Though I'm not certain why, the SAML2 metadata schema imposes an order on the md:NameIDFormat, md:AssertionConsumerService, etc elements. I found the basic order here: 

https://wiki.shibboleth.net/confluence/display/SHIB2/MetadataForSP

This is violated in `Metadata.php` by including the md:SingleLogoutService tag after the md:AssertionConsumerService tag. The fix should be as simple as moving the sls to the top of the Md:SPSSODescriptor tag, i.e. above md:NameIDFormat (i.e. move `{$sls}` from line 100 to between line 95/96 in `Metadata.php`. I'd create a pull request, but the ratio (time spent fixing the bug)/(time spent setting up stuff to submit a pull request) would tend to zero, so I hope I'm forgiven for hoping someone with direct repo access will do it instead.

I wish I was nitpicking, but unfortunately I have a metadata parser that is tripping over this :{.

**Comment by pitbulk** [comment]
How are you validating the XML?  

As you can see In the Settings.php there is a validateMetadata method where I validate the XML generated by Metadata.php    https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Settings.php#L676
against this XSD: https://github.com/onelogin/php-saml/blob/master/lib/Saml2/schemas/saml-schema-metadata-2.0.xsd

Where the SAML2 metadata imposes the order that you suggested?

P.S I'm ok changing the order, but I don't gonna do a new release only for this change.

P.S2 If you are working in a metadata parser... take a look at:  
https://github.com/Yaco-Sistemas/saml-metadata-editor

Or also http://samlmetajs.simplesamlphp.org/demo (https://github.com/andreassolberg/SAMLmetaJS)

**Comment by ElteHupkes** [comment]
Hi @pitbulk, the metadata is validated at an IDP so I don't know what it is they're using, though I could ask. As far as I know the `<sequence>` tag in the XSD specifies that the elements should appear in that order though, so I guess they have to be (which is not to say I see the actual point of that..). Upon further inspection my IDE also raises this error, so I'm thinking any XSD validator would in principle.

I understand you not wanting to do a release for just this, I'll work around it for now. Thanks for your time anyway!

**Comment by pitbulk** [comment]
Hi @ElteHupkes

In the [original xsd](http://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd) from OASIS there is no <sequence> where md:AssertionConsumerService and md:SingleLogoutService are defined.

Instead we have this other sequence:
```
   <element name="SPSSODescriptor" type="md:SPSSODescriptorType"/>
    <complexType name="SPSSODescriptorType">
        <complexContent>
            <extension base="md:SSODescriptorType">
                <sequence>
                    <element ref="md:AssertionConsumerService" maxOccurs="unbounded"/>
                    <element ref="md:AttributeConsumingService" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>.
                ...
            </extension>
        </complexContent>
    </complexType>
```
And the md:SingleLogoutService appears in the SSODescriptorType, that is extended by the SPSSODescriptorType
```
    <complexType name="SSODescriptorType" abstract="true">
        <complexContent>
            <extension base="md:RoleDescriptorType">
                <sequence>
                    <element ref="md:ArtifactResolutionService" minOccurs="0" maxOccurs="unbounded"/>
                    <element ref="md:SingleLogoutService" minOccurs="0" maxOccurs="unbounded"/>
                    <element ref="md:ManageNameIDService" minOccurs="0" maxOccurs="unbounded"/>
                    <element ref="md:NameIDFormat" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
```

In the implementation that I'm using it seems that the md:SingleLogoutService appears twice:
In the SSODescriptorType and in the SPSSODescriptorType.  

The simpleSAMLphp softwares uses a [similar xsd](https://github.com/simplesamlphp/simplesamlphp/blob/master/schemas/saml-schema-metadata-2.0.xsd) than OASIS. Same the [shibboleth](http://svn.shibboleth.net/view/java-opensaml/trunk/opensaml-saml-api/src/main/resources/schema/saml-schema-metadata-2.0.xsd?view=markup).

I think that the problem is that the IdP defines a xsd with a sequence like this:
```
    <complexType name="SPSSODescriptorType">
        <complexContent>
            <extension base="md:SSODescriptorType">
                <sequence>
                    <element ref="md:SingleLogoutService" minOccurs="0" maxOccurs="unbounded"/>
                    <element ref="md:AssertionConsumerService" maxOccurs="unbounded"/>
                    <element ref="md:AttributeConsumingService" minOccurs="0" maxOccurs="unbounded"/>
                    <element ref="md:KeyDescriptor" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>
                <attribute name="AuthnRequestsSigned" type="boolean" use="optional"/>
                <attribute name="WantAssertionsSigned" type="boolean" use="optional"/>
            </extension>
        </complexContent>
    </complexType>
```

Can you ask the Identity provider admin?

**Comment by ElteHupkes** [comment]
Hmm ok, I see how with the `lib/Saml2/schemas/saml-schema-metadata-2.0.xsd` file having the SLS at the end would be valid per the `SSOPDescriptorType`. Correct me if I'm wrong, but in the OASIS xsd the SingleLogoutService tag would have to be above NameIDFormat am I right? Is there any reason the XSD's are different?

I've asked them for their XSD, but I believe my contact there is not working today, so I'm expecting it either tomorrow or Monday.

**Comment by pitbulk** [comment]
Don't know why they are different.

There is a reason why I'm using those xsd instead the officials: "In the xsd, there are references between the different documents so ones import others. In the officials xsd, those importations are relative to an url so the XML validator download all the xsd in order to do the checks (this consume resources and time). The version that I'm using, use local references, so no download is executed.

I'm ok with the fact of fixing my xsd and change the way the XML metadata is generated.

**Comment by pitbulk** [comment]
@ElteHupkes

I think that now is fixed. Can you check it? (master branch)

**Comment by ElteHupkes** [comment]
Yes indeed, when I follow these instructions to validate the metadata:

https://wiki.surfnet.nl/display/OpenConext/Validating+SAML2+metadata

The metadata file created using the new master does indeed validate, whereas the old one does not. So the change seems to fix it :).

**Comment by ElteHupkes** [comment]
:+1:

**Comment by tsaltena** [comment]
For anyone later revisiting this issue: I had similar order problems in trying to implement eduGAIN. The key issue being that the order of a required 'md:entities' attribute was quite specific. the md:entities needed to be the first child of the SPSSOentities item to still pass the xsd validation. In the code lib\Saml2\Metadata.php:264
>         $SPSSODescriptor->insertBefore($keyDescriptor->cloneNode(), $SPSSODescriptor->firstChild);

The keyDescriptor node is added as a first child. In my implementation, I changed this to 

>         $SPSSODescriptor->insertBefore($keyDescriptor->cloneNode(), $SPSSODescriptor->firstChild->nextSibling);

This is not the cleanest way to resolve the issue as the nextSibling might return false if there is no md:entities, but it addressed the issue for eduGain specifically.
