### ISSUE TITLE
loadXML checking EXXE/XEE attack failing

### ISSUE THREAD

**Issue by zot24** [onelogin/php-saml#55]
On this line: [Utils.php#L53](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L53) you are checking for an `ENTITY` node using `strpos` 

On [PHP documentation](http://php.net/strpos) you could read:

>Warning: This function may return Boolean FALSE, but may also return a non-Boolean value which evaluates to FALSE. Please read the section on Booleans for more information. Use the === operator for testing the return value of this function.

In my case the expression:

```
strpos($xml, '<!ENTITY')
```

Is returning `NULL` so your logic:

```
if (strpos($xml, '<!ENTITY') !== false) {
       throw new Exception('Detected use of ENTITY in XML, disabled to prevent XXE/XEE attacks');
}
```

Is always throwing that `Exception` wouldn't be better if the condition check the expression below instead?

```
if (strpos($xml, '<!ENTITY')) {
       throw new Exception('Detected use of ENTITY in XML, disabled to prevent XXE/XEE attacks');
}
```

**Comment by pitbulk** [comment]
Reference:  http://php.net/functions.internal
```
If the parameters given to a function are not what it expects, such as passing
an array where a string is expected, the return value of the function is undefined.
In this case it will likely return NULL but this is just a convention, and cannot be relied upon. 
```
So the problem is that the $xml is not an string.

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (316/300 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:2049)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.84)
	(envelope-from <bounces+848413-0bd8-marc=marclaporte.com@sgmail.github.com>)
	id 1YKrfm-002XKE-T5
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:58:59 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=6DvW1jWbH9exw502Z2eyfeiqP6o=; b=M5s5mgcToVTI4DIy
	rmxwvVF0aL9y4a2UaVukWPntsEflI1sYr7qHFsYgQBVSBCxjm6xSMLXOOB4JpyGk
	xsBxGlm3SLEioMvEu8PSRtTznTXbgHN7w/06REFIfkO+iWeezcsycxDp30u6Kg+j
	8JgkVgFWi+FlKlkJjFtkv5cOtMk=
Received: by filter0288p1mdw1.sendgrid.net with SMTP id filter0288p1mdw1.9443.54D8E746A
        2015-02-09 16:58:47.091006321 +0000 UTC
Received: from ismtpd-005.iad1.sendgrid.net ([UNAVAILABLE]. [10.42.2.103])
	by 10.42.243.12:2500 (trex/5.2.13);
	Mon, 09 Feb 2015 16:58:48 GMT
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-005 (SG) with ESMTP id 14b6f476cbd.701.18dad0
	for <marc@marclaporte.com>; Mon, 09 Feb 2015 16:58:46 +0000 (UTC)
Date: Mon, 09 Feb 2015 08:58:46 -0800

**Comment by zot24** [comment]
Yep! you're right i just realise what was going on and it was failing because I wasn't sending a XML string I was sending a `OneLogin_Saml2_LogoutRequest`, so I changed that to send the XML instead, however had to do some trick before be able to get what I wanted from the XML:

```php
$request = $logoutRequest->getRequest();
$xml = gzinflate(base64_decode($request));
$nameId = $logoutRequest->getNameId($xml);
```

Thanks of your help, @pitbulk
