### ISSUE TITLE
Check destination doesn't work if you're using Varnish or HAProxy

### ISSUE THREAD

**Issue by zot24** [onelogin/php-saml#56]
Hi @pitbulk!

I got another issue, we got a special config in our server and it seems like some validation are not passing, we got Varnish and HaProxy redirecting some of the request that hit our service, this is the error that we are seeing:

```
The response was received at http://hq.contactzilla.com:8180/saml/consume instead of https://hq.contactzilla.com/saml/consume - Array ( [0] => invalid_response )
```

This is happening because the `Destination` is `https://hq.contactzilla.com/saml/consume` however internally we (Varnish) are parsing that URL to `http://hq.contactzilla.com:8180/saml/consume` instead and the method below is not passing:

```php
// Check destination
if ($this->document->documentElement->hasAttribute('Destination')) {
    $destination = $this->document->documentElement->getAttribute('Destination');
    if (!empty($destination)) {
        if (strpos($destination, $currentURL) !== 0) {
            $currentURLrouted = OneLogin_Saml2_Utils::getSelfRoutedURLNoQuery();
            if (strpos($destination, $currentURLrouted) !== 0) {
                throw new Exception("The response was received at $currentURL instead of $destination");
            }
        }
    }
}
```

I don't wanna turn off the `strict` option however I'm not sure what could be the best option to avoid this situation and be checking the proper URL.

Just wondering if this is related with the `RegExp ACS Valid URL` when configuring the OneLogin connector.

Thanks,

**Comment by pitbulk** [comment]
Is not related with the RegExp ACS Valid URL and you are right, you may set the strict as true.

Destination is the final endpoint that parse the SAML Response (this data is inside the [SAML Response](https://www.samltool.com/generic_sso_res.php))

The currentURL is build by the [OneLogin_Saml2_Utils::getSelfRoutedURLNoQuery()](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L346)  based on the getSelfURLhost, REQUEST_URI, and QUERY_STRING.

If you are under a proxy, maybe you can rewrite the $_SERVER parameters in the saml/consume view to match the expected destination.

**Comment by zot24** [comment]
I'll try to rewrite that params and see whats going on.

Thanks for your help @pitbulk

**Comment by zot24** [comment]
@pitbulk we add `$_SERVER['SERVER_PORT'] = 443;` as you suggested in the controller and that make it work properly :)

Thanks,

**Comment by zot24** [comment]
Just to be sure @pitbulk is this the correct workflow when using your library?

> CZ = Contactzilla our service (SP)

- Create an account on CZ
- Create an account on OL
- Add the CZ connector on OL
- Copy the settings from OL into CZ user
    - Issuer URL
    - Name Id
- Share the connector with others users on OL
- Click and connect

Behind the scene:

- SAMLRequest come with
    - Issuer URL
   - Name Id
- Loop CZ DB looking for the `Issuer URL` load the settings from that entry to your library
- Get the NameId which will be the user email
- Loop CZ Db looking for the email if exist login the user if not redirect to the register page
 
Does this have sense to you? Do I'm missing something? is the Issuer URL unique per connector?

Gracias ;)

**Comment by danmichaelo** [comment]
Just for anyone who googles this and ends up here: the correct solution now is to use

```php
OneLogin_Saml2_Utils::setProxyVars(true);
```

and make sure the [Forwarded headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) are set by the server.
