### ISSUE TITLE
OneLogin_Saml2_Utils::isHTTPS() does not work behind load balancer

### ISSUE THREAD

**Issue by mattzuba** [onelogin/php-saml#57]
Some extra checks for the common (at least in the AWS case) server header X-Forwarded-Proto would be nifty...

https://aws.amazon.com/blogs/aws/keeping-customers-happy-another-new-elastic-load-balancer-feature/

In the case of my AWS setup (and many others), SSL termination is at the load balancer, not at the instances behind it.

**Comment by pitbulk** [comment]
Thanks for comment that. I also found this interesting thread:
https://github.com/dmikusa-pivotal/cf-php-apache-buildpack/issues/6

**Comment by pitbulk** [comment]
@mattzuba issue solved?

**Comment by mattzuba** [comment]
Coolbeans, thanks a lot.  I don't think that completely fixes it though.  I end up with a compiled URL that has https://example.com:80/path.

**Comment by pitbulk** [comment]
Weird, why the 80 port is used for the URL?

**Comment by pitbulk** [comment]
@mattzuba  Can you do some research?

I wonder what string is returned by [getSelfURLhost](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L251) 

Also can you review what happening with the [getSelfHost](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L286) method.


Thanks!.

**Comment by mattzuba** [comment]
Looks like port 80 is returned because that is the SERVER_PORT being reported, which is technically correct.  When I force $_SERVER['SERVER_PORT'] = 443; at the start of my script, I get the expected value from getSelfURLhost.  Amazon passes a X-Forwarded-Port header that could probably be checked as well.

**Comment by pitbulk** [comment]
Can you test again?

**Comment by mattzuba** [comment]
Almost!  Needs to be HTTP_X_FORWARDED_PORT, rather than X-Forwarded-Port.  I changed that real quick on my local copy and it worked like a champ!

**Comment by mattzuba** [comment]
BTW, you guys rock!  We currently use Okta for our SSO solution, but we've decided to use this php-saml library for working with Okta in all of our future projects that we tie into SSO.

**Comment by pitbulk** [comment]
Sorry I wanted to fix that fast and I never noticed the lowercase issue.

I assume you mean get changed to OneLogin from Okta. I appreciate that you value ​​our work. 
Thank you too for contribute in this PHP SAML Toolkit.
