### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by jordipolo87** [onelogin/php-saml#66]
Why you don't use namespaces for the library inclusion?
Thanks!

**Comment by pitbulk** [comment]
We avoid to use namespaces due compatibility issues with the first version of this toolkit.

but, do you think that a class named OneLogin_Saml2_XXX can have conflicts?

I'm using this toolkit in several projects using composer and never had an issue due namespace conflict.

**Comment by jordipolo87** [comment]
What I like about namespaces is that the inclusion of the library is cleaner.
Thanks for developing the library! :)

**Comment by adrian7** [comment]
yes namespaces would be a good addition. eventually fork the version 2 in a new project to avoid conflicts.

**Comment by martynbiz** [comment]
Are you referring to >=PHP5.3 namespace? 

e.g. OneLogin_Saml2_Auth ---> OneLogin\Saml2\Auth

That would be nice.. well, neater :)

**Comment by Hikariii** [comment]
I think this would be a great addition.
Just see https://mwop.net/blog/254-Why-PHP-Namespaces-Matter.html for some readup on why code organisation and readability matter.
Improvement for a 3.* version?

**Comment by pitbulk** [comment]
This is aligned with your [proposal of psr7](https://github.com/onelogin/php-saml/issues/162)
