### ISSUE TITLE
Error on SLO

### ISSUE THREAD

**Issue by citosid** [onelogin/php-saml#70]
I'm receiving this error when trying to log out the user:

```
The SAML Single Logout request does not correspond to the logged-in session participant.
Requestor: https://siteorg/adfs/metadata
Request name identifier: Format: urn:oasis:names:tc:SAML:2.0:nameid-format:persistent, NameQualifier:  SPNameQualifier: https://siteorg/adfs/metadata, SPProvidedId: 
Logged-in session participants:
Count: 1, [Issuer: https://siteorg/adfs/metadata, NameID: (Format: urn:oasis:names:tc:SAML:2.0:nameid-format:persistent, NameQualifier:  SPNameQualifier: , SPProvidedId: )] 
 
This request failed.
 
User Action
Verify that the claim provider trust or the relying party trust configuration is up to date. If the name identifier in the request is different from the name identifier in the session only by NameQualifier or SPNameQualifier, check and correct the name identifier policy issuance rule using the AD FS Management snap-in.
```

And the configuration: 

```php
<?php
/**
 * Configuration file for the federation with site.org
 * This is done using the site site.org
 *
 * @package Main
 * @subpackage Controller
 * @author Abraham Cruz <acruz@site.org>
 * @version $Id: site.org.saml.php 1 2015-05-26 site.org $
 * @license @todo
 */

/**
 * Name of the server we are at this point. This is needed to avoid hardcoding
 * the name of qa, dev* or www
 *
 * @var string
 */
$server = "https://{$_SERVER["SERVER_NAME"]}";

/**
 * Let's return the configuration so this file can only be used by doiong
 * include 'site.org.saml.php',
 *
 *
 * @var array
 */
return [
    /*
    If the responses/requests are marked as signed, but it is received unsigned,
    the library will throw an exception
     */
    'strict' => true,
    /*
    We only debug if we are in QA o dev
     */
    'debug' => $server != "https://www.site.org",
    "security" => [
        'logoutRequestSigned' => true,
    ],
    /*
    Service provider configuration
     */
    'sp' => [
        /*
        The Entity name is the URL of the server plus the location of the metadata
        xml file
         */
        'entityId' => "{$server}/adfs/metadata",
        /*
        To this url will be redirected the callbacks
         */
        'assertionConsumerService' => [
            'url' => "{$server}/adfs/saml2",
            "binding" => "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"

        ],
        /*
        To this url will be redirected the logout callback
         */
        'singleLogoutService' => [
            'url' => "{$server}/adfs/logout",
            "binding" => "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        ],
        /*
        format of the nameid.
        We need it to be persistent
         */
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        /*
        Location of the publick key to check if the callback information is correctly signed
         */
        'privateKey' => file_get_contents(_APP_ . "includes/federation/site.key"),
        'x509cert' => file_get_contents(_APP_ . "includes/federation/site.crt"),
    ],

    'idp' => [
        'entityId' => 'http://site.org/adfs/services/trust',
        'singleSignOnService' => [
            'url' => 'https://site.org/adfs/ls/idpinitiatedsignon',
        ],
        'singleLogoutService' => [
            'url' => 'https://site.org/adfs/ls/idpinitiatedsignon',
        ],
        'x509cert' => 'MIIC1....xMw=',
    ],
];
```

**Comment by pitbulk** [comment]
ADFS requires that the NameID sent in the SAMLResponse matchs the  NameId of the Logout Request.

So review the NameIDFormat of the settings and how you build the Logout Request.

**Comment by citosid** [comment]
Thanks a lot @pitbulk! I can see in the error the requests are different. 


The question is: how can I set the logout request to sent the SPNameQualifier? I have read the code and don't find anyway to do it...

Thanks for your help!

**Comment by pitbulk** [comment]
At this example you see how create a Logout Request with a custom NameID and custom SessionIndex:
https://github.com/onelogin/php-saml/blob/master/demo1/index.php#L32

See how we saved it from a previous SAMLResponse on the session:
https://github.com/onelogin/php-saml/blob/master/demo1/index.php#L48

You can set the NameIDFormat at the settings:
https://github.com/onelogin/php-saml/blob/master/settings_example.php#L40

**Comment by citosid** [comment]
@pitbulk This is my code:

1. Method that is called when the user is logged in
```php
    /**
     * Callback for the federation service. This will be called by the IDP after
     * the user logs in successfully.
     *
     * @return void
     */
    public function saml2Action()
    {
        $_POST = $this->_request->post;
        $this->_auth->processResponse();

        if(!$this->_auth->isAuthenticated()) {
            /* Something failed at the authentication page, so we don't know
            who the user is. Redirect to the site, and show the error. */
            $this->_session->data("federation_errors", $this->_auth->getErrors());
            $this->_redirect("/federation/error");
        }

        /* Now, let's use the information to save it in database, in the session of the
        current user */
        $federationData = [];
        $federationData['samlUserdata'] = $this->_auth->getAttributes();
        $federationData['samlNameId'] = $this->_auth->getNameId();
        $federationData['samlSessionIndex'] = $this->_auth->getSessionIndex();

        $this->_session->data("federation", $federationData);
        $this->_redirect("/federation/ok");
    }
```

2. Method that calls the logout URL
```php
    /**
     * Method to start the logout process. If the usr is not logged in with
     * federation, it will be redirected to /member/logout, otherwise will be
     * redirected to the IDP logout page
     *
     * @return void
     */
    public function destroyAction()
    {
        $federationData = $this->_session->data("federation");
        if (!$federationData) {
            $this->_session->remove();
            $this->_redirect("/member/logout");
        } else {
            $this->_auth->logout(
                "https://{$_SERVER['SERVER_NAME']}/adfs/logout",
                [],
                $federationData["samlNameId"],
                $federationData["samlSessionIndex"]
            );
        }
    }
```

And finally, my NameID definition:

```php
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
```

What do you think I'm making wrong? I'm new to this federation world. We notice the "persistent" format is the only one that works with our IDP

**Comment by pitbulk** [comment]
I think that the settings on the SP side are ok.

Do you have access to the ADFS IdP?
Review this resource:
https://technet.microsoft.com/en-us/library/gg188595.aspx

**Comment by citosid** [comment]
@pitbulk one of the members of the development crew help me to notice that file LogoutRequest.php:65 has the code that adds the SPNameQualifier. If I delete it and set it empty, it works ok. 

That is a solution, another one will be add another param to the function, to avoid include it. But still feels akward. I'd prefer to know how to add that to the metadata...

**Comment by pitbulk** [comment]
On [that commit](https://github.com/onelogin/php-saml/commit/6c07e5be7c53c8e3a19c2652a897e813e0236a69) I setNAMEID_UNSPECIFIED as default NameIDFormat. I think that solve the problem.

@citosid  can you update your PHP toolkit with the master branch and see if your problem is gone?

**Comment by raijinsetsu** [comment]
I am also experiencing this issue. I pulled master from your fork but it appears to be overriding parts of my configuration in an odd way. For example: I have configured my SP to use rsa-sha256 for the signature algorithm but your fork overrides that and sets it to rsa-sha1 which is not acceptable to my IdP.
I am going to continue to monkey around with it, but thought you should know.

**Comment by pitbulk** [comment]
How are you configuring that? Are you using the new [signatureAlgorithm parameter](https://github.com/onelogin/php-saml/blob/master/advanced_settings_example.php#L65)?

**Comment by raijinsetsu** [comment]
Yes.
Also, I am loading my settings explicitly and supplying them to the
constructor rather than having the toolkit search for the files.

The good news is that if I apply just the patch, and one other change to
the generateNameId utility function, it works correctly and AD FS no longer
returns an error.

**Comment by pitbulk** [comment]
Can you detail the problems that you are experiencing related the rsa-sha256?

**Comment by raijinsetsu** [comment]
Here are the relevant parts of the code

config/saml.php
````
return array(
'security' => array(
        'requestedAuthnContext' => false,
        'authnRequestsSigned' => true,
        'logoutRequestSigned' => true,
        'logoutResponseSigned' => true,
        'signatureAlgorithm' => '
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
    ),
...
````
handler.php:
````
$auth = \OneLogin_Saml2_Auth(require('config/saml.php'));
...
$auth->logout(null, $options, $nameID, $sessionIndex);
````

With 2.6.0 installed by Composer, the SigAlg in the redirect is correctly
set to sha256. If I use your fork, sha1 is used regardless of my setting.
My IdP is configured for sha256.

**Comment by pitbulk** [comment]
@raijinsetsu but what fork do you mention? version 2.6.0 is the latest and recommended version.

If you check the [changelog](https://github.com/onelogin/php-saml/blob/master/CHANGELOG) both related functionality mentioned (RSA-SHA256 support and Set NAMEID_UNSPECIFIED as default NameIDFormat) were introduced.

**Comment by raijinsetsu** [comment]
@pitbulk Apparently, I got your commit and citosid's branch mixed up. I thought those were the changes you made to resolve this. You can ignore the SHA1 issue. Sorry about that.
I'll re-test with the correct repo.

**Comment by raijinsetsu** [comment]
Yeah. My issue is still reproducible with 2.6.0 (which is what I was running all along). AD FS just does not like the SPQualifierName attribute in the NameID element. Without it, the user is correctly logged out. Citosid's patch mostly fixes the issue, though I had to make an additional change to generateNameID so that it would not add the attribute if the flag was passed in.

Let me know if there is additional information you need.

**Comment by pitbulk** [comment]
Ok, I will review it and implement a solution for the SPQualifierName issue.

**Comment by pitbulk** [comment]
I think we will be ok with this commit:
https://github.com/onelogin/php-saml/commit/b1608fb9a7ea932bc758dc25988705c35b2dfac3
