### ISSUE TITLE
invalid saml response

### ISSUE THREAD

**Issue by romantico** [onelogin/php-saml#72]
i am using azure as my IDP  i think all my settings are fine but it displays invalid response.. when i edit response.php and print the decoded based 64 reply from it displays the attributes... but how come it traps the response ??

**Comment by romantico** [comment]
PHNhbWxwOlJlc3BvbnNlIElEPSJfMjM0YTU1MzktZmRhMS00NzY0LTg3OGItZGFhMDA4YjFiY2VjIiBWZXJzaW9uPSIyLjAiIElzc3VlSW5zdGFudD0iMjAxNS0wNi0wOVQwMzowMDoxOC4xNTBaIiBEZXN0aW5hdGlvbj0iaHR0cDovL2xvY2FsaG9zdC9waHAtc2FtbC0yLjQuMC9kZW1vMS9pbmRleC5waHA/YWNzIiBJblJlc3BvbnNlVG89Ik9ORUxPR0lOX2EwNmYzNzM5MjJhYzBhM2VjNDExMGYzZDc0ZjMyM2ZiNzQ5OTgyYjEiIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiPjxJc3N1ZXIgeG1sbnM9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPmh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzQxMDZkZjhjLTBhZmQtNDUzNy1hOTUyLTcwNjIzMzJmYmFjMC88L0lzc3Vlcj48c2FtbHA6U3RhdHVzPjxzYW1scDpTdGF0dXNDb2RlIFZhbHVlPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6c3RhdHVzOlN1Y2Nlc3MiLz48L3NhbWxwOlN0YXR1cz48QXNzZXJ0aW9uIElEPSJfMDMzZGEzMWUtMzJjNS00ZDEzLTk0ZGItYWQwYWIzMmFkOTFjIiBJc3N1ZUluc3RhbnQ9IjIwMTUtMDYtMDlUMDM6MDA6MTguMTM0WiIgVmVyc2lvbj0iMi4wIiB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+PElzc3Vlcj5odHRwczovL3N0cy53aW5kb3dzLm5ldC80MTA2ZGY4Yy0wYWZkLTQ1MzctYTk1Mi03MDYyMzMyZmJhYzAvPC9Jc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIvPjxkczpSZWZlcmVuY2UgVVJJPSIjXzAzM2RhMzFlLTMyYzUtNGQxMy05NGRiLWFkMGFiMzJhZDkxYyI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8+PGRzOkRpZ2VzdFZhbHVlPkFEdmVKbU9Hc1VGZkN6Vjh6U2EvTURBVTkvMytzMXdtT3ZDeXJZTXc5Tkk9PC9kczpEaWdlc3RWYWx1ZT48L2RzOlJlZmVyZW5jZT48L2RzOlNpZ25lZEluZm8+PGRzOlNpZ25hdHVyZVZhbHVlPkZlRzFCSUZlczJsVEFUd1ZJMTc1a1dSQXROcEtocFpiNVcwTlliaG5KSTc3VW43a0hDUHdTWDVnRklaUWc5bERJMzFVUll5RDVUYWM4U3RHU2krOTVFRTVpUDRjOWZwMW10YUNwZXRxSUcxM2VwQS82MnlnWXhyalNaRWVZVlJRUm1zUUFRVnZySGw1OXRlWmtQRW4yYTJiakFmenhFNjE1aEU5Vzd3VmZaNlpwNGE5K0daL2FkQTZaUWpxV3k5WG54ZU5QRnZGay85MW9XajlGM3I5eDhkYkhGMFdURzA0TkR0OC9CaU5xRW5kZE9XQWFISmJtTVdVVjNXKzNaQmhQY0JaMmE2ZmtyNkNPMm9ZNkRibzlXZjFNRlhKeFJsbUExWlVQbXBGSTAyaGZWS2hwd3B3R2VVV1hCOUJIMVlYR2JBSmFrcEtxOW5VM1U0UmkvZHNLdz09PC9kczpTaWduYXR1cmVWYWx1ZT48S2V5SW5mbyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PFg1MDlEYXRhPjxYNTA5Q2VydGlmaWNhdGU+TUlJQzRqQ0NBY3FnQXdJQkFnSVFRTlhybXpoTE40VkdsVVhEWUNSVDN6QU5CZ2txaGtpRzl3MEJBUXNGQURBdE1Tc3dLUVlEVlFRREV5SmhZMk52ZFc1MGN5NWhZMk5sYzNOamIyNTBjbTlzTG5kcGJtUnZkM011Ym1WME1CNFhEVEUwTVRBeU9EQXdNREF3TUZvWERURTJNVEF5TnpBd01EQXdNRm93TFRFck1Da0dBMVVFQXhNaVlXTmpiM1Z1ZEhNdVlXTmpaWE56WTI5dWRISnZiQzUzYVc1a2IzZHpMbTVsZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHlLcy91UGhFZjd6Vml6amZjci9JU0dGZTkreVVPcXdwZWwzOHpndXR2TEhtRkQzOUUyaHBQZFFoY1huNGM0ZHQxZlU1S3ZrYmNEZFZiUDgrZTRUdk5wSk15L25FQjJWOTJ6Q1EvaGhCamlsd2hGMUVUZTFUTW1WakFMczBLRnZieFc5Wk4zRWRVVnZ4RnZ6L2d2RzI5blFobDRRV0tqM3g4b3ByODlsbXExNFo3VDBtek9WOGt1YitjZ3NPVS8xYnNLcXJJcU4xZk1LS0ZoakthZXRjdGRqWVRmR3pWUTBBSkF6emJ0ZzAvUTF3ZFlOQW5oU0RhZnlnRXY2a05pcXVrMHIwUnlhc1VVZXZFWHMyTFkzdlNnS3NLc2VJOFpabFFFTXRFOS9rL2lBRzdKTmNFYlZnNTNZVHVyTlRyUG5YSk9VODhtZjNUVG9YMTRIcFlzUzFFQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZm9seDQ1dzBpOENkQVVqamVBYVlkaEc5K05ESHhvcDBVdk5PcWxHcVlKZXhxUEx1dlg4aXlVYVl4Tkd6WnhGZ0dJM0dwS2ZtUVAySlFXUTFFNUp0WS9uOGlOTE9LUk13cWt1eFNDS0p4WkpxNFNsL20vWXY3VFMxUDVMTmdBajhRTEN5cHhzV3JUQW1xMkhTcGtlU2s0SkJ0c1l4WDZ1aGJHTS9LMXNFa3RLeWJWVEh1MjIvN1RtUnFXVG1PVXk5d1F2TWpKYjJJWGRNR0xHM2hWbnROL1dXY3M1dzh2YnQxaThLazZvMTlXMk1qWjk1SmFFQ0tqQkRZUmxoRzFLbVNCdHJzS3NDQlFvQnp3SC9yWGZrc1RPOUpvVVlMWGlXMElwcEI3RGhOSDRQSjVoWkk5MVI4clIwSDMvYktrTFN1RGFLTFdTcU1ob3pkaFhzSUlLdkpRPT08L1g1MDlDZXJ0aWZpY2F0ZT48L1g1MDlEYXRhPjwvS2V5SW5mbz48L2RzOlNpZ25hdHVyZT48U3ViamVjdD48TmFtZUlEIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6cGVyc2lzdGVudCI+R0FYQVZwWmVBM1hzcG90TUp5SU1td0VVOXE2V21DdkhHWkJzN3BmV2hyWTwvTmFtZUlEPjxTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+PFN1YmplY3RDb25maXJtYXRpb25EYXRhIEluUmVzcG9uc2VUbz0iT05FTE9HSU5fYTA2ZjM3MzkyMmFjMGEzZWM0MTEwZjNkNzRmMzIzZmI3NDk5ODJiMSIgTm90T25PckFmdGVyPSIyMDE1LTA2LTA5VDAzOjA1OjE4LjEzNFoiIFJlY2lwaWVudD0iaHR0cDovL2xvY2FsaG9zdC9waHAtc2FtbC0yLjQuMC9kZW1vMS9pbmRleC5waHA/YWNzIi8+PC9TdWJqZWN0Q29uZmlybWF0aW9uPjwvU3ViamVjdD48Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMTUtMDYtMDlUMDI6NTU6MTguMTM0WiIgTm90T25PckFmdGVyPSIyMDE1LTA2LTA5VDAzOjU1OjE4LjEzNFoiPjxBdWRpZW5jZVJlc3RyaWN0aW9uPjxBdWRpZW5jZT5odHRwOi8vbG9jYWxob3N0L215YXBwPC9BdWRpZW5jZT48L0F1ZGllbmNlUmVzdHJpY3Rpb24+PC9Db25kaXRpb25zPjxBdHRyaWJ1dGVTdGF0ZW1lbnQ+PEF0dHJpYnV0ZSBOYW1lPSJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL2lkZW50aXR5L2NsYWltcy90ZW5hbnRpZCI+PEF0dHJpYnV0ZVZhbHVlPjQxMDZkZjhjLTBhZmQtNDUzNy1hOTUyLTcwNjIzMzJmYmFjMDwvQXR0cmlidXRlVmFsdWU+PC9BdHRyaWJ1dGU+PEF0dHJpYnV0ZSBOYW1lPSJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL2lkZW50aXR5L2NsYWltcy9vYmplY3RpZGVudGlmaWVyIj48QXR0cmlidXRlVmFsdWU+YjI3Mzk4MzYtODFkNS00YWZmLTgyYTEtY2ZiZDkzYjMwZDdhPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiPjxBdHRyaWJ1dGVWYWx1ZT5yb21hbnRpY29AdGlsYS5vbm1pY3Jvc29mdC5jb208L0F0dHJpYnV0ZVZhbHVlPjwvQXR0cmlidXRlPjxBdHRyaWJ1dGUgTmFtZT0iaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI+PEF0dHJpYnV0ZVZhbHVlPkdlcm9uYTwvQXR0cmlidXRlVmFsdWU+PC9BdHRyaWJ1dGU+PEF0dHJpYnV0ZSBOYW1lPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiPjxBdHRyaWJ1dGVWYWx1ZT5Kb2huIFJlbmRob248L0F0dHJpYnV0ZVZhbHVlPjwvQXR0cmlidXRlPjxBdHRyaWJ1dGUgTmFtZT0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9pZGVudGl0eS9jbGFpbXMvZGlzcGxheW5hbWUiPjxBdHRyaWJ1dGVWYWx1ZT5Kb2huIFJlbmRob24gR2Vyb25hPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vaWRlbnRpdHkvY2xhaW1zL2lkZW50aXR5cHJvdmlkZXIiPjxBdHRyaWJ1dGVWYWx1ZT5odHRwczovL3N0cy53aW5kb3dzLm5ldC80MTA2ZGY4Yy0wYWZkLTQ1MzctYTk1Mi03MDYyMzMyZmJhYzAvPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48L0F0dHJpYnV0ZVN0YXRlbWVudD48QXV0aG5TdGF0ZW1lbnQgQXV0aG5JbnN0YW50PSIyMDE1LTA2LTA4VDE2OjE4OjA1LjU4OVoiIFNlc3Npb25JbmRleD0iXzAzM2RhMzFlLTMyYzUtNGQxMy05NGRiLWFkMGFiMzJhZDkxYyI+PEF1dGhuQ29udGV4dD48QXV0aG5Db250ZXh0Q2xhc3NSZWY+dXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFjOmNsYXNzZXM6UGFzc3dvcmQ8L0F1dGhuQ29udGV4dENsYXNzUmVmPjwvQXV0aG5Db250ZXh0PjwvQXV0aG5TdGF0ZW1lbnQ+PC9Bc3NlcnRpb24+PC9zYW1scDpSZXNwb25zZT4=

**Comment by romantico** [comment]
that reply is from azure but the library traps it into an invalid response.
:(

**Comment by pitbulk** [comment]
This base64 encoded response is invalid.

Try decode it at https://www.samltool.com/decode.php and you will see how there are invalid chars.

**Comment by rendhon** [comment]
PHNhbWxwOlJlc3BvbnNlIElEPSJfNTc3YzA3OWUtODgwNy00ZmMwLTliYjEtN2VhNjM1ZDRkYmQ4IiBWZXJzaW9uPSIyLjAiIElzc3VlSW5zdGFudD0iMjAxNS0wNi0xMFQwMjoyNzowMi41ODZaIiBEZXN0aW5hdGlvbj0iaHR0cDovL2xvY2FsaG9zdC9waHAtc2FtbC0yLjQuMC9kZW1vMS9pbmRleC5waHA/YWNzIiBJblJlc3BvbnNlVG89Ik9ORUxPR0lOX2VkOTI5OTVmODk3NWQzMmNkMjI0YzNjOWI5YjJkMTRjMmUxMzBkNmIiIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiPjxJc3N1ZXIgeG1sbnM9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iPmh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzQxMDZkZjhjLTBhZmQtNDUzNy1hOTUyLTcwNjIzMzJmYmFjMC88L0lzc3Vlcj48c2FtbHA6U3RhdHVzPjxzYW1scDpTdGF0dXNDb2RlIFZhbHVlPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6c3RhdHVzOlN1Y2Nlc3MiLz48L3NhbWxwOlN0YXR1cz48QXNzZXJ0aW9uIElEPSJfY2RlYTY4MmMtYzgzYS00ZWFhLTg3N2QtOGY4NjExYTAzZDZiIiBJc3N1ZUluc3RhbnQ9IjIwMTUtMDYtMTBUMDI6Mjc6MDIuNTcwWiIgVmVyc2lvbj0iMi4wIiB4bWxucz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI+PElzc3Vlcj5odHRwczovL3N0cy53aW5kb3dzLm5ldC80MTA2ZGY4Yy0wYWZkLTQ1MzctYTk1Mi03MDYyMzMyZmJhYzAvPC9Jc3N1ZXI+PGRzOlNpZ25hdHVyZSB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PGRzOlNpZ25lZEluZm8+PGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz48ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxkc2lnLW1vcmUjcnNhLXNoYTI1NiIvPjxkczpSZWZlcmVuY2UgVVJJPSIjX2NkZWE2ODJjLWM4M2EtNGVhYS04NzdkLThmODYxMWEwM2Q2YiI+PGRzOlRyYW5zZm9ybXM+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNlbnZlbG9wZWQtc2lnbmF0dXJlIi8+PGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIvPjwvZHM6VHJhbnNmb3Jtcz48ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8+PGRzOkRpZ2VzdFZhbHVlPk03SHY4L01NU0RIbnFVSUd4emRuSHowbHptTVJ0dStaZHlLUkJaNm11QUE9PC9kczpEaWdlc3RWYWx1ZT48L2RzOlJlZmVyZW5jZT48L2RzOlNpZ25lZEluZm8+PGRzOlNpZ25hdHVyZVZhbHVlPllNWjM1YWhKOGZlZk14M0FYNW1DQzZVK3ZCcGFhREg4MWVNcnhDTjQ2cmlaRDB0MFZhVEdjTk9zOWVwalRhMURyVW1UMEdvbTIxQUl3YVhMZ3RMVGpRbkNaQ29XSXgzNnd2UVhmMWdqZjJoSndzMDArWW1mQy93MFBHZDBnOXZ0a29jL0xUaUxwMTh5b3ErOGJhV05uSmczZFJEckVvOUhnZlA3enR0UjJIQU9yck5sb2NzV2ZVc2NUVFR6R1pzOXNjRHNGYlFCSkpaekpRaHRLYkVCK0M0NHNjVmVRNDVIZnlJRS9HWUNGSXJVQUF6dzEwdytCOW5TZjk3cmQwbXBJYjJzbnVoN1VjcVI2bStVSnlvSUQyQWx0WXdodEx2KytmT2w2cHNKbElCdkZFdFZuU2U4d1o5aHg3K1VSRlFTZnR2V3BNbDBEVE02VitNR2J0WjJOdz09PC9kczpTaWduYXR1cmVWYWx1ZT48S2V5SW5mbyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnIyI+PFg1MDlEYXRhPjxYNTA5Q2VydGlmaWNhdGU+TUlJQzRqQ0NBY3FnQXdJQkFnSVFRTlhybXpoTE40VkdsVVhEWUNSVDN6QU5CZ2txaGtpRzl3MEJBUXNGQURBdE1Tc3dLUVlEVlFRREV5SmhZMk52ZFc1MGN5NWhZMk5sYzNOamIyNTBjbTlzTG5kcGJtUnZkM011Ym1WME1CNFhEVEUwTVRBeU9EQXdNREF3TUZvWERURTJNVEF5TnpBd01EQXdNRm93TFRFck1Da0dBMVVFQXhNaVlXTmpiM1Z1ZEhNdVlXTmpaWE56WTI5dWRISnZiQzUzYVc1a2IzZHpMbTVsZERDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHlLcy91UGhFZjd6Vml6amZjci9JU0dGZTkreVVPcXdwZWwzOHpndXR2TEhtRkQzOUUyaHBQZFFoY1huNGM0ZHQxZlU1S3ZrYmNEZFZiUDgrZTRUdk5wSk15L25FQjJWOTJ6Q1EvaGhCamlsd2hGMUVUZTFUTW1WakFMczBLRnZieFc5Wk4zRWRVVnZ4RnZ6L2d2RzI5blFobDRRV0tqM3g4b3ByODlsbXExNFo3VDBtek9WOGt1YitjZ3NPVS8xYnNLcXJJcU4xZk1LS0ZoakthZXRjdGRqWVRmR3pWUTBBSkF6emJ0ZzAvUTF3ZFlOQW5oU0RhZnlnRXY2a05pcXVrMHIwUnlhc1VVZXZFWHMyTFkzdlNnS3NLc2VJOFpabFFFTXRFOS9rL2lBRzdKTmNFYlZnNTNZVHVyTlRyUG5YSk9VODhtZjNUVG9YMTRIcFlzUzFFQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBZm9seDQ1dzBpOENkQVVqamVBYVlkaEc5K05ESHhvcDBVdk5PcWxHcVlKZXhxUEx1dlg4aXlVYVl4Tkd6WnhGZ0dJM0dwS2ZtUVAySlFXUTFFNUp0WS9uOGlOTE9LUk13cWt1eFNDS0p4WkpxNFNsL20vWXY3VFMxUDVMTmdBajhRTEN5cHhzV3JUQW1xMkhTcGtlU2s0SkJ0c1l4WDZ1aGJHTS9LMXNFa3RLeWJWVEh1MjIvN1RtUnFXVG1PVXk5d1F2TWpKYjJJWGRNR0xHM2hWbnROL1dXY3M1dzh2YnQxaThLazZvMTlXMk1qWjk1SmFFQ0tqQkRZUmxoRzFLbVNCdHJzS3NDQlFvQnp3SC9yWGZrc1RPOUpvVVlMWGlXMElwcEI3RGhOSDRQSjVoWkk5MVI4clIwSDMvYktrTFN1RGFLTFdTcU1ob3pkaFhzSUlLdkpRPT08L1g1MDlDZXJ0aWZpY2F0ZT48L1g1MDlEYXRhPjwvS2V5SW5mbz48L2RzOlNpZ25hdHVyZT48U3ViamVjdD48TmFtZUlEIEZvcm1hdD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOm5hbWVpZC1mb3JtYXQ6cGVyc2lzdGVudCI+TGFhTmRjRkVsWlpQUlFLZVFsaDROZnRueHlvY21ZWEVLYXllczFidkxlNDwvTmFtZUlEPjxTdWJqZWN0Q29uZmlybWF0aW9uIE1ldGhvZD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmNtOmJlYXJlciI+PFN1YmplY3RDb25maXJtYXRpb25EYXRhIEluUmVzcG9uc2VUbz0iT05FTE9HSU5fZWQ5Mjk5NWY4OTc1ZDMyY2QyMjRjM2M5YjliMmQxNGMyZTEzMGQ2YiIgTm90T25PckFmdGVyPSIyMDE1LTA2LTEwVDAyOjMyOjAyLjU3MFoiIFJlY2lwaWVudD0iaHR0cDovL2xvY2FsaG9zdC9waHAtc2FtbC0yLjQuMC9kZW1vMS9pbmRleC5waHA/YWNzIi8+PC9TdWJqZWN0Q29uZmlybWF0aW9uPjwvU3ViamVjdD48Q29uZGl0aW9ucyBOb3RCZWZvcmU9IjIwMTUtMDYtMTBUMDI6MjI6MDIuNTcwWiIgTm90T25PckFmdGVyPSIyMDE1LTA2LTEwVDAzOjIyOjAyLjU3MFoiPjxBdWRpZW5jZVJlc3RyaWN0aW9uPjxBdWRpZW5jZT5odHRwczovL215c2FsZXNmb3JjZXNhbWw8L0F1ZGllbmNlPjwvQXVkaWVuY2VSZXN0cmljdGlvbj48L0NvbmRpdGlvbnM+PEF0dHJpYnV0ZVN0YXRlbWVudD48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vaWRlbnRpdHkvY2xhaW1zL3RlbmFudGlkIj48QXR0cmlidXRlVmFsdWU+NDEwNmRmOGMtMGFmZC00NTM3LWE5NTItNzA2MjMzMmZiYWMwPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vaWRlbnRpdHkvY2xhaW1zL29iamVjdGlkZW50aWZpZXIiPjxBdHRyaWJ1dGVWYWx1ZT5iMjczOTgzNi04MWQ1LTRhZmYtODJhMS1jZmJkOTNiMzBkN2E8L0F0dHJpYnV0ZVZhbHVlPjwvQXR0cmlidXRlPjxBdHRyaWJ1dGUgTmFtZT0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9pZGVudGl0eS9jbGFpbXMvZGlzcGxheW5hbWUiPjxBdHRyaWJ1dGVWYWx1ZT5Kb2huIFJlbmRob24gR2Vyb25hPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vaWRlbnRpdHkvY2xhaW1zL2lkZW50aXR5cHJvdmlkZXIiPjxBdHRyaWJ1dGVWYWx1ZT5odHRwczovL3N0cy53aW5kb3dzLm5ldC80MTA2ZGY4Yy0wYWZkLTQ1MzctYTk1Mi03MDYyMzMyZmJhYzAvPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI+PEF0dHJpYnV0ZVZhbHVlPkpvaG4gUmVuZGhvbjwvQXR0cmlidXRlVmFsdWU+PC9BdHRyaWJ1dGU+PEF0dHJpYnV0ZSBOYW1lPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIj48QXR0cmlidXRlVmFsdWU+R2Vyb25hPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48QXR0cmlidXRlIE5hbWU9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI+PEF0dHJpYnV0ZVZhbHVlPnJvbWFudGljb0B0aWxhLm9ubWljcm9zb2Z0LmNvbTwvQXR0cmlidXRlVmFsdWU+PC9BdHRyaWJ1dGU+PEF0dHJpYnV0ZSBOYW1lPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIj48QXR0cmlidXRlVmFsdWU+cm9tYW50aWNvQHRpbGEub25taWNyb3NvZnQuY29tPC9BdHRyaWJ1dGVWYWx1ZT48L0F0dHJpYnV0ZT48L0F0dHJpYnV0ZVN0YXRlbWVudD48QXV0aG5TdGF0ZW1lbnQgQXV0aG5JbnN0YW50PSIyMDE1LTA2LTA5VDEyOjUwOjQ2LjAwMFoiIFNlc3Npb25JbmRleD0iX2NkZWE2ODJjLWM4M2EtNGVhYS04NzdkLThmODYxMWEwM2Q2YiI+PEF1dGhuQ29udGV4dD48QXV0aG5Db250ZXh0Q2xhc3NSZWY+dXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFjOmNsYXNzZXM6UGFzc3dvcmQ8L0F1dGhuQ29udGV4dENsYXNzUmVmPjwvQXV0aG5Db250ZXh0PjwvQXV0aG5TdGF0ZW1lbnQ+PC9Bc3NlcnRpb24+PC9zYW1scDpSZXNwb25zZT4=

**Comment by rendhon** [comment]
now i think thats a valid reply already but the library stiLL saying it's invalid :(

**Comment by rendhon** [comment]
this is still  'romantico' thanks.

**Comment by rendhon** [comment]
Warning: assert(): Assertion "is_string($xml)" failed in C:\xampp\htdocs\php-saml-2.4.0\lib\Saml2\Utils.php on line 51

Warning: DOMDocument::loadXML(): Empty string supplied as input in C:\xampp\htdocs\php-saml-2.4.0\lib\Saml2\Utils.php on line 58

Fatal error: Uncaught exception 'Exception' with message 'SAML Response could not be processed' in C:\xampp\htdocs\php-saml-2.4.0\lib\Saml2\Response.php:73 Stack trace: #0 C:\xampp\htdocs\php-saml-2.4.0\lib\Saml2\Auth.php(102): OneLogin_Saml2_Response->__construct(Object(OneLogin_Saml2_Settings), 'PHNhbWxwOlJlc3B...') #1 C:\xampp\htdocs\php-saml-2.4.0\demo1\index.php(35): OneLogin_Saml2_Auth->processResponse() #2 {main} thrown in C:\xampp\htdocs\php-saml-2.4.0\lib\Saml2\Response.php on line 73

**Comment by rendhon** [comment]
but i already tried to decode it  and i think it's fine.!

**Comment by pitbulk** [comment]
The last SAML Response is valid (I validated it using https://www.samltool.com/validate_response.php).

but something is wrong since no XML string arrives to the XML loader of the saml toolkit.

As you see in your error trace, something is wrong at the [Auth.php](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L102).

Can you add a breakpoint there and review what is the content of the $_POST['SAMLResponse'] var?

**Comment by rendhon** [comment]
![buang](https://cloud.githubusercontent.com/assets/12823201/8085183/a93a5be6-0f43-11e5-9926-633c8b055e69.png)

**Comment by pitbulk** [comment]
You can pass the salesforce url to the login method of the toolkit so after logged you will be redirected to salesforce.

Please read the documentation for more info.

**Comment by rendhon** [comment]
i've been redirected into salesforce by this code .. editing my 'index.php'  ..

if (isset($_POST['RelayState']) && OneLogin_Saml2_Utils::getSelfURL() != $_POST['RelayState']) {
        $auth->redirectTo('https://login.salesforce.com');

 but can i directly log in automatically?? by not entering my username and password at all?? what should i set next?

**Comment by pitbulk** [comment]
For that you need to create a federation with the different components:
1  IdP (your identity provider, sts.windows.net)
2. SP1 The php-saml toolkit
3. SP2 Salesforce (you will need to enable SAML on salesforce).

Sorry but this place is to solve issues related with the php-saml toolkit, not to learn how to integrate 3rd party apps or build a SAML federation.

**Comment by rendhon** [comment]
Yeah your right sorry.. anyway i already solve the  issues about this toolkit.. this is really useful .. thnx for help.. ill remove this issue now. thnx.

**Comment by pitbulk** [comment]
No need to remove, we can close it :)
