### ISSUE TITLE
Make OneLogin_Saml2_Auth login, logout, methods return $this->redirectTo

### ISSUE THREAD

**Issue by adrian7** [onelogin/php-saml#77]
Would like to be able to extend the OneLogin_Saml2_Auth and implement a different version of redirectTo to return a custom Redirect object from the framework I use to get dispatched to the browser.

However the login and logout methods return void instead and can't use the return value to pass it on.

Thanks.

**Comment by pitbulk** [comment]
Done

**Comment by adrian7** [comment]
:+1:
