### ISSUE TITLE
Use composer version of xmlseclibs

### ISSUE THREAD

**Issue by chriskl** [onelogin/php-saml#81]
Hi,

Can you just change this library to use robrichards/xmlseclibs as a composer dependency rather than including a copy of the library so that we don't get this kind of thing when installing via composer:

Generating autoload files
Warning: Ambiguous class resolution, "XMLSecEnc" was found in both "/vagrant/vendor/onelogin/php-saml/extlib/xmlseclibs/xmlseclibs.php" and "/vagrant/vendor/rob
richards/xmlseclibs/src/XMLSecEnc.php", the first will be used.
Warning: Ambiguous class resolution, "XMLSecurityDSig" was found in both "/vagrant/vendor/onelogin/php-saml/extlib/xmlseclibs/xmlseclibs.php" and "/vagrant/vend
or/robrichards/xmlseclibs/src/XMLSecurityDSig.php", the first will be used.
Warning: Ambiguous class resolution, "XMLSecurityKey" was found in both "/vagrant/vendor/onelogin/php-saml/extlib/xmlseclibs/xmlseclibs.php" and "/vagrant/vendo
r/robrichards/xmlseclibs/src/XMLSecurityKey.php", the first will be used.

**Comment by pitbulk** [comment]
Hi @chriskl,

we use this toolkit in many PHP projects that does not support composer, that is why I included a copy of the  robrichards/xmlseclibs library instead of add it as composer dependence.

I suggest you that if you adding php-saml as composer dependence you remove the declaration of robrichards/xmlseclibs.

**Comment by skymeyer** [comment]
Hi @pitbulk,

Not having `xmlseclibs` as a separate package is a pain to manage/track security issues. It is unclear and involves manual labor to determine which fixes/version you have pulled into `php-saml`. Actually the current version (2.0.0 "modified") as in the header https://github.com/onelogin/php-saml/blob/master/extlib/xmlseclibs/xmlseclibs.php#L40 doesn't tell us what is actually in there. 

Having `php-saml` available through composer and asking someone to remove `xmlseclibs` which is probably a dependency of another package is counter productive and might not even work properly.

What is the exact reasoning behind having a "modified" `xmlseclibs` besides having other PHP projects not supporting composer ? If this is absolutely required I suggest publishing a forked `xmlseclibs` within your own namespace and referencing that one.

**Comment by pitbulk** [comment]
@skymeyer
We use this toolkit in many old PHP projects that does not support composer, and we can't force them to add composer as dependency, this is the main reason for the forked version of xmlseclibs included at php-saml. And we need it to be included, so I don't need to publish it elsewhere.

I keep update that fork, If you review the commites of php-saml, you can see that I updated the library on [Mar 28, 2016](https://github.com/onelogin/php-saml/commit/7dde06808f4da4cd9290873f7be5d3b932bb90ca) 

If you prefer to use the composer version of xmlseclibs, remove the extlib folder, edit _toolkit_loader.php to not include that folder and add xmlseclibs as composer dependence.

**Comment by pitbulk** [comment]
Or a solution that will work for all of us:

What about adding xmlseclibs as composer dependence and editing _toolkit_loader.php to load the forked version only if there is no XMLSecurityDSig class loaded by composer autoloader?

**Comment by skymeyer** [comment]
@pitbulk that would be great yes.

We need to poke @robrichards to make a new release of `xmlseclibs` as soon as possible as the changes you have pulled in manually do not line up with the latest 2.0.0 release. For example `XMLSecurityKey::getAlgorithm` (https://github.com/onelogin/php-saml/blob/master/extlib/xmlseclibs/xmlseclibs.php#L419) is not in his latest release and comes straight from master.

I'll check to work with him to get a new 2.x release first.

**Comment by pitbulk** [comment]
@chriskl and @skymeyer it seems that 2.0 version was released so is time to fix this issue.

**Comment by skymeyer** [comment]
@pitbulk the 2.0.0 release has been release a while ago, but it doesn't contain i.e. ```getAlgorithm``` which is in master though. Or am I missing something ?

**Comment by pitbulk** [comment]
You are right. Thanks for open the release petition

**Comment by pitbulk** [comment]
I'm waiting for the new release.

I reviewed your forked version: https://github.com/skymeyer/php-saml/commit/9269e816f7f5a7f13f6e1d651975d25230f5c01e

but we will need to make it compatible with the no use of composer as we agreed :)

**Comment by skolodyazhnyy** [comment]
@pitbulk I don't think old php projects which are not using composer is a good argument to keep dependencies inside of the package. 

You always can publish a zip archive with dependencies for these projects which are not using dependency management tools. You could setup a simple service which will upload a new zip archive to [github release page](https://github.com/onelogin/php-saml/releases), every time when you tag something.

- https://developer.github.com/webhooks/
- https://developer.github.com/v3/repos/releases/#upload-a-release-asset

**Comment by hogarthj** [comment]
I just want to note that the "2.0.0 modified" is especially confusing given the only actual difference between 1.4 and 2.0 appears to be namespacing added in 2.0.0 ...

I'm in the process of packaging php-saml for fedora as a dependency to unbundle from nextcloud and unbundling xmlseclibs has been especially problematic as a result.

If you don't want to use the namespaced version might I suggest you instead change this to the 1.4 branch and include that instead to make the versioning clearer.

The test suite does pass using HEAD of the 1.4 branch of xmlseclibs unmodified in any way ...

**Comment by pitbulk** [comment]
Test suite doesn't cover all scenarios. 2.0 bring for example:
```
Add optional argument to XMLSecurityDSig to define the prefix to be used, 
  also allowing for null to use no prefix, for the dsig namespace. fixes #13
```
As soon as a new xmlseclibs version appears I don't have any problem dropping this fork, using directly the official xmlseclibs.

**Comment by Hikariii** [comment]
xmlseclibs has a new 2.0.1 release robrichards/xmlseclibs#104 (comment)
the getAlgorithm method is in there:
https://github.com/robrichards/xmlseclibs/blob/2.0.1/src/XMLSecurityKey.php#L568-L571

**Comment by skymeyer** [comment]
The last release didn't contain the changes yet for https://github.com/robrichards/xmlseclibs/pull/101. I have poked again in the comment section and rebased the PR. Mind poking too on there @pitbulk so we can move this ticket forward as well ? Seems to take some time.

**Comment by Hikariii** [comment]
@pitbulk and @skymeyer, I see a 3.0 version of xmlseclibs has been released: https://github.com/robrichards/xmlseclibs/releases/tag/3.0.0
This remove the dependency on mcrypt.

Rob richards decided to require a minimum of php 5.6 for this library.
See composer file: https://github.com/robrichards/xmlseclibs/blob/3.0.0/composer.json

Installing this via composer is now an option, but it will still conflict with the php 5.3 requirement of php-saml.

My proposal is to start things off the 'right' way and also release a new version of php-saml.
This will allow for Namespacing and the usage of a lot more packages via composer, since more and more libraries depend on php 5.6 or higher.

It also opens the way for work on https://github.com/onelogin/php-saml/issues/162

A new release may even be an opening for a code cleanup, removing the old SAML code.
(stale for 2 years looking at this https://github.com/onelogin/php-saml/tree/master/lib).

**Comment by Hikariii** [comment]
Just to get things started, a version with xmlseclibs as a composer dependency and without mcrypt.
https://github.com/onelogin/php-saml/pull/224

**Comment by pitbulk** [comment]
See [php-saml 3.0.0](https://github.com/onelogin/php-saml/tree/3.0.0) branch
