### ISSUE TITLE
Retrieve Session Timeout after processResponse

### ISSUE THREAD

**Issue by tsmgeek** [onelogin/php-saml#84]
IdP returns a session timeout with the response but this is not returned from the library during auth.
Would it not be best to return the response as part of the processResponse() call or assign it to an internal variable and a getResponse() function returns the class so that the user can extract additional data.

**Comment by pitbulk** [comment]
You are right, we are returning the sessionIndex but not the sessionExpiration (SessionNotOnOrAfter).
Let me fix that.  I will provide a getSessionExpiration available on the Auth object.

I prefer to avoid returning the whole Response object, I'm agree that this is more flexible, but I want to let things simple, and provide the data that you will need.
