### ISSUE TITLE
IDP initiated SSO ?

### ISSUE THREAD

**Issue by jamsheer-thottathil** [onelogin/php-saml#85]
How to implement IDP initiated SSO ?

**Comment by pitbulk** [comment]
This is a toolkit to deploy the SP part.

You can review the [demo1](https://github.com/onelogin/php-saml/tree/master/demo1) and also review the code and also the documentation explain the [demo](https://github.com/onelogin/php-saml#demo1).

**Comment by willbuckner** [comment]
The problem is that `processResponse()` expects a fully-populated settings object that has the expected `idpEntityId`/`Issuer`. How can we know a user's expected IdP Entity ID ahead of time without any context to look up the user? The only way I've been able to make it work is with a hack where I read the Issuer out of the XML ahead of time and feed it to a settings object before even calling `processResponse()`, and this seems like a terrible hack. We need to be able to read the NameId without `isValid()` having passed yet... Or am I missing something?

**Comment by pitbulk** [comment]
This php-saml toolkit was build to work 1 IdP - 1 SP, if you want to support multiple IdPs, you can enable multiple Assertion Consumer Endpoints, each ACS endpoint related to an IdP.

Then in the IdP-initiated scenario, the SAMLResponse will be sent to the correct ACS URL of the SP and you will be able there to validate the SAMLResponse and extract NameID / Attributes.

**Comment by willbuckner** [comment]
It's still not possible with a single IdP. We currently only integrate with OneLogin, but each of our customers will have their own OneLogin account. You're saying we should give each customer their own ACS endpoint?

**Comment by pitbulk** [comment]
If you are using OneLogin, App SAML connector ==  IdP.
Notice how each connector has its own SAML Metadata + public cert.

So if you want to enable multiple App connector (per your customer). Yes, you will need to enable multiple ACS endpoints.  For example:

http://sp.example.com/acs.php?customer=XXX
http://sp.example.com/acs.php?customer=YYY

**Comment by fnox** [comment]
I'm having trouble with the IDP initiated SSO too. The request is validated fine but the Response back is gettig rejected on ADFS end. SP initiated works fine. Is it supposed to work?

**Comment by pitbulk** [comment]
Yes, it is supposed to work. Can you provide more data about what error ADFS replies?

**Comment by fnox** [comment]
That is a bit of a problem. It is run by external partners and I cannot get logs of the error. I am told it gets rejected due to signature validation fails. Is there any way to check that the logoutresponse is valid somehow? I'm using 2.6.1 version btw.

**Comment by pitbulk** [comment]
Register the reply of the IdP (the SAML Response) with [SAML Tracer](https://addons.mozilla.org/es/firefox/addon/saml-tracer/)
