### ISSUE TITLE
getSettings does not return an array

### ISSUE THREAD

**Issue by johansyd** [onelogin/php-saml#88]
This threw me off. I believe getSettings returns an object of the type: OneLogin_Saml2_Settings

see: https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L82

**Comment by pitbulk** [comment]
getSettings returns a  OneLogin_Saml2_Settings object.
[getValues of OneLogin_Saml_Settings](https://github.com/onelogin/php-saml/blob/master/lib/Saml/Settings.php#L57) returns an array.

**Comment by johansyd** [comment]
still wrong according to https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L82

**Comment by johansyd** [comment]
Actually you are returning av object of the type OneLogin_Saml2_Settings not OneLogin_Saml_Settings.

OneLogin_Saml2_Settings doesn't have getValues only OneLogin_Saml_Settings
has getValues.

https://github.com/onelogin/php-saml/blob/v2.6.0/lib/Saml2/Auth.php#L66

https://github.com/onelogin/php-saml/blob/v2.6.0/lib/Saml2/Auth.php#L76

It's both the case on master and in the 2.6.0 release.

It is also quite confusing to see OneLogin_Saml2_Settings and OneLogin_Saml_Settings used interchangeably in the Saml2 code like here:

https://github.com/onelogin/php-saml/blob/v2.6.0/lib/Saml2/Settings.php#L114

**Comment by pitbulk** [comment]
The definition of the method/var was wrong, fixed it.

The OneLogin_Saml2_Auth and the OneLogin_Saml2_Settings constructors expect a $settings var of the type array or of the type  OneLogin_Saml_Auth (the settings object of the old php-saml framework, we keep that for compatibility issues, maybe remove it soon).
