### ISSUE TITLE
php-saml library needs to trim acs and issuer urls coming from the xml assertion

### ISSUE THREAD

**Issue by davidjnelson** [onelogin/php-saml#89]
If the idp doesn't trim the url's when entered into their admin ui, login fails to work as the acs url in the envelope and the acs url on the server don't match.  I would imagine slo and issuer are affected too.  I'll confirm those.

I'm working on a pull request to address this.  Will submit it shortly.

**Comment by davidjnelson** [comment]
Putting a space at the beginning of the acs url in onelogin breaks login.  This is fixed with the incoming PR.  The issuer URL seems to be getting trimmed in the OL admin, but I put a trim in anyway to cover using other IDP's.  The logout url doesn't redirect at all to the acs endpoint if you put a space in front of the url in the OL admin, and this cannot be fixed by this PR, because in that case the redirect never even occurs and the acs endpoint is never even reached.  I put a trim on this too though to be safe.

**Comment by davidjnelson** [comment]
I also made the issuer check a strict type and value equality check changing != to !==.  Was there any reason type coercion was intentionally used here?

**Comment by davidjnelson** [comment]
last thing, modified .gitignore to ignore phpstorm/webstorm/intellij metadata directories.

**Comment by pitbulk** [comment]
The sanitation of the URL should be done at the php piece of code that uses the library if you getting those data from a form, if you are providing the data using the settings file you should insert a correct string. I don't think that this must be done at php-saml library.

**Comment by davidjnelson** [comment]
Thanks for your feedback.  For our situation, the assertion xml itself had a space in front of the acs url because it wasn't trimmed in onelogin's admin ui when input.  I think intercepting the $_POST, url decoding, base64 decoding, then reassembling the assertion xml would not make much sense right?  Is that what you meant?  I can remove all the trim's that aren't coming from the assertion xml message.  Let me resubmit with that - just a sec.

**Comment by pitbulk** [comment]
At your SP you receive a SAMLResponse that has a space in the Destination (acs url), that means that the IdP hasn't got the right data. So the problem is in the IdP side, not in the SP side.
I'm ok an in the OneLogin admin UI should be trimmed the spaces, but meanwhile you will need to fix it manually in the connector.

Reassembling the assertion xml has no sense, is a problem of the IdP that built an invalid SAMLResponse, not SP fault.

**Comment by davidjnelson** [comment]
OK, how about this one?  I'm only trimming the acs url and issuer url that come from the xml assertion in the case that the idp forgets to trim the data on input in their admin web ui.

**Comment by pitbulk** [comment]
I have a dilemma

* I understand that your proposal is a feature that relaxes the SP in the described scenario, but doing that the data on the IdP side never gonna be fixed.

* I understand that getting an error when trying to validate 2 URLS that only differ in 1 space at the start or at the end is also so hard to debug.

I have to think about that and ask what other people think.

P.S Thanks for collaborate.

**Comment by davidjnelson** [comment]
sure np.  

regarding fixing on the idp side, absolutely, all idp's should trim their data when it's inputted into their admin ui's - agreed.  this just helps when it's missed.

regarding the hard to debug, something I thought of was sticking a single quote on both sides, so you'd see:

'http://foo.com' doesn't match ' http://foo.com'

that would be helpful.  the reason I didn't add it is because I didn't think it was needed since it was fixed.

You bet!  Happy to contribute.  Thanks for building such a sweet library that we and so many others have benefited from.  Great work :-D
