### ISSUE TITLE
Allow single log out to work for applications not leveraging php session_start

### ISSUE THREAD

**Issue by davidjnelson** [onelogin/php-saml#91]
Some apps don't use session_start but need to do single logout.  A solution I came up with was a parameter added to processSLO() which defaults the current behavior of calling the redirect, but when specified as a different constant it makes the code return a closure which will call the redirect instead of calling it immediately.

This would allow for scenarios where users don't use session_start, and need to call their own session termination code after the assertion is validated.

Any concerns with this approach?   Thanks!

**Comment by pitbulk** [comment]
At [python-saml](https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/auth.py#L113) I have a session callback.

I thought that this functionality on PHP was not necessary.

At php-saml, on [processSLO](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Auth.php#L150) we can execute or not the fact of [deleting the local session](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L620), so if the app is not using session_start, you can keep the local session and after execute the processSLO you can call the other session termination method.  

This described trick works in case of processing a SAMLResponse, not when processing a SAMLRequest. So maybe we will need that method callback to override the deleteLocalSession call.







https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L620

**Comment by samlev** [comment]
This problem becomes apparent when working with Laravel (and the [laravel-saml2](https://github.com/aacotroneo/laravel-saml2) package). In short, Laravel has it's own session model, and session writes happen with middleware (at the end of the request, all changes to the session are written).

When processing an SLO request, this library redirects back to the IDP, which means that the session changes are never written.

So yes, a 'logout callback' option would be perfect. I'll get a pull request going.

**Comment by pitbulk** [comment]
Thanks, review how we did at the Python toolkit previously mentioned.

**Comment by samlev** [comment]
PR #93 has been added
