### ISSUE TITLE
implement  HTTP POST binding to deliver the SAML <AuthnRequest> to the IdP

### ISSUE THREAD

**Issue by ctamietto** [onelogin/php-saml#92]
I need to promote the login page in Service Provider and ask to provide the credentials for a better user experience . 
I'm using wso2 identity provider that support this feature enabling a Request Path Authentication configuration as basic-auth.
 in this case the SP need send the SAML2 Auth request using SAML2 SSO POST binding , NOT redirect binding .

**Comment by pitbulk** [comment]
The toolkit right now does not support AuthNRequest under HTTP-POST.

**Comment by ctamietto** [comment]
are you interested in supporting this feature in the future ?

**Comment by pitbulk** [comment]
Add that functionality will require some re-build of the toolkit.
OneLogin IdP works with the current bindings so is not a priority for us adding new bindings.
