### ISSUE TITLE
Error with SSO - Unable to Verify Signature

### ISSUE THREAD

**Issue by timtrinidad** [onelogin/php-saml#94]
I'm currently seeing an issue when working with one of our customer's IdPs. Here's what I've observed so far:

* The signature block doesn't seem to be namespaced with "ds:", although it does have the proper xmlns attribute:
```
<?xml version="1.0" encoding="UTF-8"?>
<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
   <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
   <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
   <Reference URI="">
      <Transforms>
         <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
         <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
      </Transforms>
      <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
      <DigestValue></DigestValue>
   </Reference>
</SignedInfo>
```
* In xmlseclibs.php decryptNode(), the following code seems to import the newly decrypted signature block into the original document but places "default:" as the namespace for all elements.
```
$importEnc = $this->rawNode->ownerDocument->importNode($newdoc->documentElement, TRUE);
$this->rawNode->parentNode->replaceChild($importEnc, $this->rawNode)
```
```
<?xml version="1.0" encoding="UTF-8"?>
<default:SignedInfo xmlns:default="http://www.w3.org/2000/09/xmldsig#">
   <default:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
   <default:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
   <default:Reference URI="">
      <default:Transforms>
         <default:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
         <default:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
      </default:Transforms>
      <default:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
      <default:DigestValue></default:DigestValue>
   </default:Reference>
</default:SignedInfo>
```
* This causes a problem when the signature block is run through xmlseclibs.php verifyOpenSSL() since the new namespace doesn't match with the original signed data

Any ideas on what needs to be changed in order to prevent the default namespace from being added? I'd rather not have to code in a text parser to remove the namespace from the generated text.

**Comment by pitbulk** [comment]
This is an xmlseclib issue rather than php-saml issue. Please move the ticket to:
https://github.com/xmlseclibs/xmlseclibs/issues

**Comment by timtrinidad** [comment]
This appears to be related to robrichards/xmlseclibs#27 and onelogin/php-saml#29. I'll go ahead and reply to the issue in xmlseclibs with an example.
