### ISSUE TITLE
$arUrl is an array, used like string

### ISSUE THREAD

**Issue by deed02392** [onelogin/php-saml#95]
$arUrl is an array, used like string.

file_get_contents expects arg 1 to be a string, array provided.

https://github.com/onelogin/php-saml/blob/9f2296343bf8c935434b71e9a78f1d22e1441be1/lib/xmlseclibs/xmlseclibs.php#L827

**Comment by pitbulk** [comment]
Can you report this bug in the original repository?
https://github.com/robrichards/xmlseclibs/blob/master/src/XMLSecurityDSig.php#L477

xmlseclibs  is an external library that we use.

**Comment by deed02392** [comment]
Thanks a lot for the direct link, really appreciate that. Sorry for not realising this wasn't the origin.

New issue created there.
