### ISSUE TITLE
No way to get AuthnRequest Id via AuthRequest object

### ISSUE THREAD

**Issue by crazytonyi** [onelogin/php-saml#96]
The AuthnRequest class `OneLogin_Saml2_AuthnRequest` has a public method `getId` which allows access to the actual ID set for the request. But if request is being initiated via object of `OneLogin_Saml_AuthRequest` class, the `OneLogin_Saml2_AuthnRequest` object is instantiated inside the `getRedirectUrl` method, so it can't be accessed directly. So in the following code:

    $authRequest = new OneLogin_Saml_AuthRequest($settings_obj);
    $auth_url = $authRequest->getRedirectUrl();

There is no way to retrieve the ID of the AuthnRequest through the library, since `OneLogin_Saml_AuthRequest` does not store the ID anywhere and since it doesn't expose the `OneLogin_Saml2_AuthnRequest` object it used to generate the URL to allow calling the `getId` method directly.

This effectively makes the `getId` method unusable and therefore the ID itself unavailable.

Two solutions to consider:

Store the `OneLogin_Saml2_AuthnRequest` object as a public property on the `OneLogin_Saml_AuthRequest` so it gets set inside `getUrl` method like:

    $this->authnRequest = new OneLogin_Saml2_AuthnRequest($settings);

which would allow the code above to retrieve the ID via : 

    $authRequest->authnRequest->getId();

Alternatively, `getUrl` could call `getId` of `$authnRequest` and store it as a public property of it's own, like:

    $authnRequest = new OneLogin_Saml2_AuthnRequest($settings);
    $this->id = $authnRequest->getId();

which would allow the sample code to retrieve the ID with :

    $authRequest->id;

Based on the design of the existing classes and the use of getters and setters, I imagine neither solution is actually quite complete (you'll probably want a getter on the AuthRequest in either case).

Assuming that the SAML2 class is really usurping the original class, couldn't you also change the AuthRequest object to be extended from the AuthnRequest so that it could just call its parent methods as needed as well as inherit the methods, so that  

    $authRequest->getId();

was an option by implicit design?

**Comment by pitbulk** [comment]
Don't use the code of the Saml folder, this is there for compatibility reasons (to be compatible with the 1.1 version).

From 2.0.0 the constructor set the AuthNRequest id as you can see at:
https://github.com/onelogin/php-saml/blob/master/lib/Saml2/AuthnRequest.php
