### ISSUE TITLE
Multiple languages in organization makes invalid metadata

### ISSUE THREAD

**Issue by Ronnie-J** [onelogin/php-saml#99]
Hello.

I am running version 2.6.1.

When I create more than one language in the `organization` array the medatada is not valid when creating a metadata endpoint.

```
'organization' => [
    'en-US' => [
        'name' => 'Corp',
        'displayname' => 'Hello',
        'url' => 'www.webpage.com'
    ],
    'da-DK' => [
        'name' => 'Corp',
        'displayname' => 'Hello2',
        'url' => 'www.webpage.com'
    ]
]
```

When running `validateMetadata` on the class `OneLogin_Saml2_Settings` I get the following error `invalid_xml`

```

Element '{urn:oasis:names:tc:SAML:2.0:metadata}Organization': This element is not expected. Expected is one of ( {urn:oasis:names:tc:SAML:2.0:metadata}ContactPerson, {urn:oasis:names:tc:SAML:2.0:metadata}AdditionalMetadataLocation ).
```

If I remove one of the languages in the `organization` it works as intended.

**Comment by pitbulk** [comment]
Thanks for report this issue. Solved at: https://github.com/onelogin/php-saml/commit/d29b8e0922f8c0ae8e8082f5c9e2a1e59f466931

As described on the SAML specification,
```
<element name="Organization" type="md:OrganizationType"/>
<complexType name="OrganizationType">
<sequence>
<element ref="md:Extensions" minOccurs="0"/>
<element ref="md:OrganizationName" maxOccurs="unbounded"/>
<element ref="md:OrganizationDisplayName" maxOccurs="unbounded"/>
<element ref="md:OrganizationURL" maxOccurs="unbounded"/>
</sequence>
<anyAttribute namespace="##other" processContents="lax"/>
</complexType>
<element name="OrganizationName" type="md:localizedNameType"/>
<element name="OrganizationDisplayName" type="md:localizedNameType"/>
<element name="OrganizationURL" type="md:localizedURIType"/>
```

We defined organization in the same way that ContactPerson (secuence of Organization objects) instead of define an Organization element and inside iterate between the different subelements.

**Comment by Ronnie-J** [comment]
Makes sense. This fix is confirmed working. :+1:
